### ISSUE TITLE
Octave 6 may break our doctests with `format short` changes 

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1000]
Two dozen functions fail doctests because of upcoming Octave `format short` changes.

Octave hg tip:
```
heaviside.m ............................................ FAIL    1/3   

   >> heaviside(0)

      expected:    0.50000

      got     : ans = 0.5000


laguerreL.m ............................................ FAIL    2/5   

   >> laguerreL (14, 6)

      expected:    0.97654

      got     : ans = 0.9765


   >> coeffs = sym2poly (L);
    polyval (coeffs, 6)

      expected:    0.97654

      got     : ans = 0.9765


```

I need to do a 2.8.1 or 2.9.0 *now (well soon)* because of new SymPy 1.5.

But I don't know whether to make these formatting changes *now* or wait and see if Octave 6 really does this change or not...

**Comment by mtmiller** [comment]
Yeah, I asked about that on [Octave#56936](https://savannah.gnu.org/bugs/?56936), and Rik responded that the new behavior is correct and intentional for the next release.

**Comment by cbm755** [comment]
Fixed, maybe I didn't write the commit thingy correctly.
