### ISSUE TITLE
documentiation: @@ym in ezplot

### ISSUE THREAD

**Issue by NRJank** [cbm755/octsympy#1005]
I haven't searched for this elsewhere, but I see that in at least the ezplot docstring a @@ym instead of @sym:

`%% -*- texinfo -*-`
`%% @documentencoding UTF-8`
`%% @defmethod  @@ym ezplot (@var{f})`
`%% @defmethodx @@ym ezplot (@var{f1}, @var{f2})`
`%% @defmethodx @@ym ezplot (@var{f}, @var{dom})`
`%% @defmethodx @@ym ezplot (@var{f1}, @var{f2}, @var{dom})`
`%% @defmethodx @@ym ezplot (@dots{}, @var{N})`
`%% Simple plotting of symbolic expressions.`

which of course renders oddly in the help browser and on the [website documentaion](https://octave.sourceforge.io/symbolic/function/@sym/ezplot.html)

(Symbolic 2.8.0)

**Comment by mtmiller** [comment]
Thanks for finding this typo, easy to look right past that. I found a few more and fixed them all in #1006.
