### ISSUE TITLE
request more detail in 'sympref diagnose'

### ISSUE THREAD

**Issue by kwanlowe** [cbm755/octsympy#1009]
Hello:

This is opened in reference to this thread: https://octave.1599824.n4.nabble.com/Octave-unable-to-find-python-when-using-symbolic-toolbox-tt4695912.html#a4695924

To assist with troubleshooting, is it possible to provide the full path to the python binary that is being used?  I use Python virtualenv and run Octave either from the host installation (e.g., dnf install octave, apt install octave) or via Snaps or Flatpaks. Teasing out which Python is actually being called can help troubleshoot various issues.

Thanks and best regards,
Kwan

**Comment by mtmiller** [comment]
> is it possible to provide the full path to the python binary

You mean you'd like `sympref diagnose` to show the full path to whatever `python` or `python3` that it found in the `PATH`, right?

Just clarifying, at first glance it looked like you were asking if _you_ could "provide" the full path to a Python of your choosing, which yes you can.

**Comment by mtmiller** [comment]
See also #1008 I opened for a slightly different troubleshooting idea.

**Comment by kwanlowe** [comment]
Yes, I'd like the sympref diagnose to show the python path that is being used. 

 I was trying do this with python itself. For example, to get the module info:
```
octave:25> unix("python3 -c 'help(\"modules\")'|grep -i sympy ")
ans =  1
```

I couldn't get a working snippet that would output the detail though..

**Comment by kwanlowe** [comment]
Here's the snippet that should do it:
```
octave:1> unix("python3 -c 'import sys;  print(sys.executable)'")
/home/kwan/bin/python_venv/p36/bin/python3
```

**Comment by mtmiller** [comment]
In OctSymPy terms, that would be

    exe = python_cmd ("return sys.executable");

Would you like to work on PR to add this info to `diagnose`?
