### ISSUE TITLE
Mixing boolean and vector

### ISSUE THREAD

**Issue by jose-matos** [cbm755/octsympy#1013]
Using symbolic I have a problem when working with arrays and symbolic.

Let us assume that a is an anonymous function and e1 is a vector of symbols:

```octave
>> a = @(n) 1 / 2 + 1 / 2 .* (n == 0)
a =

@(n) 1 / 2 + 1 / 2 .* (n == 0)

>> e1 = sym(0:4)
e1 = (sym) [0  1.0  2.0  3.0  4.0]  (1×5 matrix)
>> a(e1)
warning: passing floating-point values to sym is dangerous, see "help sym"
error: Python exception: TypeError: unsupported operand type(s) for *: 'Half' and 'MutableDenseMatrix'
    occurred at line 9 of the Python code block:
    return x*y
error: called from
    pycall_sympy__ at line 178 column 7
    times at line 74 column 5
    @<anonymous> at line 1 column 17
```

Is there any workaround or is this something that can be dealt from symbolic?

Thank you. :-)

**Comment by mtmiller** [comment]
Confirmed, simpler example with a boolean scalar:

```
>> sym(1) .* sym(true)
error: Python exception: TypeError: BooleanAtom not allowed in this context.
    occurred at line 9 of the Python code block:
    return x*y
```

And simpler example with a boolean array:

```
>> sym(1) .* sym([true, true])
error: Python exception: TypeError: unsupported operand type(s) for *: 'One' and 'MutableDenseMatrix'
    occurred at line 9 of the Python code block:
    return x*y
```

A simple workaround for your simple example is to convert `n` to `double` before doing the comparison. I'm not aware of a simple conversion from a symbolic boolean array to a numeric array.

You might want to add some markup to your initial post to make it easier to read.

**Comment by jose-matos** [comment]
Actually it all started because I wanted to avoid the warning:

```octave
warning: passing floating-point values to sym is dangerous, see "help sym"
.... line repeated lots of times ...
warning: passing floating-point values to sym is dangerous, see "help sym"
```

and so I decided to convert first to vpa and then do the calculations.

Finally I decided to silence that warning:
```octave
warning('off', 'OctSymPy:sym:rationalapprox');
```

OTHO I found meanwhile (asking to a colleague) that vpa in matlab (and old version) also does not work. Or better it works but the result is not what we would expect:

```matlab
>> a(e1)
[ 1/2 == 1/2, 1.0 == 0.5, 1.5 == 0.5, 2.0 == 0.5, 2.5 == 0.5]
```

PS: I hope that the text now is easier to read.

**Comment by mtmiller** [comment]
I agree with the Matlab behavior, so there's no compatibility issue here.

> Actually it all started because I wanted to avoid the warning:

Can you show the original expression you wanted to use that gave this warning? That might help clear up what you're trying to do and suggest what workarounds might be easiest to get the result you want.

**Comment by jose-matos** [comment]
> I agree with the Matlab behavior, so there's no compatibility issue here.
> 
> > Actually it all started because I wanted to avoid the warning:
> 
> Can you show the original expression you wanted to use that gave this warning? That might help clear up what you're trying to do and suggest what workarounds might be easiest to get the result you want.

Sorry for taking so long. This period coincides with the pandemics and I have busy with other issues.
Meanwhile I have refactor the code and I am now running 2.9.0 and I do not see that warning anymore.

Thank you for taking care of this. :-)
