### ISSUE TITLE
error: operator =: no conversion for assignment of 'class' to indexed 'scalar'

### ISSUE THREAD

**Issue by asthagurjarmnit** [cbm755/octsympy#1017]

**Comment by cbm755** [comment]
No enough info to reproduce.  I thought this was the error from
```
syms x
[1 x; 3 4]
```
which fails with
```
octave:5> [1 x; 3 4]
error: octave_base_value::map_value(): wrong type argument 'scalar'
```
But that is Issue #8.

If anyone seems this particular error again, please reopen.

**Comment by mtmiller** [comment]
This is similar to #910, but instead of

```
A = []
A(1) = sym(2)
```

start with a scalar

```
A = 0
A(1) = sym(2)
```

**Comment by cbm755** [comment]
Thanks!  Linked to #191 and #910 and the upstream issue(s) mentioned thereof
