### ISSUE TITLE
How can I display latex-style math?

### ISSUE THREAD

**Issue by BiggerHao** [cbm755/octsympy#1024]
I am using GNU Octave 5.2.0 on Windows with octsympy installed through `symbolic-win-py-bundle-2.9.0.tar.gz`.

After I typed `syms x` and `f = 2*sin(cos(x)/2)`, I got something like this:
```
f = (sym)

       /cos(x)\
  2*sin|------|
       \  2   /
```
but the images in README.md show math in latex style. How can I achieve that? I cannot find any relevant information on that.

**Comment by cbm755** [comment]
You can use the `latex(f)` command to generate latex code.

If instead you mean "pretty printing", like:
```
f = (sym)
       ⎛cos(x)⎞
  2⋅sin⎜──────⎟
       ⎝  2   ⎠
```
then see ["I want nice unicode" on the wiki](https://github.com/cbm755/octsympy/wiki/Notes-on-Windows-installation#i-want-nice-unicode-output)

**Comment by BiggerHao** [comment]
@cbm755 Thank you for your prompy reply. I had thought those equations in the following image were rendered using Latex.

![](https://github.com/cbm755/octsympy/raw/master/screenshot.png)

It turns out they are just character art. 😂

**Comment by cbm755** [comment]
Does it work 'out of the box' for you or did you need to install fonts?

**Comment by BiggerHao** [comment]
@cbm755 I set display preference to unicode and installed DejaVu Mono Sans as recommended in #912, then I got the exact result shown in the previous image. Other fonts like Consolas, Courier are not as good.

**Comment by cbm755** [comment]
thanks, so we still cannot change the default of `sympref display` on Windows.  Too bad.
