### ISSUE TITLE
"subs" not found

### ISSUE THREAD

**Issue by wanderworder** [cbm755/octsympy#1029]
Hi,  I'm new here.
I recently installed the latest Octave 5.2.0 and symbolic bundle package 2.9.0 (with tar.gz extension because it's said that Octave 5.2.0 should go with the .tar.gz one) and it ran smoothly with the syms function but when i tried "subs" it didn't work out. It seems like my Octave couldn't even locate the subs because when i executed "help subs" it says 

> error: help: 'subs' not found

I actually had the earlier version of Octave and one earlier version of the symbolic package but i got the same error, so i thought maybe i could uninstall and install the latest one to get a better result but it only appeared with the same error. please help. thanks. :)

**Comment by mtmiller** [comment]
Welcome. `subs` is a method of the `sym` class, so you need to use `help @sym/subs` in Octave.
