### ISSUE TITLE
add methods for "flip" and "rot90"

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#103]

**Comment by latot** [comment]
Hi, i write an octave script to can rotate vectors/matrix, 
An eraser.
```
%% Things

#syms a b;
#m=[1 2;a b];
#x=1;
#y=2;
#order="row";
#r=sym('pi/2');

function v=rot(m, x, y, r, order="row")

t_m=typeinfo(m);

if (!strcmp(class(m),"sym"))
	if (!strcmp(t_m,"matrix") & strcmp(t_m,"scalar"))
		v=m;
		return;
	elseif (!strcmp(t_m,"matrix") & !strcmp(t_m,"scalar"))
		error("Bad Matrix/Scalar Input");
	endif
endif

o_colum=!(strcmp(order,"row") | strcmp(order,"rows"));

if ((o_colum & (x>rows(m) | y>rows(m))) | (!o_colum & (x>columns(m) | y>columns(m))))
	error("Bad rotation axes");
endif

if (o_colum)
	m=m';
endif

if (strcmp(class(m),"sym") | strcmp(class(r),"sym"))
	r_d=sym(eye(columns(m)));
else
	r_d=eye(columns(m));
endif

r_d(x, x)=cos(r);
r_d(y, x)=-sin(r);
r_d(x, y)=sin(r);
r_d(y, y)=cos(r);

result=m*r_d;

if (o_colum)
	result=result';
endif

v=result;

end

syms a b c d
m=[[1 2 3];a b 3;c d 1];
rot(m, 2, 3, sym('pi/2'), "row")
m
```

Have a condition to interpret it, the axes of the vector/matrix should be perpendicular with the others.

the rot function have 5 params, rot(m, x, y, r, order="row"), m-> input matrix, x first axe, y, second axe, it will rotate from x to y, r->rads to rotate, order->rotate from rows or columns.

i don't know if i'm close to your idea of rotate for this D:
the example in the code its a rotation of the matrix (sorted [x y z]->[1 2 3]) of 90° from y to z (2 to 3)

This should works with sym objects, and with n dimentions. the order param i don't know but can be removed its the same to rot(matrix',params...)'.

Cya,

**Comment by cbm755** [comment]
I meant to overload two octave built-in functions: see `help rot90` and `help fliplr`.  Will your code here help with that?

**Comment by latot** [comment]
Hi again, i check this:
/usr/share/octave/4.0.0/m/general/flip.m
/usr/share/octave/4.0.0/m/general/rot90.m

Should works with sym objects, i alredy test some rotation matrix and flip with sym and works fine, but only works if the optional argumants don't are syms, and are integers.
When i read the source it feels like the function is conceived as table rotation system you don't rotate the system you rotate the table it remeber to me the transposition. Its different with the function posted here, its works more like a math rotation, well if you need only rotate in 90° or flip things it should be enough, but if you need more specific things like rotate sym('pi/2*n') (n symbol) rads there you should need the function posted here.

**Comment by cbm755** [comment]
great news that flip etc works on Octave 4!  (did not used to work, maybe on 3.8)
So I can close this bug...

But what to do with your code?  Is there a equivalent Octave function that applies this kind of axis rotation for `double` matrices?

If I am right, your code creates and multplies by a Given's Rotation Matrix.

**Comment by latot** [comment]
i can't found any function to this in octave...
but this rot function returns the type of value depending of the input, if you don't send any sym object should return a normal octave matrix.
you are right it works with Given's Rotation Matrix.
this code works, but i consider it as a eraser, and i probably will make other rot function but it will works with a direction instead of axes.

**Comment by cbm755** [comment]
Ok, I don't think this is something we can merge into Symbolic, at least in current form.  I'll leave this closed for now.  Feel free to open a new bug if you think this code or similar is needed in Symbolic.

Thanks for you help with `rot`, `fliplr` etc.
