### ISSUE TITLE
Sympy not working with octave

### ISSUE THREAD

**Issue by AidanHryc** [cbm755/octsympy#1031]
Whenever I try to use sympy on octave I get the error message of 'sympy.core.compatibility' has no attribute 'integer_types'

>> syms x
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "<stdin>", line 12, in octoutput_drv
  File "<stdin>", line 55, in octoutput
  File "/usr/lib/python3.8/site-packages/sympy/__init__.py", line 677, in __getattr__
    return getattr(self.mod, name)
AttributeError: module 'sympy.core.compatibility' has no attribute 'integer_types'
error: Python exception: AttributeError: module 'sympy.core.compatibility' has no attribute 'integer_types'
    occurred while copying variables to Python.
    Try "sympref reset" and repeat your command?
    (consider filing an issue at https://github.com/cbm755/octsympy/issues)
error: called from
    pycall_sympy__ at line 191 column 5
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13

I've tried using this with sympy of 1.5.1 and 1.6, they both don't work

**Comment by Lafite-Yu** [comment]
downgrade sympy with `pip install sympy==1.5.1` for as a temporal solution, and wait for bugfix.......

**Comment by mtmiller** [comment]
See #1023.
