### ISSUE TITLE
Should contributions here be preferred over sourceforge?

### ISSUE THREAD

**Issue by tpapastylianou** [cbm755/octsympy#1033]
Dear maintainer,

The official octave websites (forge, wiki etc) seem to suggest that the main development location for this package is sourceforge.
But I note this github "mirror" seems to have more activity (18 pull request at the time of writing).

I made a merge request on sourceforge some time ago, based on the fact that it was labelled as the 'official' repository for this package, but I have not received a response.

I understand this may well be because you're busy and that's just the pace of things, but I *did* want to confirm it's not just a case that I chose to put that in the wrong repository and it fell on deaf ears ... (I do note that the sourceforge repository doesn't mention any updates since March)

If it really _is_ the case that the github repository should be preferred for contributions, may I suggest you update the README on the sourceforge side of things to point this out, and redirect traffic here?

Many Thanks

PS. I also note the existence of issue #992, which may relate to this.

**Comment by mtmiller** [comment]
Yes, this is the official development upstream repository. Sourceforge is the mirror.

**Comment by tpapastylianou** [comment]
Hi Mike, thanks for confirming! Would you advise me to create a new pull request here then?

**Comment by mtmiller** [comment]
Yes please! I have never used pull requests on Sourceforge and didn't even know they were an option or people were using them. I certainly wasn't aware that there was a PR on SF for the symbolic package. :grimacing:
