### ISSUE TITLE
Migrate to GitHub Actions for CI?

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#1038]
Travis has recently made some drastic changes away from supporting open source projects for free. Time to migrate to GitHub Actions?

**Comment by cbm755** [comment]
Or Gitlab CI?   I assume GitHub Actions is similar but haven't used it yet.

**Comment by mtmiller** [comment]
Yeah, I forgot that GitLab offers free CI for GitHub projects as well.

I have another repo that I am now planning on moving to GitHub Actions, if that goes well I'll experiment with it here shortly.

**Comment by mtmiller** [comment]
@cbm755 Welcome back! I moved [octave-snap](https://github.com/octave-snap/octave-snap) to Actions, see https://github.com/octave-snap/octave-snap/pull/58.

**Comment by cbm755** [comment]
This is done.  Filed #1070 to try the linter mentioned above.
