### ISSUE TITLE
Problems with symbolic on Mac

### ISSUE THREAD

**Issue by sq7robin** [cbm755/octsympy#1041]
I get the following error message  when trying to start Symbolic in Octave 4.4.1 run under Mac Sierra 10.13.6:

>> syms x
Symbolic pkg v2.7.0: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 12, in octoutput_drv
  File "<stdin>", line 54, in octoutput
  File "<stdin>", line 55, in octoutput
AttributeError: module 'sympy' has no attribute 'compatibility'
Waiting................warning: readblock: timeout of 30 exceeded, breaking out
warning: called from
    readblock at line 101 column 7
    python_ipc_popen2 at line 99 column 14
    python_ipc_driver at line 59 column 13
    python_cmd at line 164 column 9
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
no output so far

error: ipc_popen2: something wrong? timed out starting python
error: called from
    python_ipc_popen2 at line 101 column 7
    python_ipc_driver at line 59 column 13
    python_cmd at line 164 column 9
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13

However, when checked with: 

>> sympref diagnose

Symbolic package diagnostics
============================

Python and SymPy are needed for most features of the Symbolic package.

The Python interpreter is currently: "/usr/local/bin/python3.9".

Computers may have more than one Python interpreter installed.  If you
need to, you can select a different one using the PYTHON environment
variable (see "help sympref").  For example, to use Python 3, try
    setenv PYTHON python3
    sympref reset

Attempting to run /usr/local/bin/python3.9 -c "print(\"Python says hello\")"

status = 0
output = Python says hello

Good, Python ran correctly.

SymPy Python Library
--------------------

SymPy is a Python library used by Symbolic for almost all features.

Attempting to run /usr/local/bin/python3.9 -c "import sympy; print(sympy.__version__)"

status = 0
output = 1.7.1

SymPy must be at least version 1.0; you have version 1.7.1.

Good, a working version of SymPy is installed.

Python XML Parsing and DOM Support
----------------------------------

The XML DOM library is used by Symbolic for passing values to and from Python.
Some older versions of Python formatted XML output differently.  As long as you
have any reasonably recent version of Python, this should pass.

Attempting to run /usr/local/bin/python3.9 -c "import xml.dom.minidom as minidom; doc = minidom.parseString(\"<item>value</item>\"); print(doc.toprettyxml(indent=\"\"))"

status = 0
output = <?xml version="1.0" ?>
<item>value</item>
 
Your kit looks good for running the Symbolic package.  Happy hacking!

>>

everything shall work fine, but isn't...

I tried Python 3.9 and Anaconda. Both do not work with Octave.
Python 3.9 works in IDLE as it should.

Anybody can help?

**Comment by feralber** [comment]
For the moment, the symbolic package does not work with sympy 1.6 or later. You will have to use sympy 1.5.1. See issue #1023.
