### ISSUE TITLE
Several subfolders not in PATH by default

### ISSUE THREAD

**Issue by rotton** [cbm755/octsympy#1044]
When I tried using `function_handle`, it would give me:
`'function_handle' undefined near line 1 column 1`

So I took a look at the search PATH and noticed (Debian 10 example) that Octave's search path contains the following directories:

```
.                                                                      /usr/share/octave/4.4.1/m/miscellaneous
/usr/share/octave/packages/symbolic-2.7.1                              /usr/share/octave/4.4.1/m/ode
/usr/lib/x86_64-linux-gnu/octave/4.4.1/site/oct/x86_64-pc-linux-gnu    /usr/share/octave/4.4.1/m/optimization
/usr/lib/x86_64-linux-gnu/octave/site/oct/api-v52/x86_64-pc-linux-gnu  /usr/share/octave/4.4.1/m/path
/usr/lib/x86_64-linux-gnu/octave/site/oct/x86_64-pc-linux-gnu          /usr/share/octave/4.4.1/m/pkg
/usr/share/octave/4.4.1/site/m                                         /usr/share/octave/4.4.1/m/plot
/usr/share/octave/site/api-v52/m                                       /usr/share/octave/4.4.1/m/plot/appearance
/usr/share/octave/site/m                                               /usr/share/octave/4.4.1/m/plot/draw
/usr/share/octave/site/m/startup                                       /usr/share/octave/4.4.1/m/plot/util
/usr/lib/x86_64-linux-gnu/octave/4.4.1/oct/x86_64-pc-linux-gnu         /usr/share/octave/4.4.1/m/polynomial
/usr/share/octave/4.4.1/m                                              /usr/share/octave/4.4.1/m/prefs
/usr/share/octave/4.4.1/m/audio                                        /usr/share/octave/4.4.1/m/profiler
/usr/share/octave/4.4.1/m/debian                                       /usr/share/octave/4.4.1/m/set
/usr/share/octave/4.4.1/m/deprecated                                   /usr/share/octave/4.4.1/m/signal
/usr/share/octave/4.4.1/m/elfun                                        /usr/share/octave/4.4.1/m/sparse
/usr/share/octave/4.4.1/m/general                                      /usr/share/octave/4.4.1/m/specfun
/usr/share/octave/4.4.1/m/geometry                                     /usr/share/octave/4.4.1/m/special-matrix
/usr/share/octave/4.4.1/m/gui                                          /usr/share/octave/4.4.1/m/startup
/usr/share/octave/4.4.1/m/help                                         /usr/share/octave/4.4.1/m/statistics
/usr/share/octave/4.4.1/m/image                                        /usr/share/octave/4.4.1/m/strings
/usr/share/octave/4.4.1/m/io                                           /usr/share/octave/4.4.1/m/testfun
/usr/share/octave/4.4.1/m/java                                         /usr/share/octave/4.4.1/m/time
/usr/share/octave/4.4.1/m/linear-algebra                               /usr/share/octave/4.4.1/data
```

But `function_handle` is located in the `@sym` subdirectory of `/usr/share/octave/packages/symbolic-2.7.1/`. Shouldn't this be added by default to the PATH? I am not sure if this is a bug in `pkg` or Octave in general.
But the same holds true for my Windows installation. `@sym` is not on PATH there either.

**Comment by mtmiller** [comment]
This is the expected behavior. `function_handle` is a method of the `sym` class, not a bare function. Since it only operates on `sym` objects, calling `function_handle` or `function_handle (2)` results in an undefined error.

It's legitimate to discuss whether Octave should give a hint to the user that the function doesn't exist as called, but would work if you called it with the right argument. But that's a more generic Octave interface design discussion, not specific to this package.

**Comment by rotton** [comment]
Ok, I see. Actually, when I execute [the example](https://octave.sourceforge.io/symbolic/function/@sym/function_handle.html) word by word, it works.

The confusion arises when I expected `function_handle(1)` to throw an error like
`Wrong data type. Symbolic equation expected.`
instead of
`error: 'function_handle' undefined near line 1, column 1`

Or `help function_handle` to print something other than
`error: help: 'function_handle' not found`

Could this behavior be improved?

**Comment by mtmiller** [comment]
Yes, like I said before

> But that's a more generic Octave interface design discussion, not specific to this package.

In other words, there's nothing that octsympy can do about this, but it could be discussed or worked on in Octave itself. If you want to pursue that, please raise it on the [Octave Discourse](https://octave.discourse.group/) or [bug tracker](https://savannah.gnu.org/bugs/?group=octave).
