### ISSUE TITLE
octave symbolic unique

### ISSUE THREAD

**Issue by Micky71** [cbm755/octsympy#1047]
syms a;

unique([a,a])  works fine, but

unique([a])

leads to the following error:
error: Python exception: UnboundLocalError: local variable ‘s’ referenced before assignment
occurred at line 1 of the Python code block:
return sp.Matrix([list(uniq(*ins))]),
error: called from
pycall_sympy_ at line 178 column 7
unique at line 55 column 5

**Comment by mtmiller** [comment]
Yes, confirmed. This is probably easy to fix for a new contributor.
