### ISSUE TITLE
CI: enable pythonic tests

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1067]
This should be straightforward:
  - look at the legacy `.travis.yml`
  - look at the gnuoctave docker-based jobs in the `main.yml` file.
  - make a new job for ~~doctests~~ *pythonic* (*updated*)

**Comment by cbm755** [comment]
@alexvong1995 this looks up your alley, and is prereq for #1072.

**Comment by alexvong1995** [comment]
Do you mean creating an extra `doctests` job in `main.yml` or merging stuff in `.travis.yml` into the existing `doctests` job in `main.yml`? We've already got a `doctests` job in `main.yml`.

**Comment by cbm755** [comment]
I think `main.yml` does not run anything with **Pythonic** .  The old `.travis.yml` had some runs that used `Pythonic`.

I suspect they could/should be a separate job in the main.yml.

**Comment by cbm755** [comment]
See around here, where `pythonic` is installed.

https://github.com/cbm755/octsympy/blob/f9ce230a20115820f19ef67c458f6f69163ae959/.travis.yml#L63

I'm not sure which Octave versions and SymPy versions we want to target.  But I guess anyone using Pythonic is going to be on the bleeding edge: so maybe just Octave 7.1 and SymPy 1.10.1 is sufficient (?)

**Comment by alexvong1995** [comment]
@cbm755 @chrisjohgorman After some debugging, I discover that pythonic does not work with python 3.10 due to this bug https://gitlab.com/mtmiller/octave-pythonic/-/issues/95

I get the following error:
```
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
error: subsref: cannot index Python object, not sequence or callable
error: called from
    subsref at line 52 column 9
    subsref at line 57 column 7
```

**Comment by chrisjohgorman** [comment]
I also ran into this problem and have a fix for it in my octave-pythonic in
the changes-octave-pythonic branch.  ( git clone -b changes-octave-pythonic
https://gitlab.com/chrisjohgorman/octave-pythonic/ )  I still have yet to
make a merge request for this.  I will try to make one later on today.

Chris

**Comment by alexvong1995** [comment]
I manage to workaround the issue by replacing all occurences of `py.collections.Callable` to `py.collections.abc.Callable` and `py.collections.Sequence` to `py.collections.abc.Sequence` (this trick was mentioned in the bug report https://gitlab.com/mtmiller/octave-pythonic/-/issues/95). But I run into another issue of octsympy not using pythonic during test. I'm trying to debug it now.

**Comment by alexvong1995** [comment]
> I also ran into this problem and have a fix for it in my octave-pythonic in the changes-octave-pythonic branch. ( git clone -b changes-octave-pythonic https://gitlab.com/chrisjohgorman/octave-pythonic/ ) I still have yet to make a merge request for this. I will try to make one later on today. Chris

Thanks! It would be great to have a more permanent fix for the issue. Right now, I'm using a workaround.

**Comment by cbm755** [comment]
For the CI runs, we can also run on an earlier Python...  (although obviously we eventually need 3.10 support)

**Comment by alexvong1995** [comment]
I finally succeed in getting pythonic doctests (Octave 7.1.0, SymPy 1.10.1, mpmath 1.1)  to run. Basically, all but 8 tests passed.
```
Summary:
   FAIL    8/1086
371/376 targets passed, 30 without tests.
```

**Comment by cbm755** [comment]
Great!  How much of the regular test suite passes?  `octsympy_tests`.

**Comment by alexvong1995** [comment]
For the regular test suite, 6 tests failed.
```
Summary:
  PASS                             2396
  FAIL                                6
  XFAIL (expected failure)           28
```

**Comment by alexvong1995** [comment]
It appears that those 8 doctests failed due to a single reason. The error msg looks similar to that in #1053. Should we mark them as `xtest`, as in #1089?

```
   >> syms m n positive integer
    B = sym('B', [m n])
      expected:    B = (sym) B  (m×n matrix expression)
      got     : ??? NameError: name 'Str' is not defined
```

```
   >> syms n
    A = sym('A', [n n])
      expected:    A = (sym) A  (n×n matrix expression)
      got     : ??? NameError: name 'Str' is not defined
   >> B = 3*A
      expected:    B = (sym) 3⋅A  (n×n matrix expression)
      got     : ??? NameError: name 'Str' is not defined
   >> A = sym('A', [0, n])
      expected:    A = (sym) A  (empty 0×n matrix expression)
      got     : ??? NameError: name 'Str' is not defined
   >> B = 3*A
      expected:    B = (sym) 3⋅A  (empty 0×n matrix expression)
      got     : ??? NameError: name 'Str' is not defined
```

```
   >> syms n m integer
    A = sym('a', [n m])
      expected:    A = (sym) a  (n×m matrix expression)
      got     : ??? NameError: name 'Str' is not defined
```

```
   >> syms m n positive integer
    B = sym('B', [m n])
      expected:    B = (sym) B  (m×n matrix expression)
      got     : ??? NameError: name 'Str' is not defined
```

```
   >> syms n m integer
    A = sym('A', [n m]);
    B = sym('B', [n m]);
    A.*B
      expected:    ans = (sym) A∘B
      got     : ??? NameError: name 'Str' is not defined
```

**Comment by alexvong1995** [comment]
For the regular test suite, 4 failed due to

```
NameError: name 'Str' is not defined
```

2 failed due to

```
assert (isequal (a, b)) failed
```

**Comment by alexvong1995** [comment]
The underlying issue causing the `assert (isequal (a, b)) failed` test failure is now found. Basically, it boils down to `store_vars_in_python` not handling the 0x0 matrix correctly. It took me hours to track down the bug, but the fix is only 2 lines...

As a result, all test failures are now caused by a single issue: `NameError: name 'Str' is not defined`
