### ISSUE TITLE
support for existing Octave installs if we depend on new python packages

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1083]
If we depend on `packaging` like in #1061 then we have a new dependency.

* we can ask the maintainers of gnuoctave/octave container images to add this package their images
    - do they still make changes to 5.1.0? (our minimum supported version)
* think/investigate the Windows Octave install (which I think ships a bundled Python, at least partially because of us)

The other option here is to prefer `packaging.version` going forward but ship our own probably-inferior version of `Version` in the meantime.  I *think* we use this package to control when tests are expected to pass on which versions of SymPy so likely we only really need to support SymPy's versioning schemes.

CC @chrisjohgorman as they are thinking about these things too.

**Comment by cbm755** [comment]
Proposal: for 3.0.0, we ship our own implementation if `packaging` is not installed

**Comment by chrisjohgorman** [comment]
The proposal is a reasonable one, but I don't know much about what
needs to be done to octsympy and octave to include packaging.  I
thought it was a simple fix of a couple of lines, not realizing that
it would mean for windows users who don't have a python installed by
default.  (Or even that packaging was not part of the default python
install.)

I have some details that may be useful, distutils is deprecated, but
still works.  It is slated for removal in python 3.12, so if we can
accept a warning from python in version 3.10+ there would be no reason
to change to packaging.

Other than the fix to the try_stuff job in .github/workflows/main.yml,
what needs to be done to get packaging working for 3.0.0?  When is
3.0.0 scheduled for release?

**Comment by cbm755** [comment]
3.0.0 will be a while, will try to mark some various issues with that milestone.

How about this for now, in sudo code:


```
try:
    import packaging...
except ImportError:
    import distutils....
```

That we we are future-proof and will still work on existing systems...?

**Comment by chrisjohgorman** [comment]
Sorry for the delay in replying, I wanted to test out the Workflow run on
github.  Your suggestion is a good one.  Not only does it work, it fixes
the problem I was having with the try_stuff job failing.  I now have a
clean workflow.  I will now try to give you a pull request.  (I have a lot
of commits as I committed and reverted trying to get try_stuff working.)

**Comment by cbm755** [comment]
I think this is good enough: the only case that requires `packaging.version` is Python >= 3.12 and old SymPy, an unlikely combination.
