### ISSUE TITLE
doctest: update Catalan printing for SymPy 1.10

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1093]
In sympy 1.10.1, doctests are failing because of changes to how Catalan pretty prints.

- `pip install sympy==1.10.1`
- `pkg install -forge doctest`
- `pkg load doctest`
- `doctest catalan`, maybe other places too.

**Comment by cbm755** [comment]
@chrisjohgorman next time put:

`Fixes #1093` somewhere in the BODY (3rd line onward, not first line) of your git commit message and this would close automatically when #1097 was merged.

No big deal, I'm closing it manually now.

**Comment by chrisjohgorman** [comment]
Thanks, will do.
