### ISSUE TITLE
times: elementwise multiplication broken on SymPy 1.9

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1109]
Consider
```
 syms x
 A = [1 x];
 B = [2 3];
 A .* B
```
On SymPy 1.9, I get:
```
Python exception: AssertionError
    occurred at line 6 of the Python code block:
    return x.multiply_elementwise(y)
```
Looks like an upstream issue but its fixed in the later SymPy 1.10.x.  Should bisect and ensure upstream has a unit test for this...

If so (rather than our fault), maybe we want to implement a blocklist or at leat a warnlist on "known bad" SymPy versions.  E.g., in `sympref diagnose`.

**Comment by chrisjohgorman** [comment]
A git bisect leaves `[67b59a8f591180fb1e5ecd02e793b929541327e1] multiply_elementwise error fixed` as the commit which fixes the issue.  Looking at the commit, I don't see a unit test added.  Of course it's possible to have added the unit test in a different commit.  Where would I go to add the unit test?
```
diff --git a/sympy/matrices/repmatrix.py b/sympy/matrices/repmatrix.py
index 2f0cdcd6ca..84cde91b1e 100644
--- a/sympy/matrices/repmatrix.py
+++ b/sympy/matrices/repmatrix.py
@@ -239,8 +239,9 @@ def _eval_matrix_mul(self, other):
         return classof(self, other)._fromrep(self._rep * other._rep)
 
     def _eval_matrix_mul_elementwise(self, other):
-        rep = self._rep.mul_elementwise(other._rep)
-        return classof(self, other)._fromrep(rep)
+        selfrep, otherrep = self._rep.unify(other._rep)
+        newrep = selfrep.mul_elementwise(otherrep)
+        return classof(self, other)._fromrep(newrep)
 
     def _eval_scalar_mul(self, other):
         rep, other = self._unify_element_sympy(self._rep, other)
```

**Comment by chrisjohgorman** [comment]
I looked around at sympy and found that pull request from the author also included a commit to the sympy/matrices/tests/test_commonmatrix.py.  It mentions the issue #22353.  I decided to run this test case, by hand in sympy-1.9 where it fails.  It now runs properly in 1.10.

**Comment by cbm755** [comment]
Anything we should do here for 3.0.0?  We could have a `known_bad` list of SymPy versions, maintained in `sympref` and checked similar to how we check the minimum sympy version...  Or just ignore it?

**Comment by alexvong1995** [comment]
Actually, for this particular issue, we can workaround it by using `hadamard_product(x, y)` instead of `x.multiply_elementwise(y)` for sympy 1.9 because the bug for `hadamard_product` https://github.com/sympy/sympy/issues/8557 has been fixed since Mar 2020 (sympy 1.9 was released on Oct 2021).

**Comment by cbm755** [comment]
So could we keep using hadamard_product when SymPy >= 1.9?  That sounds like a nice fix to me!

**Comment by alexvong1995** [comment]
Yes, `hadamard_product` works fine and passes all tests in sympy 1.9. Should we use `hadamard_product` instead of `multiply_elementwise` in sympy >1.9 as well?

**Comment by cbm755** [comment]
Sure, try it?  If tests pass, it should be good.  Semantically correct is good!
