### ISSUE TITLE
sym/ztrans references non-implemented function

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1122]
For 3.0.0, we could either comment out the `@seealso` line.

Of course it should be added back if `iztrans` is added.

**Comment by cbm755** [comment]
@alexvong1995 shall we just comment out the `@seealso` for 3.0.0?

**Comment by alexvong1995** [comment]
Yes, I think we can add `iztrans` later.

I (mostly) have an implementation of `iztrans`, but I'm not sure if I handle the case where it's not possible to find the inverse transform correctly. Currently, it returns an unevaluated limit of an unevaluated integral (using the definition of course, but there're multiple ways to rewrite the definition into something sympy can represent...) when the inverse transform cannot be found.
