### ISSUE TITLE
Regression caused by cd263b3853482226dbffe99486ff98c8445d6a63

### ISSUE THREAD

**Issue by alexvong1995** [cbm755/octsympy#1151]
I realize cd263b3853482226dbffe99486ff98c8445d6a63 causes a regression because in the following code:

```
     elseif (isequal (x, []))
      var_pyobj.append (py.list ());
```

If `x` is `''`, we have `isequal ('', [])` being evaluated to true which is not what we want.

See also the discussion in #1136.

**Comment by cbm755** [comment]
Is there a particular thing that fails b/c of this?  Something like `a = pycall_sympy__('return _ins[0]', "")`?   Or `sym('')`?

Must be something missing from the test suite anyway: so when we fix this we should add something to the BIST.

**Comment by alexvong1995** [comment]
Due to this bug,

```pycall_sympy__ ('sys.stderr.write(repr(_ins[0]) + "\n")', '');```

prints `[]` rather than `''`.

Basically, the empty string turns into the empty list in Python, which is incorrect and different from the old behaviour.
