### ISSUE TITLE
add maintainers

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1178]
@alexvong1995 I'd like to list you as a maintainer.  If that is ok, I suggest you:

  * go here: https://github.com/gnu-octave/packages/
  * and edit the `symbolic.yaml`

No need to put an email address: leaving it blank links to https://octave.discourse.group

Or let me know if you prefer I do this.

**Comment by cbm755** [comment]
@mtmiller I took the liberty of adding you without asking as you've been defacto maintainer for couple years.  But of course you can remove your name or ask me to if you prefer.

**Comment by alexvong1995** [comment]
I'm glad to be a co-maintainer. In the past, I have trouble acting as a (sole) maintainer because of time / personal circumstances. But I've no problem replying to user enquires / resolving issues occasionally.
