### ISSUE TITLE
port our python executable detection to upstream octave and use it here

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1188]
Upstream Octave has a `python` command which is basically like `system` except calls Python.  Its currently hardcoded to `python`, and would therefore benefit form what we do:

  * use `python3` on unix and `python` on Windows
  * respect the $PYTHON env var.

Upstream issue: https://savannah.gnu.org/bugs/index.php?62733

Thread: https://octave.discourse.group/t/configure-test-for-python-can-fail-but-with-little-apparent-harm/2978/7

- - - -

If we move that code upstream, we could eventually drop it here.

**Comment by alexvong1995** [comment]
https://savannah.gnu.org/bugs/index.php?62733 has been fixed in https://hg.savannah.gnu.org/hgweb/octave/rev/6cfc7af8eacc
