### ISSUE TITLE
adopt .oct-config files to indicate source in is utf-8

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1191]
There are new-ish .oct-config files with this content:
```
encoding=utf-8
```
These are used to indicate that the source code is in utf-8.  Which ours is.

note: we also use have this texinfo: `@documentencoding UTF-8` in-place but I'm not sure that is used by Octave's `__mfile_encoding` / `dir_encoding` etc.  *both*, we want *both*.

#### References:
* https://github.com/catch22/octave-doctest/pull/252
* https://github.com/catch22/octave-doctest/issues/251
* https://octave.discourse.group/t/should-i-use-oct-config-when-i-have-utf-8-strings-in-m-files/3001

**Comment by cbm755** [comment]
I'm getting failures in Octave 6.4.0 about this when `LANG=C` (in Fedora 35/36 package builds for example).

A workaround is to do this
```
__mfile_encoding__("utf-8")
```
before running doctests.

**Comment by mmuetzel** [comment]
Afaict, those files have been added to the repository. Is there anything left to do for this?

**Comment by cbm755** [comment]
I don't think Symbolic has such files yet.  We added them to the Doctest package.

My current understanding packages that have utf-8-encoded source files (like we do) shoulddeclare that so that Octave will DTRT when the system is set to something else.

Actually, it is already declared in most files like this:
```
%% -*- texinfo -*-
%% @documentencoding UTF-8
```
but I don't think Octave considers that; rather it is an indicator for texinfo tooling.

**Comment by mmuetzel** [comment]
Oops. Sorry. Got confused as to which repository this was meant for. Sorry for the noise.
