### ISSUE TITLE
post-release bumps

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1204]
@alexvong1995 see here:

https://sourceforge.net/p/octave/package-releases/486/

1. Please post the yaml update
2. bump the versions post-release as per HOWTO-release.md document
3. close 3.0.1 milestone
4. create milestone for 3.0.2, if not already existing.

**Comment by cbm755** [comment]
by "post-release bumps" I meant something like 6acbe24d07d188b7d047af7d5ebb3fb5167e2936

**Comment by alexvong1995** [comment]
* [X] Update the https://gnu-octave.github.io/packages/ yaml file

      - [X] see https://github.com/gnu-octave/packages/blob/main/CONTRIBUTING.md

      - [X] send pull request (NOTE: see PR https://github.com/gnu-octave/packages/pull/154)


AFTER release
=============

  * [X] Bump version by appending "+" in sympref.m and DESCRIPTION. (NOTE: see PR #1205)

  * Optionally, update the make_windows_bundle script.  DEPRECATED.

---

1. [X] close 3.0.1 milestone (NOTE: already closed)
2. [X] create milestone for 3.0.2, if not already existing. (NOTE: already existing)

**Comment by alexvong1995** [comment]
PR https://github.com/gnu-octave/packages/pull/154 merged in https://github.com/gnu-octave/packages/commit/04ea6104776f10bce80a6311f3bdbdf8a4edab7f and PR #1205 merged in 1252eec1d43ffc2f0fc0d0d731e18718781f2498
