### ISSUE TITLE
pythonic: add `dbout` command

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1210]
@alexvong1995 pointed out that dbout does not work on pythonic backend.

Possibly its just `print`?   Anyway, needs to be added to `python-header` or equivalent.

**Comment by alexvong1995** [comment]
I think using `logging.debug` is a more common way to do it. (We can add a FIXME comment if we don't want to change it now.)

WDYT?

**Comment by cbm755** [comment]
Background: my debugging style is just `print`.  But you cannot use `print` in popen2 ipc mechanism (b/c the stdout is used for the communication).  So I made `dbout`.  (In those days I did not know about logging module.)

In my experience in other projects, `logging` needs some config boilerplate.

I'd suggest just porting `dbout` to pythonic, at least in the *short term*.  But if then both dbout's can be can be replaced with logging, I'd be happily test a MR for that, later.
