### ISSUE TITLE
common helper python function for Array/Matrix return

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1211]
@alexvong1995, after our discussion, I think you are right: we should have some shared code for this Array versus Matrix stuff:

```
if all(isinstance(elt, Expr)'
          '           for elt in itertools.chain.from_iterable(MM))):'
          '    M = Matrix(MM)'
          'else:'
          '    M = Array(MM)'
```

I think a helper python function in python_header is a good way to do this.

**Comment by alexvong1995** [comment]
Fixed in b618e5fdd0bb1080d913d965ed4040e6f1f6bb6a
