### ISSUE TITLE
subs: needs to use  make_matrix_or_array

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#1226]
MWE, from `test @sym/and`:

```
syms x
e = (x == 3) & (x^2 == 9);
subs(e, x, [-3 0 3])
sympy(ans)
ans = MutableDenseMatrix([[false, false, true]])
```

Here `e` is a scalar but `subs` "broadcasts" to the size of `[-3 0 3]`.

I guess the implementation needs to do a list-of-lists thing and then call `make_matrix_or_array`.

Blocks #1124.

**Comment by alexvong1995** [comment]
Fixed by #1227
