### ISSUE TITLE
Using symengine instead of SymPy

### ISSUE THREAD

**Issue by SylvainCorlay** [cbm755/octsympy#1242]
Did you consider using the C++ [SymEngine](https://github.com/symengine/symengine) library instead of SymPy (by the same authors).

This would make it possible to directly link with Symengine rather than requiring a Python runtime.

**Comment by cbm755** [comment]
Its a good idea.  I think I started this before SymEngine.  

But does SymEngine have all the features we need?  I've never looked carefully at it.

**Comment by SylvainCorlay** [comment]
> Just for transparency towards you, however, I have to say that the plotly integration is quite incomplete, as it works mainly for the basic plots, and still has limitations even in the basic examples...

@certik may be able to give a complete answer to that!

**Comment by certik** [comment]
SymEngine has basic symbolic manipulation features, but does not yet have more advanced symbolic algorithms like limits, integration etc. The advantage is that it is very fast and pure C++, no Python dependency.

**Comment by cbm755** [comment]
Wrong thread maybe?  completeness of `plotly` interface is not relevant to Octave Symbolic pkg as far as I know.

But nonetheless, @certik 's answer is useful to me :-)   We definitely want "limits, integration, etc" in Octave Symbolic so I suspect its not worth moving: as we'd be moving to a hybrid approach, with both C++ and SymPy.  Maybe that's worth it in the future but I don't think so at the moment.

**Comment by certik** [comment]
However, if anyone is interested in helping out with SymEngine, I am definitely interested in eventually implementing all the advanced algorithms. If so, please contact me!
