### ISSUE TITLE
Test failure with octave 8.1.0

### ISSUE THREAD

**Issue by opoplawski** [cbm755/octsympy#1249]
I'm seeing the following test failure with octave-symbolic 3.0.1, sympy 1.11.1, and octave 8.1.0:
```
finiteset.m ............................................ FAIL    1/12  

   >> S(2)

      expected:    ??? ind2sub: index out of range

      got     : Python exception: IndexError: Index out of range: a[1]
    occurred at line 7 of the Python code block:
    M[i][0] = A[rr[i],cc[i]]

```
I think it is new with octave 8.1 (from 7.3).

**Comment by cbm755** [comment]
Yes is fixed in `main`, shall I do a new release for Fedora's sake?

**Comment by cbm755** [comment]
Oh sorry I hadn't merged it yet: is https://github.com/cbm755/octsympy/pull/1248

**Comment by opoplawski** [comment]
Since that doesn't apply cleanly to 3.0.1, a new release would be appreciated.  Thanks.

**Comment by cbm755** [comment]
Can do, will take another look that the upcoming SymPy 0.12 doesn't break anything other than Bernoulli (#1217).

There is also a new `mpmath` release I think...
