### ISSUE TITLE
Forget to update tarball filename in v3.1.1 release (?)

### ISSUE THREAD

**Issue by alexvong243f** [cbm755/octsympy#1253]
In https://github.com/cbm755/octsympy/releases/tag/v3.1.1 we have ```Octave package: symbolic-3.0.1.tar.gz```. Shouldn't it be `symbolic-3.1.1.tar.gz`? Also, the tarball `symbolic-3.1.1.tar.gz` seems to be missing from `Assets`.

Are they being forgotten or is this still WIP?

**Comment by cbm755** [comment]
Forgotten!  Thanks Alex
