### ISSUE TITLE
moving double arrays between Octave and Python

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#134]
@huizhonglu said:

> Another question, it seems that sympy can use double as matlab (with subs). Is
> it possible to impement directly double/float subs in octsympy ? For complicate
> symbolic computation, reducing number of symbolic variables may improve a lot
> the performance.

**Comment by latot** [comment]
i only want to say, python actually brings by default with pip in windows, so install dependencies should be more easy now.

**Comment by cbm755** [comment]
pretty sure vpa bit is done too, at least `vpa([1 2.1 3.1])` works.
