### ISSUE TITLE
Add more set operators: union, intersection etc

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#147]
I've added setxor and setdiff in commit 6e1f02f7806189189e31132a9614f3790b532b1e.

It would be great to do other set operations.  This should be an easy fix for someone wanting to get involved.

I think we need: `union, intersect, unique, ismember`

Implement one (mostly copy-paste I hope) and submit a pull request.

**Comment by latot** [comment]
can we add others functions like interval?

**Comment by latot** [comment]
last comment to other issue
