### ISSUE TITLE
Why do I need to use subsref within @sym/myfcn.m?

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#17]
I've overloading subrefs() and it works fine.  But within _my own_ @sym/ directory, I have to manually use subrefs() like this:

```
x(i)   % <-- gives error
% so workaround:
idx.type = '()';
idx.subs = {j};
subsref(x, idx);
```

The error is:

```
error: myfcn.m: A(I): index out of bounds; value 2 out of bound 1
error: called from:
```

It's calling the superclass subsref (I think).  Which in my case, will report [1 1] or something wrong for my array.

FWIW, same thing in Matlab 2008:

```
??? Index exceeds matrix dimensions.
```

**Comment by latot** [comment]
mm, here a related thing from sym2poly:
```
  c = sym([]);
  for j = 1:numel(c2)
    % Bug #17
    %c(j) = c2{j};
    idx.type = '()'; idx.subs = {j};
    c = subsasgn(c, idx, c2{j});
  end
```
we still can't do:
```
  c = sym([]);
  for j = 1:numel(c2)
    c(j) = c2{j};
  end
```
because only return the first value....
i remember some days ago i was having problems with this, assigning values and only get the first.

**Comment by cbm755** [comment]
Its a "feature": you can't use indexing within the class itself
