### ISSUE TITLE
Assigning a function to a function fails if the second function's argument is missing in the symbolic expression

### ISSUE THREAD

**Issue by rocketsound** [cbm755/octsympy#189]
The following code

    syms t
    x(t) = t;
    y(t) = x;

results in the error

    error: assignment failed, or no method for '<unknown type> = class'

Note that

    y(t) = x(t);

works fine, but for the sake of MATLAB compatibility both expressions should work.

**Comment by cbm755** [comment]
Good catch!  I'm not likely to look a this for a week or so.  Would you like to help?  Some ideas:

1.  Preparing an "xtest", perhaps at end of `@symfun/subsasgn.m` of this issue.  Submit this as a pull request here on github.

2.  Debug, maybe with disp() to see if you can track this down to `@symfun/subsasgn.m` or `@sym/subsasgn.m` (or somewhere else).

Thanks for the report!

**Comment by cbm755** [comment]
I assume `y = x` works and gives a symfun but either way, that should be tested for as well.

**Comment by rocketsound** [comment]
`y = symfun(x, t);` also fails

**Comment by cbm755** [comment]
no problem, filing bugs is great.  Especially when they have nice minimal nonworking examples, as you've done here.

However, if you want to try, hacking on this is pretty easy!  And experience with git is great thing for students to put on their CVs!  (My suggestion 1. above should be pretty straightforward).
