### ISSUE TITLE
implement rows/columns/ismatrix

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#193]

**Comment by cbm755** [comment]
Fixed in 1b7f5166385f4d52bf8e273e5448b8 and 8707437762431e3254430e759ffaf58aa.

**Comment by latot** [comment]
Hi, do you mean all sym are matrix?

```
 +function b = ismatrix(x)
 +
 +  b = true;
 +
 +end
```

**Comment by cbm755** [comment]
Yes.  I think this is consistent with `help ismatrix` for doubles...
