### ISSUE TITLE
Octave-Forge pkg symbolic fails on windows w/o bin folder

### ISSUE THREAD

**Issue by vassbu** [cbm755/octsympy#229]
Hi, I am trying to get the OctSymPy package working with GNU Octave 4.0.0-rc3 with Python 2.7.9. The Symbolic-2.1.0 package seems to be installed OK, but the first command, eg. syms x, give error messages: Initializing communication with SymPy using a popen2() pipe.
Detected a Windows system: using "mydbpy.bat" to workaround Octave bug
popen2: process creation failed
error: called from
    python_ipc_popen2 at line 52 column 19
    python_ipc_driver at line 30 column 13
    python_cmd at line 120 column 9
    sym at line 279 column 5
    syms at line 157 column 9
error: evaluating argument list element number 3
error: called from
    syms at line 157 column 9
    
Any clues?

**Comment by cbm755** [comment]
Thanks for testing: I cannot test the Octave 4.0 rc's myself on windows, and you're the second person who pointed this out.

1. Do you have SymPy installed and working?

2. Are you installing from Octave-Forge?  You could try the "bundle" packages from https://github.com/cbm755/octsympy/releases.

3. Did you have it working with Octave 3.8.2?

**Comment by vassbu** [comment]
Hi Colin,
Good News!,
I tried once more to install the Symbolic pkg  'by the book' with Win8/Octave 4.0 rc3 and took the time to wait for a warning message to finish (instead of breaking with Ctrl-C). Then I got the magic 'OctSymPy: Communication established.  SymPy v0.7.6.' after a long while!
Here is how I did it on Win8/Octave 4.0.0-rc3:
1) Installed the bundle:
------------
>> pkg install symbolic-win-py-bundle-2.1.0.zip
For information about changes from previous versions of the symbolic package, run 'news symbolic'.
(Took a few secs.)
------------

2) Loaded Synbolic:
------------
>> pkg load symbolic
(Took fraction of sec.)
------------

3) Tried to make a symbolic variable:
------------
>> syms x
OctSymPy v2.1.0: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Detected a Windows system: using "mydbpy.bat" to workaround Octave bug
Some output from the Python subprocess (pid 4368) might appear next.
warning: fopen: 'C:\Octave\Octave-4.0.0-rc3\share\octave\packages\symbolic-2.1.0\private/python_header.py' found by searching
load path
warning: called from
    fileread at line 35 column 7
    python_header at line 26 column 16
    python_ipc_popen2 at line 67 column 13
    python_ipc_driver at line 30 column 13
    python_cmd at line 120 column 9
    sym at line 279 column 5
    syms at line 157 column 9
*********** Long pause ***********
OctSymPy: Communication established.  SymPy v0.7.6.
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
------------

4) New try after a while:
-----------
>> syms x n
>> f = exp(-x^2)
f = (sym)

     2
   -x
  e

>> F = fourier(f, x, n)
Waiting......
F = (sym)

             2  2
    ____  -pi *n
  \/ pi *e
-------------

So, it was the *********** Long pause *********** that tricked me to conclude that it did not work!
Now I will try to play with the Symbolic pkg - looks promising!
Regards
Tore Gaupseth


------ Original Melding ------
Fra: "Colin Macdonald" <notifications@github.com<mailto:notifications@github.com>>
Til: "cbm755/octsympy" <octsympy@noreply.github.com<mailto:octsympy@noreply.github.com>>
Cc: "Gaupseth Tore" <Tore.Gaupseth@hin.no<mailto:Tore.Gaupseth@hin.no>>
Sendt: 16.04.2015 01:28:02
Emne: Re: [octsympy] Wish I could get Symbolic-2.1.0 to work in Win8 (#229)


Thanks for testing: I cannot test the Octave 4.0 rc's myself on windows, and you're the second person who pointed this out.

  1.  Do you have SymPy installed and working?

  2.  Are you installing from Octave-Forge? You could try the "bundle" packages from https://github.com/cbm755/octsympy/releases.

  3.  Did you have it working with Octave 3.8.2?

**Comment by cbm755** [comment]
On 16/04/15 06:05, vassbu wrote:
> warning: fopen: 'C:\Octave\Octave-4.0.0-rc3\share\octave\packages\symbolic-2.1.0\private/python_header.py' found by searching
> load path
> warning: called from
>      fileread at line 35 column 7
>      python_header at line 26 column 16
>      python_ipc_popen2 at line 67 column 13
>      python_ipc_driver at line 30 column 13
>      python_cmd at line 120 column 9
>      sym at line 279 column 5
>      syms at line 157 column 9

This particular warning is fixed in master and will be in 2.1.1.

**Comment by cbm755** [comment]
> install the Symbolic pkg 'by the book' with Win8/Octave 4.0 rc3

Ok, so it works if you use the bundle.  That is good.

But am I right that it doesn't work with "pkg install -forge symbolic"?  (assuming you have SymPy and Python deps in place).  Are you able to test this?

**Comment by vassbu** [comment]
Will try, hang on...

**Comment by vassbu** [comment]
Installed Python 2.7.9 and Sympy on another Win 8 PC. Sympy tested OK in Python console.
Installed Octave 4.0.0-rc3 and then pkginstall -forge symbolic, no error messaes.
Tried >> syms x
OctSymPy v2.1.0: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Detected a Windows system: using "mydbpy.bat" to workaround Octave bug
error: popen2: process creation failed
error: called from
    python_ipc_popen2 at line 52 column 19
    python_ipc_driver at line 30 column 13
    python_cmd at line 120 column 9
    sym at line 279 column 5
    syms at line 157 column 9
error: evaluating argument list element number 3
error: called from
    syms at line 157 column 9
>>
*** The call terminated ***
Then I noticed that the bin directory of the symbolic package files was not installed by 'pkginstall -forge symbolic' - and copied the bin directory from my other PC. Tried once more and now it works,
>> syms x
OctSymPy v2.1.0: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Detected a Windows system: using "mydbpy.bat" to workaround Octave bug
Some output from the Python subprocess (pid 3740) might appear next.
warning: fopen: 'C:\Octave\Octave-4.0.0-rc3\share\octave\packages\symbolic-2.1.0\private/python_heade
r.py' found by searching load path
warning: called from
    fileread at line 35 column 7
    python_header at line 26 column 16
    python_ipc_popen2 at line 67 column 13
    python_ipc_driver at line 30 column 13
    python_cmd at line 120 column 9
    sym at line 279 column 5
    syms at line 157 column 9

OctSymPy: Communication established.  SymPy v0.7.6.
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
>>
_Vassbu

------ Original Melding ------
Fra: "Colin Macdonald" <notifications@github.com<mailto:notifications@github.com>>
Til: "cbm755/octsympy" <octsympy@noreply.github.com<mailto:octsympy@noreply.github.com>>
Cc: "Gaupseth Tore" <Tore.Gaupseth@hin.no<mailto:Tore.Gaupseth@hin.no>>
Sendt: 16.04.2015 11:06:24
Emne: Re: [octsympy] Wish I could get Symbolic-2.1.0 to work in Win8 (#229)


install the Symbolic pkg 'by the book' with Win8/Octave 4.0 rc3

Ok, so it works if you use the bundle. That is good.

But am I right that it doesn't work with "pkg install -forge symbolic"? (assuming you have SymPy and Python deps in place). Are you able to test this?

**Comment by cbm755** [comment]
> Then I noticed that the bin directory of the symbolic package files
> was not installed by 'pkginstall -forge symbolic' - and copied the
> bin directory from my other PC. Tried once more and now it works,

Fantastic!  We can try to get that fixed!  Great catch.

Are you familiar with Octave packaging?  If you want to try to fix this
that would be great...  Otherwise, I'll try when I get a chance.  Let me
know.

Can you rename the bug to "Octave-Forge pkg fails on windows w/o bin 
folder" or similar?

Thanks

**Comment by vassbu** [comment]
Since I am a stranger in those package woods, I think it is best done by you.
Btw, I did a Win7 buggy install just as I did on Win8. The bin folder fixed it.
_Vassbu

________________________________
Fra: Colin Macdonald [notifications@github.com]
Sendt: 16. april 2015 13:13
Til: cbm755/octsympy
Kopi: Gaupseth Tore
Emne: Re: [octsympy] Wish I could get Symbolic-2.1.0 to work in Win8 (#229)

> Then I noticed that the bin directory of the symbolic package files
> was not installed by 'pkginstall -forge symbolic' - and copied the
> bin directory from my other PC. Tried once more and now it works,

Fantastic! We can try to get that fixed! Great catch.

Are you familiar with Octave packaging? If you want to try to fix this
that would be great... Otherwise, I'll try when I get a chance. Let me
know.

Can you rename the bug to "Octave-Forge pkg fails on windows w/o bin
folder" or similar?

Thanks

**Comment by cbm755** [comment]
Could you check if both of these packages work?

needs Python, SymPy installed:
  http://people.maths.ox.ac.uk/macdonald/temp/symbolic-2.1.1.dev.zip

Bundle:
  http://people.maths.ox.ac.uk/macdonald/temp/symbolic-win-py-bundle-2.1.1.dev.zip

If those work, I will make a new release.

**Comment by cbm755** [comment]
How would you like your name written for the release notes?  E.g., 49e175fed67c84eb584

**Comment by vassbu** [comment]
Hi,
1) the symbolic-2.1.1.dev.zip works OK, with one remark: the first pkg install symbolic-2.1.1.dev.zip run complained that Python could not be found - then after setting C:\Python27 in path it installed with some warnings, see below. I guess Python is not in path after default installation in Windows?
2) the bundle package installed with similar warnings as above, but after pkg load symbolic and >>syms x it failed, see errormessages below. THEN I noticed that the winwrapy.bat file was missing from the packages/../bin directory. So I copied in the one from the bin directory in the symbolic-2.1.1.dev.zip - and then it works!
This must be corrected.

**** from pkg install symbolic-2.1.1.dev.zip ***********
>> pkg install symbolic-2.1.1.dev.zip
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-R7FAOX:97: @result expected braces.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-R7FAOX:97: Misplaced {.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-R7FAOX:97: Misplaced }.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-R7FAOX:97: @result missing close brace.
warning: doc_cache_create: unusable help text found in file 'catalan'
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-noH3OM:97: @result expected braces.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-noH3OM:97: Misplaced {.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-noH3OM:97: Misplaced }.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-noH3OM:97: @result missing close brace.
warning: doc_cache_create: unusable help text found in file 'eulergamma'
For information about changes from previous versions of the symbolic package, run 'news symbolic'.
>>
>> syms x
OctSymPy v2.1.1.dev: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Detected Windows: using "winwrapy.bat" to workaround Octave bug #43036
Some output from the Python subprocess (pid 5004) might appear next.

OctSymPy: Communication established.  SymPy v0.7.6.
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
>>

********pkg install symbolic-win-py-bundle-2.1.1.dev.zip**********
>> pkg install symbolic-win-py-bundle-2.1.1.dev.zip
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-Nds3Z1:97: @result expected braces.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-Nds3Z1:97: Misplaced {.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-Nds3Z1:97: Misplaced }.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-Nds3Z1:97: @result missing close brace.
warning: doc_cache_create: unusable help text found in file 'catalan'
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-kELVfB:97: @result expected braces.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-kELVfB:97: Misplaced {.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-kELVfB:97: Misplaced }.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-kELVfB:97: @result missing close brace.
warning: doc_cache_create: unusable help text found in file 'eulergamma'
For information about changes from previous versions of the symbolic package, run 'news symbolic'.
>>
>> pkg load symbolic
>> syms x
error: 'python_ipc_popen2' undefined near line 30 column 15
error: called from
    python_ipc_driver at line 30 column 13
    python_cmd at line 120 column 9
    sym at line 279 column 5
    syms at line 157 column 9
error: evaluating argument list element number 3
error: called from
    syms at line 157 column 9
>>
[[winwrapy.bat copied to the ../bin folder corrected this]]

_Vassbu

________________________________
Fra: Colin Macdonald [notifications@github.com]
Sendt: 17. april 2015 14:22
Til: cbm755/octsympy
Kopi: Gaupseth Tore
Emne: Re: [octsympy] Octave-Forge pkg symbolic fails on windows w/o bin folder (#229)


Could you check if both of these packages work?

needs Python, SymPy installed:
http://people.maths.ox.ac.uk/macdonald/temp/symbolic-2.1.1.dev.zip

Bundle:
http://people.maths.ox.ac.uk/macdonald/temp/symbolic-win-py-bundle-2.1.1.dev.zip

If those work, I will make a new release.

**Comment by cbm755** [comment]
Thanks, I'll look into all that.

> 1) the symbolic-2.1.1.dev.zip works OK, with one remark: the first pkg install symbolic-2.1.1.dev.zip
> run complained that Python could not be found - then after setting C:\Python27 in path it installed
> with some warnings, see below. I guess Python is not in path after default installation in Windows?

No being a windows user since Win95, this is the bit hard for me...   Is there anything here we can fix or is "setting C:\Python27 in path" something you have to do in Windows settings?  Would you be able to document this on https://github.com/cbm755/octsympy/wiki/Notes-on-Windows-installation?

**Comment by cbm755** [comment]
Filed catalan thing as #232.

**Comment by cbm755** [comment]
I think I fixed "THEN I noticed that the winwrapy.bat file was missing".  Can you try:
  http://people.maths.ox.ac.uk/macdonald/temp/symbolic-win-py-bundle-2.1.1.dev-try2.zip

And follow up on #232 if you can.

thanks!

**Comment by vassbu** [comment]
Hi, again,
the bundle..dev-try2 works OK!

Octave version is 4.0.0-rc3 (on Win8 64 bit and also Win7)
Python 2.7.9
Sympy 0.7.6

I think the path issue on Windows systems is well documented in: https://docs.python.org/2/faq/windows.html?highlight=path
I will try to comment in https://github.com/cbm755/octsympy/wiki/Notes-on-Windows-installation .

>> help catalan
C:\Users\tg\AppData\Local\Temp\octave-help-OTdLSK:97: @result expected braces.
C:\Users\tg\AppData\Local\Temp\octave-help-OTdLSK:97: Misplaced {.
C:\Users\tg\AppData\Local\Temp\octave-help-OTdLSK:97: Misplaced }.
C:\Users\tg\AppData\Local\Temp\octave-help-OTdLSK:97: @result missing close brace.
warning: help: Texinfo formatting filter exited abnormally; raw Texinfo source of help text follows...

warning: called from
    help at line 116 column 7
'catalan' is a function from the file C:\Octave\Octave-4.0.0-rc3\share\octave\packages\symbolic-2.1.0\catalan.m

 -- Function File:  catalan ()
     Return Catalan constant.

          vpa (catalan ())
            (sym) 0.91596559417721901505460351493238
     See also: eulergamma.
   =>

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org<mailto:help@octave.org>
mailing list.
>>
_Vassbu

------ Original Melding ------
Fra: "Colin Macdonald" <notifications@github.com<mailto:notifications@github.com>>
Til: "cbm755/octsympy" <octsympy@noreply.github.com<mailto:octsympy@noreply.github.com>>
Cc: "Gaupseth Tore" <Tore.Gaupseth@hin.no<mailto:Tore.Gaupseth@hin.no>>
Sendt: 17.04.2015 17:29:21
Emne: Re: [octsympy] Octave-Forge pkg symbolic fails on windows w/o bin folder (#229)


I think I fixed "THEN I noticed that the winwrapy.bat file was missing". Can you try:
http://people.maths.ox.ac.uk/macdonald/temp/symbolic-win-py-bundle-2.1.1.dev-try2.zip

And follow up on #232<https://github.com/cbm755/octsympy/issues/232> if you can.

thanks!

**Comment by cbm755** [comment]
Excellent I'll close this.  Let me know about:

> How would you like your name written for the release notes? E.g., 49e175f

**Comment by vassbu** [comment]
Hi,
I'll test other versions later.
The name  vassbu  is ok.
vassbu

------ Original Melding ------
Fra: "Colin Macdonald" <notifications@github.com<mailto:notifications@github.com>>
Til: "cbm755/octsympy" <octsympy@noreply.github.com<mailto:octsympy@noreply.github.com>>
Cc: "Gaupseth Tore" <Tore.Gaupseth@hin.no<mailto:Tore.Gaupseth@hin.no>>
Sendt: 17.04.2015 19:19:47
Emne: Re: [octsympy] Octave-Forge pkg symbolic fails on windows w/o bin folder (#229)


Excellent I'll close this. Let me know about:

How would you like your name written for the release notes? E.g., 49e175f<https://github.com/cbm755/octsympy/commit/49e175fed67c84eb58426b4092b44ac73ef87131>

**Comment by vassbu** [comment]
Installs fine on Octave 3.8.2:

Installing Symbolic on Octave 3.8.2 MXE, Win7

0.
The Python runtime must be in path for this to work, see http://docs.python-guide.org/en/latest/starting/install/win/

1.
Installed Python and Sympy and tested OK.
>> pkg install symbolic-2.1.1.dev.zip
[[OK, with some warnings (catalan?), see below]]
>> pkg load symbolic
>> syms x
[[Works OK, see below]]

2.
Installed Symbolic with Py/SympPy bundled.
>> pkg install symbolic-win-py-bundle-2.1.1.dev-try2.zip
[[OK, with some warnings (catalan?), see below]]
>> pkg load symbolic
>> syms x
[[Works OK, see below]]

**********
>> pkg install symbolic-2.1.1.dev.zip
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-dk6ZNl:97: @result e
xpected braces.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-dk6ZNl:97: Misplaced
 {.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-dk6ZNl:97: Misplaced
 }.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-dk6ZNl:97: @result m
issing close brace.
warning: doc_cache_create: unusable help text found in file 'catalan'

C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-y6hTqm:97: @result e
xpected braces.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-y6hTqm:97: Misplaced
 {.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-y6hTqm:97: Misplaced
 }.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-y6hTqm:97: @result m
issing close brace.
warning: doc_cache_create: unusable help text found in file 'eulergam
ma'
For information about changes from previous versions of the symbolic
package, run 'news symbolic'.
>>

>> pkg load symbolic
>> syms x
OctSymPy v2.1.1.dev: this is free software without warranty, see sour
ce.
Initializing communication with SymPy using a popen2() pipe.
Detected Windows: using "winwrapy.bat" to workaround Octave bug #4303
6
Some output from the Python subprocess (pid 3772) might appear next.

OctSymPy: Communication established.  SymPy v0.7.6.
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Int
el)]
>>>> diff(1/x, x)
ans = (sym)

  -1
  ---
    2
   x

>>

*************
>> pkg install symbolic-win-py-bundle-2.1.1.dev-try2.zip
warning: creating installation directory C:\Octave\Octave-3.8.2\share
\octave\packages
warning: directory C:\Octave\Octave-3.8.2\share\octave\packages\symbo
lic-2.1.0 previously lost
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-uVVR6b:97: @result e
xpected braces.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-uVVR6b:97: Misplaced
 {.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-uVVR6b:97: Misplaced
 }.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-uVVR6b:97: @result m
issing close brace.
warning: doc_cache_create: unusable help text found in file 'catalan'

C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-c3VwRi:97: @result e
xpected braces.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-c3VwRi:97: Misplaced
 {.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-c3VwRi:97: Misplaced
 }.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-c3VwRi:97: @result m
issing close brace.
warning: doc_cache_create: unusable help text found in file 'eulergam
ma'
For information about changes from previous versions of the symbolic
package, run 'news symbolic'.
>>
>> pkg load symbolic
>> syms x
OctSymPy v2.1.1.dev: this is free software without warranty, see sour
ce.
Initializing communication with SymPy using a popen2() pipe.
Detected Windows: using "winwrapy.bat" to workaround Octave bug #4303
6
Some output from the Python subprocess (pid 3836) might appear next.

OctSymPy: Communication established.  SymPy v0.7.6.
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Int
el)]
>>
>> diff(sin(x)/x, x)
ans = (sym)

  cos(x)   sin(x)
  ------ - ------
    x         2
             x

>>

_vassbu

________________________________
Fra: Colin Macdonald [notifications@github.com]
Sendt: 17. april 2015 19:19
Til: cbm755/octsympy
Kopi: Gaupseth Tore
Emne: Re: [octsympy] Octave-Forge pkg symbolic fails on windows w/o bin folder (#229)


Closed #229<https://github.com/cbm755/octsympy/issues/229>.

**Comment by cbm755** [comment]
Thanks for your help!  I'll roll new release now with these fixes.

**Comment by jotaeri** [comment]
Uninstall Octave, mainly if you use 64bit in win10. Install Octave 32bits configuring compatibility for win7. Download the symbolic executable package at https://github.com/cbm755/octsympy/releases and then put it in the directory that appears in the Octave program. Open the Octave GUI and check the Directory. Then apply the type:
->pkg install symbolic-win-py-bundle-x.y.z.zip
->pkg load symbolic
->syms x

Good luck.

**Comment by cbm755** [comment]
@jotaeri I'm not sure if I understand.  Did you perhaps mean to edit the wiki?  Or are you reporting a new bug?
