### ISSUE TITLE
catalan, eulergamma braces issue?

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#232]
Fix this:
````
> pkg install symbolic-2.1.1.dev.zip
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-R7FAOX:97: @result expected braces.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-R7FAOX:97: Misplaced {.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-R7FAOX:97: Misplaced }.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-R7FAOX:97: @result missing close brace.
warning: doc_cache_create: unusable help text found in file 'catalan'
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-noH3OM:97: @result expected braces.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-noH3OM:97: Misplaced {.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-noH3OM:97: Misplaced }.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-noH3OM:97: @result missing close brace.
warning: doc_cache_create: unusable help text found in file 'eulergamma'
````

**Comment by cbm755** [comment]
@vassbu, I can't reproduce this.  The texinfo looks fine to me.  After installation, does "help catalan" work?

What is your Octave version?

**Comment by vassbu** [comment]
Octave version is 4.0.0.rc3
>> help catalan
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-hvIUeE:97: @result expected braces.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-hvIUeE:97: Misplaced {.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-hvIUeE:97: Misplaced }.
C:\Users\TOREGA~1\AppData\Local\Temp\octave-help-hvIUeE:97: @result missing close brace.
warning: help: Texinfo formatting filter exited abnormally; raw Texinfo source of help text follows...

warning: called from
    help at line 116 column 7
'catalan' is a function from the file C:\Octave\Octave-4.0.0-rc3\share\octave\packages\symbolic-2.1.0\catalan.m
 -- Function File:  catalan ()
     Return Catalan constant.
          vpa (catalan ())
            (sym) 0.91596559417721901505460351493238
     See also: eulergamma.
   =>
Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org
mailing list.
>>

**Comment by cbm755** [comment]
Just for reference, on Linux and Octave 4.0.0-rc2 I get:
````

 -- Function File: catalan ()
     Return Catalan constant.

          vpa (catalan ())
          => (sym) 0.91596559417721901505460351493238

     See also: eulergamma.
````
I notice that the `=>` (which is what `@result {}` does) is after the see also for you...  I will upgrade my machine to rc3 later tonight and try.

Are you able to test on any other versions of Octave?  3.8.2 and 4rc2 perhaps
