### ISSUE TITLE
about install symbolic-2.2.1 on Octave-3.8.2-5 (W8.1-64b)

### ISSUE THREAD

**Issue by abobroff** [cbm755/octsympy#236]
Hi Colin ! Thank you for your great work - package symbolic .
But I can not install this package:

    >>pkg install symbolic-2.2.1.tar.gz
    -r?? г¤ ?вбп - cвЁ гЄ § --лc д c<.
    configure: error: SymPy version 0.7.5 or later is required
    checking for python... /c/Users/bobrov.ae/AppData/Local/Continuum/Miniconda/python
    checking python module: sympy... yes
    checking checking for SymPy version... 0.7.6
    checking for gawk... gawk

    pkg: error running the configure script for symbolic.
    error: called from 'configure_make' in file C:\Octave-3.8.2-5\share\octave\3.8.2\m\pkg\private\configure_make.m near line 72, column 9
    error: called from:
    error:   C:\Octave-3.8.2-5\share\octave\3.8.2\m\pkg\private\install.m at line 199, column 5
    error:   C:\Octave-3.8.2-5\share\octave\3.8.2\m\pkg\pkg.m at line 394, column 9

**Comment by cbm755** [comment]
thanks for this.  Any idea what `-r?? г¤ ?вбп - cвЁ гЄ § --лc д c<.`?  I saw it in your screenshot in email too.

Its weird that configure gives the error and then proceeds to find SymPy...

@carandraug : can you take a look at this?  Have I messed up something with the bootstrap script?  Perhaps I'm not running that when preparing the tar.gz file... could that cause this?

**Comment by carandraug** [comment]
If you were not running bootstrap, then there wouldn't even be a configure script there in the first place. I took a quick look at the confgure script and things looked right.

@abobroff could you please run this and show us the output?

    PYTHON="/c/Users/bobrov.ae/AppData/Local/Continuum/Miniconda/python"
    version=`$PYTHON -c "import sympy; print sympy.__version__" 2>/dev/null`
    printf -- '-%s-\n' $version
    min_sympy_version='0.7.5'
    printf -- '-%s-\n' $min_sympy_version


    A=`echo "$version" | sed -e 's/\([[0-9]]*\)/Z\1Z/g' \
                             -e 's/Z\([[0-9]]\)Z/Z0\1Z/g' \
                             -e 's/Z\([[0-9]][[0-9]]\)Z/Z0\1Z/g' \
                             -e 's/Z\([[0-9]][[0-9]][[0-9]]\)Z/Z0\1Z/g' \
                             -e 's/[[^0-9]]//g'`
    printf -- '-%s-\n' $A

    B=`echo "$min_sympy_version" | sed -e 's/\([[0-9]]*\)/Z\1Z/g' \
                                       -e 's/Z\([[0-9]]\)Z/Z0\1Z/g' \
                                       -e 's/Z\([[0-9]][[0-9]]\)Z/Z0\1Z/g' \
                                       -e 's/Z\([[0-9]][[0-9]][[0-9]]\)Z/Z0\1Z/g' \
                                       -e 's/[[^0-9]]//g'`
    printf -- '-%s-\n' $B

    res=`echo "x$A
    x$B" | sed 's/^ *//' | sort -r | sed "s/x${A}/true/;s/x${B}/false/;1q"`

    printf -- '-%s-\n' $res

    if test "$ax_compare_version" = "true" ; then
      echo "all good"
        else
      echo "error"
    fi

**Comment by abobroff** [comment]
Hello Carnë Draug! Sorry but I do not understand how to run this your script. In Command Prompt of Windows?

**Comment by carandraug** [comment]
You should run that command on the same prompt from where you start Octave. I am not familiar with windows to guide you there but those commands must be run from bash with the same environment that is used to run Octave.

**Comment by cbm755** [comment]
@carandraug I wouldn't know how to do this either: AFAICT, Octave on Windows just starts the GUI so bash et al is not exposed...

@abobroff Its possible I know even less about Windows than Carnë... but perhaps there is some way to start a terminal (in C:\Octave or where-ever Octave is install).  Alternatively, can you try installing 1. the "bundle" package? and 2. "pkg install -forge symbolic"? and let us know what happens with each.

**Comment by carandraug** [comment]
That will be dependent on the Octave installation. My understanding is that there's several ways to do this (4.0.0 will be the first time that the Octave will distribute Windows installers). Bash (or some other POSIX shell) must be installed otherwise how would the configure script run at all?

So if the OP doesn't know how to do this, we'll need to have more details on the system, first of all, how was Octave installed.

**Comment by abobroff** [comment]
Download Results of symbolic - 2.2.1 from the Octave-forge (home laptop: W7-x64, Octave-3.8.2-5 (from mxeoctave.osuv.de), Python-2.7.9 (Miniconda):

    >>pkg install -forge symbolic
    -r?? г¤ ?вбп - cвЁ гЄ § --лc д c<.
    configure: error: SymPy version 0.7.5 or later is required
    checking for python... /c/Users/13881/Miniconda/python
    checking python module: sympy... yes
    checking checking for SymPy version... 0.7.6
    checking for gawk... gawk

    pkg: error running the configure script for symbolic.
    error: called from 'configure_make' in file C:\Octave-3.8.2-5\share\octave\3.8.2\m\pkg\private\configure_
    make.m near line 72, column 9
    error: called from:
    error: C:\Octave-3.8.2-5\share\octave\3.8.2\m\pkg\private\install.m at line 199, column 5
    error: C:\Octave-3.8.2-5\share\octave\3.8.2\m\pkg\pkg.m at line 394, column 9

But installation of symbolic - 2.1.0 went very well.

**Comment by cbm755** [comment]
OK. And Carne's question: how did you install Octave etc?

In your orig private email, you sourced some file. Can you also test without doing that?

**Comment by abobroff** [comment]
For install Octave-3.8.2 
System administrator:

http://mxeoctave.osuv.de/octave-3.8.2-5-installer.exe  

without  system administrator:

http://mxeoctave.osuv.de/octave-3.8.2-5-portable.7z

**Comment by carandraug** [comment]
This will be easier to discuss if you guys come to #octave on irc.freenode.net we can discuss this better and get some info from the person who makes those binaries.

**Comment by carandraug** [comment]
Seems like that installer will also install a `bash.exe` . Start that and enter the code there.

**Comment by abobroff** [comment]
Hi Colin and Carnë!   Output from run script by Carne:

    bash.exe"-3.1$ C:/Octavework/script_by_carandraug
    -0.7.6-
    -0.7.5-
    -Z0Z.Z7Z.Z6Z-
    -Z0Z.Z7Z.Z5Z-
    -r?? г¤ ?вбп - cвЁ гЄ § --лc д c<.
    --
    error
    bash.exe"-3.1$

**Comment by cbm755** [comment]
Can you change your locale and try again?

**Comment by cbm755** [comment]
Hi @abobroff any progress?  In case I wasn't clear, by "locale" I meant changing your localization settings to english or ascii or something.  It looks like there is an error message on that `r??` line but I do not know what it is.

It might be possible to do something like `export LANG=C` or maybe `export LANG=en_US.UTF-8` at that bash prompt because running `script_by_carandraug`.  Maybe its `LC` not `LANG`: google can probably help.

**Comment by carandraug** [comment]
This is weird, the following

    A="-Z0Z.Z7Z.Z6Z-"
    B="-Z0Z.Z7Z.Z5Z-"
    res=`echo "x$A
    x$B" | sed 's/^ *//' | sort -r | sed "s/x${A}/true/;s/x${B}/false/;1q"`

should set `res` to either "true" or "false" but instead you're getting gibberish. Can you try this last piece, part by part, until we see where it breaks?

    A="-Z0Z.Z7Z.Z6Z-"
    B="-Z0Z.Z7Z.Z5Z-"

    echo "x$A
    x$B"

    echo "x$A
    x$B" | sed 's/^ *//'

    echo "x$A
    x$B" | sed 's/^ *//' | sort -r

    echo "x$A
    x$B" | sed 's/^ *//' | sort -r | sed "s/x${A}/true/;s/x${B}/false/;1q"

For reference, this is what I get

    $ echo "x$A
    > x$B"
    x-Z0Z.Z7Z.Z6Z-
    x-Z0Z.Z7Z.Z5Z-

    $ echo "x$A
    > x$B" | sed 's/^ *//'
    x-Z0Z.Z7Z.Z6Z-
    x-Z0Z.Z7Z.Z5Z-

    $ echo "x$A
    > x$B" | sed 's/^ *//' | sort -r
    x-Z0Z.Z7Z.Z6Z-
    x-Z0Z.Z7Z.Z5Z-

    $ echo "x$A
    > x$B" | sed 's/^ *//' | sort -r | sed "s/x${A}/true/;s/x${B}/false/;1q"
    true

**Comment by abobroff** [comment]
Hi Colin and Carnё!

05/05/2015 I have successfully downloaded the symbolic-2.2.1 from Octave forge (previously failed).

But use for download the command:

    pkg installs symbolic-2.2.1.tar.gz

gives my error.


About new script by Carnё:

error in command  sort -r

![for_octsympy2](https://cloud.githubusercontent.com/assets/8687951/7515803/ce226ce0-f4d2-11e4-9218-e1c84e05f382.png)

**Comment by carandraug** [comment]
The man page of sort on my system has the following warning:

       ***  WARNING  ***  The locale specified by the environment affects sort
       order.  Set LC_ALL=C to get the traditional sort order that uses native
       byte values.

**Comment by cbm755** [comment]
@carandraug so our configure script could `blah | LC_ALL=C sort -r | blah`?

**Comment by cbm755** [comment]
Sort of seems like an upstream problem for m4 script eh?

**Comment by mtmiller** [comment]
Hey guys. I don't think it's a locale problem, all autoconf scripts should already set LC_ALL=C (I haven't checked yours but it should be there).

It looks to me like the sort being run for this user might be the Windows sort.exe rather than the one in the Octave mxe install. If I run `sort -r` in a normal Windows shell, I get something like

    -r Windows can't find this file

Note the garbage error message does start with `-r` and the length of the message is about right.

@abobroff can you tell which sort executable is being run in the same bash environment? Can you show what your PATH is set to?

**Comment by markuman** [comment]
[msys-coreutils](http://hg.octave.org/mxe-octave/file/tip/src/msys-coreutils.mk) 5.97-3 and [msys-bash](http://hg.octave.org/mxe-octave/file/tip/src/msys-bash.mk)  3.1.17-4 are build/distributed in the mxe process...

> This will be easier to discuss if you guys come to #octave on irc.freenode.net we can discuss this better and get some info from the person who makes those binaries

Well, at least this are [untouched mxe builds](http://wiki.octave.org/Windows_Installer#Steps_to_create_Windows_Installer). I even don't have a Windows system atm for testing myself. 

Imho, the mxe thing is a technology to bridge the gap. On modern systems it's in any case better to run Octave in a VirtualBox Linux if you don't want to leave Windows _(for example: on mac os x, calculations in a virtual box machine are faster than on the host)_. Providing GNU Octave as a docker image might run very better than mex......just my 2cents

**Comment by vassbu** [comment]
Hi, I tried to install symbolic-2.2.2 (Win 8.1 64bit, Octave 4.0.0, Python 2.7.9, SymPy 0.7.6) and got similar error output as above:
...checking for python... /c/Python27/python
checking python module: sympy... yes
checking checking for SymPy version... 0.7.6
checking for gawk... gawk
-rThe system cannot find the file specified.
configure: error: SymPy version 0.7.5 or later is required
...

The last line give status=1 and causes the configure_make.m to exit around line 79.
Then I just commentet out the lines
      #if (status != 0)
      #  rmdir (desc.dir, "s");
      #  disp (output);
      #  error ("pkg: error running the configure script for %s.", desc.name);
      #endif
-and the installation completed ok:
make: Entering directory `/tmp/oct-sZklel/symbolic-2.2.2/src'
echo "no installation steps are needed"
no installation steps are needed
make: Leaving directory `/tmp/oct-sZklel/symbolic-2.2.2/src'
For information about changes from previous versions of the symbolic package,
 run 'news symbolic'.
>> pkg load symbolic
>> syms x
OctSymPy v2.2.2: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Detected Windows: using "winwrapy.bat" to workaround Octave bug #43036
Some output from the Python subprocess (pid 4452) might appear next.

OctSymPy: Communication established.  SymPy v0.7.6.
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
>>

Could someone tell me where in the code the tests that returns 
   checking for python... /c/Python27/python
   checking python module: sympy... yes
   checking checking for SymPy version... 0.7.6
   checking for gawk... gawk
   -rThe system cannot find the file specified.
   configure: error: SymPy version 0.7.5 or later is required
are executed - so I can try to dig more into the matter?

**Comment by mtmiller** [comment]
@vassbu can you tell us what sort executable is called from your Octave shell (e.g. `system ("sort")`)? What is your `PATH` environment variable set to (`%PATH%` or `getenv ("PATH")` in Octave)?

As I said in an earlier comment, I think this means the `sort.exe` from Windows is being executed instead of the GNU `sort` provided by your Octave installation.

**Comment by vassbu** [comment]
Hi Mike,
I should have read your comments in 'small print'.
The sort command at the bottom of the configure script is executing the Win system command. The -r option is seen as a file name. If I execute the command 'system("sort --h") from the Octave prompt I get an error: --hThe system can not find the file (translated from Norwegian). If I do the same command from the command prompt in the Octave/bin directory i get the sort help text.
Here is how I managed to do a OK installation of Symbolic-2.2.2:
1. The Octave/bin sort.exe was copied to sort_sh.exe
2. I put a break in the configure_make.m just before [status, output] = shell (cmd, verbose);
3. In the Temp-unpacked script configure I replaced all sort commands by sort_sh.
4. The configure_make was continued, and a OK installation was completed.
Then I repacked my 'new version' of the script configure into the tar.gz package, and did a new ok installation on another PC.

Here is the path:
C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Octave\Octave-4.0.0\bin

**Comment by mtmiller** [comment]
@vassbu, if you are launching Octave with the shortcut installed by the official installer, it should be setting C:\Octave\Octave-4.0.0\bin to come first in PATH (both `octave.bat` and `octave.vbs` do this). If you are launching Octave through some other means, you should probably arrange so that C:\Octave\Octave-4.0.0\bin comes first so the appropriate GNU utilities are found before any Windows (or other) programs of the same name.

Maybe the only thing that could be fixed in octsympy would be to try to run `sort --version` and make sure it is GNU sort before calling the version comparison macros that rely on sorting.

**Comment by vassbu** [comment]
@mtmiller, thanks.
Now I managed to do an installation wirhout errors. On a new Win 8.1 64b Pc (without Octave, Python/SymPy) I followed these steps:
1. Installed Octave 4.0.0 from the downloaded .exe installer. Accepted the defaults.
2. Installed Python 2.7.10 from the downloaded .msi installer.
3. Installed SymPy from Python: pip install sympy.
4. Added C:\Python27 to the Windows system path
5. Started Octave from the octave.bat
6. Cheked the path with the Octave command: system("path")
7. Downloaded the symbolic-2.2.2.tar.gz
8. Installed Symbolic from Octave: pkg install symbolic-2.2.2.tar.gz
-_-

**Comment by cbm755** [comment]
@vassbu thanks for these steps!  Can you also tell us the steps you were using before?  I mean the steps that did not work?  In particular, was the crucial part "5." where you start Octave from octave.bat?

You might also document all this at [the wiki](https://github.com/cbm755/octsympy/wiki/Notes-on-Windows-installation): it seems lots of Windows people need help installing but I'm not able to help, so your step-by-step list would be much appreciated.

**Comment by cbm755** [comment]
> Maybe the only thing that could be fixed in octsympy would be to try to run sort --version and make
> sure it is GNU sort before calling the version comparison macros that rely on sorting.

+1 for this.  I would happily accept a patch that does this or I will try to get to it (someday).

**Comment by carandraug** [comment]
Can you please pull from my `gnu-sort` branch?

    curl --user "cbm755" --request POST --data '{"issue":"236","head":"carandraug:gnu-sort","base":"master"}' https://api.github.com/repos/cbm755/octsympy/pulls

There's two commits there (I forgot that to redirect STDERR on the first). It's a very simple check and I don't have windows toi check if it really works but in theory it should. It does work on my Linux system.

**Comment by cbm755** [comment]
Ok I've merged.  Just for posterity: I was suspicious but AFAICT the `2> /dev/null` *does* work on windows.  I assume because we're inside a bash script.  So I've partially tested this on Windows.

- - - - - - -

I'll now close this as not sure what else we can do here.

Carnë's error message is unique enough that people should find their way here, and learn that they have a path problem:
````
The sort program is not GNU sort.  Please configure your PATH
````
