### ISSUE TITLE
Fails to install package on Python 3.4.2

### ISSUE THREAD

**Issue by yoihito** [cbm755/octsympy#239]
1. I download release package
2. `$ octave-cli`
3. `octave:1> pkg install symbolic-2.2.1.tar.gz`
4. Got this 
```
configure: error: Failed to import SymPy
checking for python... /home/yoihito/.pyenv/shims/python
checking python module: sympy... yes
checking checking for SymPy version... no
```
PROFIT!!1 :)

I found possible mistake in `src/configure.ac` after some investigations. I got syntax error on this `$ $PYTHON -c "import sympy; print sympy.__version__" 2>/dev/null`

I suggest my pull request to fix it. https://github.com/cbm755/octsympy/pull/240

**Comment by cbm755** [comment]
Thanks again for fix!  Will be fixed in 2.2.2, which I should do soon.
