### ISSUE TITLE
laplace/ilaplace do not match the SMT behaviour

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#242]
- [ ] 2 arg form should control output variable not input.
- [ ] symbol collision rules look wrong, at least according to SMT docs.

Maybe other problems too, haven't very carefully.

@maprieto did you intend that these would closely follow the Symbolic Math Toolbox?  If so, we may need to revise them a bit.

**Comment by maprieto** [comment]
(i)laplace and (i)fourier functions have been updated to replicate the variable behavior according to SMT docs. A new pull request is pending (with a downgrade version of the dsolve function to avoid any collision)

**Comment by cbm755** [comment]
I think this is fixed (?)  @maprieto re-open if not.

**Comment by maprieto** [comment]
Right, it should be definitely closed
