### ISSUE TITLE
Not able to symbolically calculate simple Laplace Transforms

### ISSUE THREAD

**Issue by mwwils01** [cbm755/octsympy#245]
I am trying a few laplace transforms of some familiar time functions and I seem to have tripped up the octsympy communication mechanism, here is the error message...

㸒PYTHON: Error in cmd
Resetting the octsympy communication mechanism
Closing the Python pipe...
error: python_cmd: unexpected return
error: called from
    python_cmd at line 143 column 6
    laplace at line 60 column 7
    Laplace_example at line 13 column 3

It may be a problem with the syntax in my code but everything seems okay and I was able to get it to work for a simpler case. Here is what I have...

clc
clear

%--Laplace Example--%

syms t a s

f=t
L=laplace(f)
IL=ilaplace(L)

f1=exp(-a*t)
L2=laplace(f1)

**Comment by cbm755** [comment]
Confirmed, last command fails for me:
````
octave:10> L2=laplace(f1)
Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "<stdin>", line 7, in _fcn
PYTHON: Error in cmd
  File "/usr/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 1118, in laplace_transform
Resetting the octsympy communication mechanism
    return LaplaceTransform(f, t, s).doit(**hints)
  File "/usr/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 118, in doit
    self.function_variable, self.transform_variable, **hints)
  File "/usr/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 1064, in _compute_transform
    return _laplace_transform(f, t, s, **hints)
  File "/usr/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 196, in wrapper
    res = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 1025, in _laplace_transform
    conds = [process_conds(c) for c in disjuncts(cond)]
  File "/usr/lib/python2.7/site-packages/sympy/integrals/transforms.py", line 993, in process_conds
    if m[q] > 0 and m[w2]/m[p] == pi/2:
  File "/usr/lib/python2.7/site-packages/sympy/core/relational.py", line 103, in __nonzero__
    raise TypeError("cannot determine truth value of\n%s" % self)
TypeError: cannot determine truth value of
a > 0
Closing the Python pipe...

error: python_cmd: unexpected return
error: called from:
error:   /home/cbm/octave/symbolic-2.2.1/python_cmd.m at line 143, column 5
error:   /home/cbm/octave/symbolic-2.2.1/@sym/laplace.m at line 60, column 7
octave:10> 
````

*But* it seems to work with sympy from git...  So something is fixed upstream in SymPy...

(I might dig a bit deeper later, but quite possibly its an already-fixed SymPy bug).

**Comment by maprieto** [comment]
Take a look at the log line:  "TypeError: cannot determine truth value of a > 0". If it is assumed that a is positive or negative (obviously the case a=0 is trivial), then everything works fine:
```
syms t a s
a=assume(a, 'positive')
laplace(exp(-a*t))
a=assume(a, 'negative')
laplace(exp(-a*t))
```

**Comment by cbm755** [comment]
Thanks!

An annoying bug: I think one cannot see the error messages on Windows (because of upstream Octave bug https://savannah.gnu.org/bugs/?43036)

Also, maybe `a=0` case is not so trivial!  Shall I do a patch?

**Comment by cbm755** [comment]
> Also, maybe a=0 case is not so trivial! Shall I do a patch?

#250, I will patch.

**Comment by maprieto** [comment]
Since #250 is already closed, should this issue be closed too?

**Comment by cbm755** [comment]
> should this issue be closed too?

Yes I guess so, thanks.

@mwwils01 not much more we can do here, I think it will work better with the next SymPy release (and in the short-term, slightly better with the next Symbolic release).
