### ISSUE TITLE
incompatible with Octave 3.8

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#268]
Due to the whole compact spacing compatibility mess, it seems that disp won't work with Octave 3.8 (the `__compactspacing__` function was added in 4.0). Installing the package with 3.8 works but can't show any variables. The logic could be further fixed to handle both Octave ways of checking whether compact formatting is on or off, or simply add a dependency on Octave >= 4.0 in the DESCRIPTION file.

**Comment by cbm755** [comment]
thanks Mike.  My tests are not run regularly on 3.8.1; I guess I'll drop support for it soon.

Assumptions seem to be broken too, I'll see if I can fix that up then do a new release.
