### ISSUE TITLE
deprecate Octave 3.8 support

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#271]
Perhaps after next Ubuntu LTS is ok?  16.04?  

or maybe sooner, I'm not running tests on 3.8 any more...

There is still some 3.6 cruft around too, clean that up as well.

**Comment by mtmiller** [comment]
Cutting off 3.8 support at 16.04 LTS release sounds fine to me.

**Comment by cbm755** [comment]
done I think
