### ISSUE TITLE
Suppress initialization messages

### ISSUE THREAD

**Issue by oheim** [cbm755/octsympy#273]
During first use of the package the following messages are printed on the console:
````
OctSymPy v2.2.2: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Some output from the Python subprocess (pid 4706) might appear next.
OctSymPy: Communication established.  SymPy v0.7.5.
````

AFAIK, this can't be disabled. I want to use the symbolic package in the documentation of another package and verify the examples with the doctest package. This is my example block:

````
@example
@group
f = @@(x) sqrt (x) + (x + 1) .* cos (x);
@end group
@group
pkg load symbolic
df = function_handle (diff (formula (f (sym ("x")))))
  @result{} df = @@(x) -(x + 1) .* sin (x) + cos (x) + 1 ./ (2 .* sqrt (x))
@end group
@group
fzero (f, infsup ("[0, 6]"), df)
  @result{} ans ⊂ 2×1 interval vector

        [2.059, 2.0591]
       [4.3107, 4.3108]

@end group
@end example
````

However, the doctest always fails because the initialization messages mess up the result. Would it be possible to write the messages as warning messages with a particular warning ID symbolic:initialization? Then I could disable their output for my test suite.

**Comment by cbm755** [comment]
I don't think I can fix this until we have a better IPC mechanism to talk to Python :(

The interactive Python executable writes to stderr and I need to wait for it to start up before I can stop it from doing.

OTOH, if I don't run it interactively, it doesn't wait for more inputs.

Possible workarounds:

(a)  "sympref ipc system" can in principle be quiet (it is not currently).  Its slower.

(b) have an initial xfail doctest that does "syms x" or something just to fail...

(c) have a script that runs your tests which does "syms x" before starting the tests.

(d) Wait/help with Pytave.

I do (c) in my CI stuff.

**Comment by oheim** [comment]
The python output is not a problem. It gets ignored by doctest, because it comes from a background process. I was talking about the `disp` commands in the octave code. However, doing a `sym ("x")` before the doctests is a workaround at least.

**Comment by cbm755** [comment]
Ah, ok, that is possible!

**Comment by cbm755** [comment]
Or maybe #275 would mean `sympref quiet` is superfluous?  I won't merge it yet.
