### ISSUE TITLE
inv matrix det 0

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#274]
Hi :D 

Well here a little problem, its when matrix have det 0, in a simple ex:

```
>> syms a
OctSymPy v2.2.4: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Some output from the Python subprocess (pid 1594) might appear next.
Python 2.7.10 (default, Nov 19 2015, 11:51:46) 
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> 
OctSymPy: Communication established.  SymPy v0.7.6.
>> det([a,a;a,a])
ans = (sym) 0
>> inv([a,a;a,a])
Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "<stdin>", line 6, in _fcn
  File "/usr/lib64/python2.7/site-packages/sympy/matrices/matrices.py", line 309, in inv
    return self._eval_inverse(**kwargs)
  File "/usr/lib64/python2.7/site-packages/sympy/matrices/dense.py", line 306, in _eval_inverse
    rv = M.inverse_GE(iszerofunc=iszerofunc)
  File "/usr/lib64/python2.7/site-packages/sympy/matrices/matrices.py", line 2631, in inverse_GE
    raise ValueError("Matrix det == 0; not invertible.")
ValueError: Matrix det == 0; not invertible.

PYTHON: Error in cmd
Resetting the octsympy communication mechanism
Closing the Python pipe...
error: python_cmd: unexpected return
error: called from
    python_cmd at line 144 column 6
    inv at line 41 column 5
```

Well obs this can happend with more complex expresions.

Cya.

**Comment by cbm755** [comment]
Hmmm, that is a bit messy!  What do you think should happen instead?

**Comment by latot** [comment]
Hi, in octave this is the default result to this case (only make a matrix full "Inf"):

```
inv([1,1;1,1])
warning: matrix singular to machine precision
ans =

   Inf   Inf
   Inf   Inf
```

personally i don't have problem with a message of determinant =0 while octsympy don't reset the communication,

Cya.

**Comment by cbm755** [comment]
FYI: the resetting should be harmless (sympy objects don't depend on the state of the pipe).

But yes, we could do better and have an Octave-native (rather than Python) error message.

**Comment by cbm755** [comment]
If you want to try to fix this, maybe have a look at `@sym/lhs.m` or perhaps `@sym/vertcat.m` (see `flag`).

**Comment by latot** [comment]
Hi, well i have a little try to fix it, i don't know python but i know the programming logic so if you can check it please :D , new inv function to replace in @sym/inv.m

```
function z = inv(x)

  [n,m] = size(x);
  if n ~= m
    error('matrix is not square')
  end

  cmd = {
	'x, = _ins'
	'flag = 0'
	'r = "whatev"'
	''
	'if x.is_Matrix:'
	'	try:'
	'		r = x.inv()'
	'	except ValueError:'
	'		flag = 1'
	'else:'
	'	try:'
	'		r = S.One/x'
	'	except ValueError:'
	'		flag = 1'
	''
	'return (flag, r)'};

  [flag, z] = python_cmd (cmd, x);

  if (flag)
    error('ValueError: Matrix det == 0; not invertible.')
  end

end
```

**Comment by cbm755** [comment]
Yes, that looks right in the matrix case.  Do you want to do a Pull Request?

1. I don't think the scalar case will raise a ValueError: it will just give `zoo`.  I guess we'll need to decide if `inv(sym(0))` should be the same as `1/sym(0)`.

2. would be great to add `%!` test coverage at the bottom of the file.

3. The error message could be improved---doesn't need to say ValueError.

**Comment by latot** [comment]
Hi, point 2 and 3 are done, with the 1 i'm in the same, i normaly perfer get an error or the zoo message, because if you choose inf like octave then found where is the problem in big codes will be very dificult.

**Comment by latot** [comment]
i would like do a difference here, as i read in the codes i think zoo represent infinite values, but here or 1/sym(0) represent undefined values, with that as base i think we can think or use inv(sym(0))=1/sym(0) while sym(0) always be a number.

**Comment by cbm755** [comment]
Sorry, I don't understand your comment.  `zoo` is complex infinity.  The issue for scalar `x` is whether a user would expect `inv(x)` to do the same as `1/x`.

(Note for matrices, it might be different: Octave users will generally expect `inv` to mean "compute the inverse" whereas slash means "solve a linear system" (e.g., with Gaussian Elimination).)

File a PR if you have a specific change you want here.

**Comment by latot** [comment]
mm, before it, is the concept. zoo is infinity, there no problem.
but 1/0 don't is infinity, so basically we can't use zoo for that. 1/0 is positive infinity and negative infinity. or undefined.

for that reazon if we use zoo for infinity we can't send zoo to inv(0) or 1/0

**Comment by cbm755** [comment]
`1/0` being some sort of infinity is common practice in both Octave (doubles) and SymPy.  I'm not going to change that.  Maybe there is a better discussion but here is one example: https://github.com/sympy/sympy/issues/5195
