### ISSUE TITLE
Initialize Sympy on load package

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#275]
Hi again, Its posible initialize sympy when the package is loaded?

**Comment by cbm755** [comment]
hmmm, I wonder if this can be [done using PKG_ADD](http://www.gnu.org/software/octave/doc/interpreter/PKG_005fADD-and-PKG_005fDEL-Directives.html)?

What do you think?  Would you like to try it?

**Comment by latot** [comment]
Hi, it actually works, a very brute try, in the PKG_ADD file add 'syms a;clear a', well i don't like load like this, but i can't found other way, as i know the conection only is stabilized when we run some comand whithout pid.

**Comment by cbm755** [comment]
Cool!  Maybe `__symbolic_tmp__= sym('a')`: people will not appreciate us overwriting their `a` variable :-)  Or maybe `python_cmd('pass');`

What if there is an error in PKG_ADD?  does the package still load?

One downside is user has no chance to change any settings (`sympref`) before opening the pipe.  Another might be memory overhead of starting up python and sympy even if user never actually makes a symbolic object.

@oheim what do you think of this idea?

**Comment by latot** [comment]
with errors in the PKG_ADD only show it as normal errors, the package is loaded correctly.

**Comment by mtmiller** [comment]
@latot I'm curious, what is the use case or reason for wanting to initialize SymPy before it is needed? Is there a reason why loading it early is better than loading it on demand? Is it a performance issue, is it a cosmetic issue, is it because you are not sure if Python / SymPy will work and you want to know a priori instead of failing in the middle of some function?

**Comment by mtmiller** [comment]
This code seems safest to me to do in a PKG_ADD

    function __load_sympy__ ()
      x = sym ('x');
    end
    __load_sympy__;
    clear __load_sympy__;

**Comment by latot** [comment]
mm, when we execute some script and sympy init in the first function the logs is mixed with that data...., personally i don't like that mix.

And, if we load the package i think is because we will use it, then happen the same as above.

**Comment by cbm755** [comment]
Startup in 2.7.0 is now much quieter (in fact it can be made totally silent with "sympref quiet on").  So I think I'll decide not to do this.  Can always be re-opened.
