### ISSUE TITLE
[maint] CI failures on doctests: term widthchange?

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#276]
I think Travis may have changed the default line lengths and things are wrapping around.

A newer (unreleased) doctest might help as IIRC @catch22 improved how `doctest` deals with terminal widths.

**Comment by catch22** [comment]
I think you are referring to https://github.com/catch22/octave-doctest/blob/master/inst/private/doctest_run.m#L104.

**Comment by cbm755** [comment]
eh, still failing with doctest-0.4.1 (!)  Will investigate...

**Comment by cbm755** [comment]
I see: the terminal width effects python too :(

**Comment by cbm755** [comment]
Ok, fixed in 1ebebadf195509f512d9b41b6648de3b0f29557d.
