### ISSUE TITLE
Weird number, 2^0.5

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#279]
Hi, here a weird behavior with nums:

```
sym(2.^0.5)
warning: Using rat() heuristics for double-precision input (is this what you wanted?)
warning: called from
    sym at line 221 column 7
ans = (sym)

  1393
  ────
  985 

```

i found this playing with matrix D: i don't know if is a real bug, because we can do sym(sym(2).^0.5) or sym(2.^sym(0.5)) and works fine, but it don't see practic most use sym on all numbers.

```
sym(2.^sym(0.5)+2.^0.5)
warning: Using rat() heuristics for double-precision input (is this what you wanted?)
warning: called from
    sym at line 221 column 7
warning: Using rat() heuristics for double-precision input (is this what you wanted?)
ans = (sym)

  1393     ____
  ──── + ╲╱ 2 
  985         
```

and a little question, are some way to use sym class as a default? (if i write "2" interpret it as a sym)

Cya.

**Comment by cbm755** [comment]
Well, the warning should indicate something could go wrong.  `2^(sym(1)/2)` would be my recommended input.

Maybe the warning message could be improved?  "warning: conversion of floating point to symbolic is likely to be lossy"... or something.  For comparison, when I last checked, Matlab's Symbolic Math Toolbox just silently gives you an approximation.

I did consider special casing `sym(0.5)` (and other small fractions) to avoid the warning but I thought its better for people to discover this on an easy problem...  However, note that `sym(pi)` and some fractions of pi work correctly via special case code in `@sym/sym.m`.

**Comment by cbm755** [comment]
> are some way to use sym class as a default? (if i write "2" interpret it as a sym)

Not that I know of...  Perhaps by changing Octave---would not be popular!
