### ISSUE TITLE
implementing determinant to non-square matrix

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#280]
Hi, well i thing this can be very useful, what do you think?

math form, m is any matrix (square or not)
det(m)=det(m*m')^(1/2)

ex uses, area of sphere:
```
syms r a b
x=r*sin(a)*cos(b)
y=r*sin(a)*sin(b)
z=r*cos(a)
u=[diff(x, a) diff(y, a) diff(z, a);diff(x, b) diff(y, b) diff(z, b)]
#last line is [0 0 0] diff on constant r
octave:58> simplify(det(u))
warning: Using rat() heuristics for double-precision input (is this what you wanted?)
warning: called from
    sym at line 221 column 7
    detm at line 5 column 2
ans = (sym)

     ____________
    ╱  4    2    
  ╲╱  r ⋅sin (a) 
```

Note in the example i use m.' instead of m'

**Comment by cbm755** [comment]
Do you have a citation for this?

**Comment by latot** [comment]
mm, i found here:
https://en.wikipedia.org/wiki/Determinant
check jacobian determinant.

As a note to this, this non-square determinant represent the space in the vectors of the matrix (area/volume/etc)

**Comment by cbm755** [comment]
Ok.  But I'm not convinced its used generally for non-square matrices.  In particular, wikipedia doesn't seem to say the notation `det(A)` is used for the this.

Do other CAS extend their `det` or similar command for non-square matrices?

Even if we want this change, it would be preferable (to me) to make it in the upstream SymPy project.  We should be a thin layer on top of SymPy.

**Comment by latot** [comment]
mm, here other doc:
https://www.math.uchicago.edu/~may/VIGRE/VIGRE2007/REUPapers/FINALAPP/Peng.pdf

its better think this like jacobian determinant, and the condition should be columns>=rows, in the example i only overload the det function, but its preferable use other.
sorry ask this but i'm not familiarized with nomenclatures, what means CAS?

i'm agree up this to SymPy :D

**Comment by cbm755** [comment]
CAS == computer algebra system: i.e., Maple, Mathematica, Matlab's Symbolic Math Toolbox, etc.

That reference has `det(A^T*A)` but I don't think it has `det(A)` for rectangular `A`.  I don't think I want to change Symbolic's det.  If you convince upstream SymPy than of course I will.

But my opinion is that people who want to calculate `sqrt(det(A^T*A))` can do just that: they do not need to have `det(A)` overloaded.

**Comment by latot** [comment]
Oki doki.
https://github.com/sympy/sympy/issues/10318
