### ISSUE TITLE
Handling error proposal.

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#281]
Hi again, well i found other case of error in the solve function, so thinking how try to handle more specific the problems i got an idea, to see if you like it, this example to handle the errors on solve:

```
function varargout = solve(varargin)

  varargin = sym(varargin);

  e_a = {"AttributeError", "'BooleanTrue' object has no attribute 'as_coefficient'"
	 "AttributeError", "'BooleanFalse' object has no attribute 'as_coefficient'"};

  if (nargout == 0 || nargout == 1)
    cmd = { 'eqs = list(); symbols = list()'
	    'flag = 0'
            'for arg in _ins:'
            '    if arg.is_Relational:'
            '        eqs.append(arg)'
            '    else:'
            '        symbols.append(arg)'
            '#'
	    'try:'
            '	if len(symbols) > 0:'
            '		d = sp.solve(eqs, symbols, dict=True)'
            '	else:'
            '		d = sp.solve(eqs, dict=True)'
	    'except Exception as e:'
     strcat('	if type(e).__name__ == "', char(e_a(1,1)), '" and str(e) == "', char(e_a(1, 2)), '":')
	    '		flag = 1'
     strcat('	elif type(e).__name__ == "', char(e_a(2,1)), '" and str(e) == "', char(e_a(2, 2)), '":')
	    '		flag = 2'
	    '	else:'
	    '		raise'
            '#'
	    'if flag:'
	    '	return (flag, "whatev")'
	    '#'
            'if len(d) >= 1 and len(d[0].keys()) == 1:'  % one variable...
            '    if len(d) == 1:'  % one variable, single solution
            '        return (flag, d[0].popitem()[1])'
            '    else:'  % one variable, multiple solutions
            '        return (flag, sp.Matrix([r.popitem()[1] for r in d]))'
            '#'
            'if len(d) == 1:'
            '    d = d[0]'
            'return (flag, d)' };

    [flag, out] = python_cmd (cmd, varargin{:});

	if (flag == 1 || flag == 2)
		error("Booleans equations.")
	end

    varargout = {out};

  else  % multiple outputs
    cmd = { 'eqs = list(); symbols = list()'
	    'flag = 0'
            'for arg in _ins:'
            '    if arg.is_Relational:'
            '        eqs.append(arg)'
            '    else:'
            '        symbols.append(arg)'
            '#'
	    'try:'
            'if len(symbols) > 0:'
            '    (vars, solns) = sp.solve(eqs, symbols, set=True)'
            'else:'
            '    (vars, solns) = sp.solve(eqs, set=True)'
	    'except Exception as e:'
     strcat('	if type(e).__name__ == "', char(e_a(1,1)), '" and str(e) == "', char(e_a(1, 2)), '":')
	    '		flag = 1'
     strcat('	elif type(e).__name__ == "', char(e_a(2,1)), '" and str(e) == "', char(e_a(2, 2)), '":')
	    '		flag = 2'
	    '	else:'
	    '		raise'
            '#'
	    'if flag:'
	    '	return (flag, "whatev")'
	    '#'
            'd = []'
            'for (i, var) in enumerate(vars):'
            '    d.append(sp.Matrix([t[i] for t in solns]))'
            'return (flag, d)' };

    [flag, out] = python_cmd (cmd, varargin{:});

	if (flag == 1 || flag == 2)
		error("Booleans equations.")
	end

    varargout = out;
    if (length(out) ~= nargout)
      warning('solve: number of outputs did not match solution vars');
    end
  end

end
```

part of the idea is simplify handling things from python/octave, and avoid handle only via error type to can specify the problem.

Thx.

**Comment by latot** [comment]
asking about code style

**Comment by cbm755** [comment]
I find this a bit hard to read: if you you send PR it will be easier as then I can easily see diffs...

stylewise: probably its better to use multiple `except:` clauses in Python, see https://docs.python.org/2/tutorial/errors.html

**Comment by latot** [comment]
mm, that was one option, but if we use that we should in every exception check the error message like:

```
exception
  if
exception
  if
exception
  if
```
try to avoiding that line excess i try this:
```
exception
  if
  elif
  elif
```

**Comment by cbm755** [comment]
How about: if there is an exception, pass a string of the error back to Octave and then call error with that?

(Ideally the communication between Octave and Python would just do this for all functions---maybe later with something called pytave)

Actually, its not so bad right now on Linux and Mac because you at least can see the Python error: but on Windows its annoying because of my stupid `winwrapy.bat`, which eats the stderr and hides the errors from us.

**Comment by latot** [comment]
D:
other way its the same but we can call raise in else if the error don't is in the handled lists.

**Comment by cbm755** [comment]
Sorry, I'm still unclear what problem you are trying to solve.

I repeat:

> How about: if there is an exception, pass a string of the error back to Octave and then call error with that?

No `if`s inside exceptions needed...

**Comment by latot** [comment]
actually the handled errors are via type, but in sympy in the same type are multiples errors, so when we recive the error message handled of actsympy not always its the real problem its can difficult know what is the problem, so trying to avoid this problem i think try pass the error of python to octave but we can't do that now, so the other option its check the problems we know are, check the type and the error message, the code posted here its an example, using the flag option to handle several errors.

**Comment by cbm755** [comment]
>  but we can't do that now,

why not?  get string of error, set flag, pass flag and string back to Octave.  If flag set, call Octave's error with the string.  See `@sym/isprime.m` for example.

**Comment by latot** [comment]
ups sorry bad explication, i mean, you exaplin top we can't pass the error string to handle it, but we can use the flag system.

**Comment by cbm755** [comment]
I wonder if we can do this `(flag, err)` idea in `python_cmd.m` instead: then we could do it for every function, not just one at a time.  It would also be nice to get a string representation of the Python stack trace and display that before calling error.

I had planned to worry more about this later, perhaps after using "pytave" (https://hg.mtmxr.com/pytave) for better communication...

**Comment by latot** [comment]
as a note when this can be improved the files should re-raise the errors if try is used for others reasons.

**Comment by cbm755** [comment]
Should we close this?
