### ISSUE TITLE
non-deterministic behaviour in (new) ilaplace

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#287]
CC @maprieto have you seen this?

I've narrowed down the problem to `L = ilaplace(exp(c*s))` (where c and s are `syms c s`)

Sometimes I get this:
````
pydebug: exp(c*s)
pydebug: ('r=', {a__: 1, b__: c*s})
pydebug: exp(c*s)
pydebug: ('rlist=', [1, c*s])
pydebug: c
pydebug: 1
L = (sym) DiracDelta(c + t)
````

Other times I get:
````
pydebug: exp(c*s)
pydebug: ('r=', {b__: c*s, a__: 1})
pydebug: exp(c*s)
pydebug: ('rlist=', [c*s, 1])
pydebug: 1/s
pydebug: c*s
L = (sym)

  ⎧                             │t│       │c│    
  ⎪           0             for │─│ < 1 ∨ │─│ < 1
  ⎪                             │c│       │t│    
  ⎪                                              
  ⎪        ⎛     │    ⅈ⋅π⎞                       
  ⎨╭─╮0, 1 ⎜1    │ t⋅ℯ   ⎟                       
  ⎪│╶┐     ⎜     │ ──────⎟                       
  ⎪╰─╯1, 1 ⎝   1 │   c   ⎠                       
  ⎪───────────────────────        otherwise      
  ⎪           t                                  
  ⎩                                              
````

One of the new tests fails sometimes but not others...   Looks to be an ordering assumption about lists.  I guess this `rlist=list(r.values())` is non-deterministic (on Python 3 anyway)...

**Comment by cbm755** [comment]
@maprieto This is annoying me as its causing random test failures so I'm going to merge it.  Let me know if this is not the right solution and we can revert it.

**Comment by maprieto** [comment]
Perfect! That's natural to use r[a_] and r[b_] (I can't understand why I'd need to use a list instead of the original dictionary..??)

**Comment by cbm755** [comment]
no problem!  I think its a very common error when switching to Python 3!
