### ISSUE TITLE
support {} in subsasgn subsref(sym and symfun)

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#292]
Hi, i was experimenting again and i found this, this 3 function have missed the type value "{}"

@sym/subsasgn
@sym/subref
@symfun/subsref

Without it some returns in python fails, sadly i don't understand very well how works this functions.

**Comment by cbm755** [comment]
Can you give an example that fails?  These are supposed to be support what happens if one does:
`syms x`
`x{2}`
So far, that syntax isn't used for `sym` objects...

**Comment by latot** [comment]
use this to inv:
```
function z = inv(x)

  cmd = {
        'x, = _ins'
        'if x.is_Matrix:'
        '    return x.inv()'
        'else:'
        '    return S.One/x'
        };

  z = python_cmd (cmd, x);

end
```
this will fail with:
```
error: @sym/subsref: invalid subscript type '{}'
error: called from
    subsref at line 62 column 7
    python_cmd at line 144 column 3
    inv at line 61 column 5
error: evaluating argument list element number 1
error: called from
    python_cmd at line 144 column 3
    inv at line 61 column 5
```
some times i see some unrecognized values, so i think this can help there.
I check the code of this 3 functions and only actually support "()" and "."

**Comment by cbm755** [comment]
currently, it must return a tuple.  you need:
````
        '    return x.inv(),'
        '    return S.One/x,'
````
(note commas)

**Comment by latot** [comment]
mm, yes, but i think can help have enabled the {} in this functions, we can avoid some problems...

**Comment by cbm755** [comment]
I don't know what `x{1}` should do so I don't how overloading it would help with anything.  Unless maybe it would help give a better error message.

**Comment by latot** [comment]
coincidently, now i found a situation where this is required:
```
syms a(t) b(t)
r=[a, 1;2, 3];
q=[b, 1;2, 3];
r/q
```
using the sympy function \

**Comment by cbm755** [comment]
> coincidently, now i found a situation where this is required:
> ```
> syms a(t) b(t)
> r=[a, 1;2, 3];
> q=[b, 1;2, 3];
> r/q
> ```
> using the sympy function \


I think this is just https://github.com/cbm755/octsympy/issues/8 (i.e.,
Octave bug https://savannah.gnu.org/bugs/?42152)
