### ISSUE TITLE
extend class

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#301]
To improve Intervals:

https://github.com/cbm755/octsympy/issues/303
sympy/sets/sets.py

Note, Intervals only support unicode not ascii.
Updated.

**Comment by latot** [comment]
well, experimenting, we can use union removeing the ascii from the code, but probably we lost compatibility with octave, behaviors too diferents in the outputs, personally  i don't like the output of octave i prefer the sympy because in octave is too confusing.

**Comment by cbm755** [comment]
I'm not sure what you mean.  Can you give some example?

**Comment by latot** [comment]
okis, lets suppose we wanna improve the ceil function, from here:
http://docs.sympy.org/dev/modules/mpmath/general.html

basically should be:
```
x = sym(1.1)
z = python_cmd ('return mpmath.ceil(_ins[0]),', x)
pydebug: error exporting variable:
pydebug: x: 2.0
pydebug: type: <class 'mpmath.ctx_mp_python.mpf'>
z = python does not know how to export type <class 'mpmath.ctx_mp_python.mpf'>
```

and if we use S()
```
x = sym(1.1)
z = python_cmd ('return S(mpmath.ceil(_ins[0])),', x)
z = (sym) 2.00000000000000
```

so i think add the classes from mpmath.ctx_mp_python can help to make this functions, we can use the S() but the result its little weird...

**Comment by cbm755** [comment]
Ok I see I think.

In general, I think we should return sympy `Float` objects rather than lower-level mpmath objects.

With `S()` (or `N()`) you get something Symbolic pkg users will think of as a `vpa` object.

**Comment by latot** [comment]
how its posible transform this 2.00000000000000 to 2? (basically simplify, but that don't works there)

**Comment by cbm755** [comment]
> how its posible transform this 2.00000000000000 to 2? (

When would we want that to happen?

**Comment by latot** [comment]
in the secod example using S() to transform mpf, it returns to 2.00000000000000, would be ideally return 2, imaging an big calc using this... i think its a bad idea return with all this zeros..

**Comment by cbm755** [comment]
but why we need the second example?

**Comment by latot** [comment]
https://github.com/cbm755/octsympy/issues/217

in sympy to can improve fix, frac or similar are from mpmath, the second example its the example to improve it.

**Comment by cbm755** [comment]
I think we can use `Float`, `Integer` and other SymPy objects.

`frac(sym(pi))` should give `π - 3`: (no mpmath there)

Even with a SymPy `Float`:
````
>> vpi = vpa(pi, 40)
vpi = (sym) 3.141592653589793238462643383279502884197

>> % frac
>> vpi - floor(vpi)
ans = (sym) 0.1415926535897932384626433832795028841972
````

Maybe in some case we need to directly use mpmath within python_cmd.  Ok, but I don't see why we need to return such a thing back to Octave: just convert to `Float` (or whatever).

**Comment by cbm755** [comment]
Maybe round can be something like this?
````
  sf = 'lambda x: Integer(x.round(0))';
  y = uniop_helper (x, sf);
````

**Comment by latot** [comment]
Okis, lets use Integer to round the numbers, thx.

**Comment by latot** [comment]
this should be done with the last commits of union.
