### ISSUE TITLE
Improve Intervals

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#303]
Hi, well i was thinking this can help a lot in octave, can we add it here?
if you are agree what strcture do you recomend?

But probably we will be need add classes from here:
sympy/sets/sets.py

**Comment by cbm755** [comment]
Sounds good.   Here's some things that would be nice to have:

````
>> evalpy('x = Interval(2,4)')
pydebug: Treating unexpected SymPy obj as scalar: <class 'sympy.sets.sets.Interval'>
x = (sym) [2, 4]
>> evalpy('y = Interval(1,10)')
y = (sym) [1, 10]
>> evalpy('z = Interval(9,10*S(pi)/3-1)')
z = (sym)

  ⎡        10⋅π⎤
  ⎢9, -1 + ────⎥
  ⎣         3  ⎦

>> evalpy('a = y.intersect(z)', y, z)
a = (sym)

  ⎡        10⋅π⎤
  ⎢9, -1 + ────⎥
  ⎣         3  ⎦
````

Also
````
>>> pprint(x.union(z))
         ⎡        10⋅π⎤
[2, 3] ∪ ⎢9, -1 + ────⎥
         ⎣         3  ⎦
````

**Comment by latot** [comment]
how structure this? we can't use the word union or similar, or use interal_function like interval_union?

**Comment by cbm755** [comment]
I wonder if `@sym/interval.m` is the right way to make such things?  A quick search suggests Matlab's SMT does not expose intervals.

However, Octave has an "interval" package (which does floating point interval arithmetic: mostly unrelated).  Need to make sure they don't fight...

**Comment by cbm755** [comment]
>> how structure this?

maybe `setdiff.m`, `setxor` `union.m` etc?  And `@sym/interval` to make them...
````
x = interval(sym(2), sym(4))
````

**Comment by latot** [comment]
mm, but the union, intersect, etc, have practically others functions and behaviors...

**Comment by cbm755** [comment]
> or you mean check the class type in union.m etc..

Yes.  But I'm not sure.

I even thought about extending `colon`: i.e., see that `y = 2:x` would make an `Interval`.   But I now think this is a bad idea.

**Comment by latot** [comment]
bad idea improve intervals or change colon on that way?

**Comment by latot** [comment]
i already check the interval package, i seems don't have any interval.m file

**Comment by cbm755** [comment]
bad idea to change colon in that way.

**Comment by cbm755** [comment]
> a little question, how i can call specific an symbolic function, or a octave function? (overloaded)

`inst/@sym/foo.m` is called only when at least one input to `foo` is a `sym`.  `inst/bar` is in the global namespace (and thus should be avoided I think).

**Comment by latot** [comment]
D: i get a problem, the intervals are represented as arrays, so i can't find any way to recognize it to can use from union (ex)....basically
```
isinstance([Interval(1, 2), [4, 5]], sympy.Set)
False
```
other ways is start checking one by one

**Comment by cbm755** [comment]
Does this help?
````
In [470]: A = FiniteSet(1,2,4,5)

In [471]: Ia = Interval(1,10)

In [472]: Ia.is_Interval
Out[472]: True

In [473]: Ia.is_FiniteSet
Out[473]: False

In [474]: A.is_Interval
Out[474]: False

In [475]: Ia.is_FiniteSet
Out[475]: False
````
Note the current `setdiff.m` and `setxor.m` that I wrote don't use any of that...  I just copied how `setdiff` for `doubles` works... perhaps this was not the correct decision
