### ISSUE TITLE
problem sending data to python, Bool with inverse

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#309]
Hi, well here a problem, for some reason when octsympy send data to python is recognized in some way  doing poible this:
```
>> syms x
>> a=x*x==1
a = (sym)

   2    
  x  = 1

>> inv(a)
ans = (sym)

          -1
  ⎛ 2    ⎞  
  ⎝x  = 1⎠ 
```
i try this in python but should send an error:
```
evalpy("x=symbols('x');w=S.One/(x*x==1)")
error: AttributeError: 'BooleanFalse' object has no attribute '_eval_power'
error: called from
    python_cmd at line 145 column 5
    evalpy at line 174 column 17
```

**Comment by cbm755** [comment]
`==` and `Eq` not the same in SymPy:
````
In [478]: Eq(x,6)
Out[478]: Eq(x, 6)

In [479]: 1/Eq(x,6)
Out[479]: (Eq(x, 6))**(-1)
````
That is why no error is raised: but its still nonsense of course :)

**Comment by cbm755** [comment]
btw, in octave: `char(x == 1)` useful to see what kinds of SymPy objects we are making...  need to document all this better :(
