### ISSUE TITLE
taylor expansions need work

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#31]
see taylor.m.  Hard-coded for 8 terms for example.

**Comment by cbm755** [comment]
Sure @trueutkarsh that would be great.

Maybe this is helpful?   http://stackoverflow.com/questions/22857162/multivariate-taylor-approximation-in-sympy

**Comment by trueutkarsh** [comment]
@cbm755 i have written the python code(function) which does it  ,tested and compared it with few outputs from the matlab .Its working fine.
But I am facing problems in how to incorporate it in octave. Since the function is not present in sympy how I can I use it ?
 Thanks

**Comment by cbm755** [comment]
Sounds great so far.

If you look in `inst/@sym/taylor`, near the end there is a `cmd = { ' ... ' };` bit.  This is python code, you can probably do something similar.  Fork this project, start a new branch, then send a pull request--- even if its not perfect---we'll help!

**Comment by trueutkarsh** [comment]
cool that should do the job..
as soon as I'll incorporate it in octave will send a pull request.

**Comment by trueutkarsh** [comment]
@cbm755  Now that expr=f(x,y) my code needs a list [x,y] as parameter .
"(f, x, a, n) = _ins' " interprets f as expr  ,I want it to interpret x as list of variables and 'a' as list of evaluation points . 
Right now it throws
 "Python exception: TypeError: 'Zero' object does not support indexing
    occurred at line 8 of the Python code block
"
line 8 is
'expr=f'
'var=x'
'i=a'
'expn=expr.subs([(var[x],i[x]) for x in range(len(var))]) '  %this is line 8

**Comment by cbm755** [comment]
Bit hard for me to comment without seeing your whole code...  I suggest you start the pull request, even if it doesn't work yet (then I can see the actual code and even check it out).

**Comment by trueutkarsh** [comment]
https://github.com/cbm755/octsympy/pull/364

**Comment by cbm755** [comment]
Not at the moment, no.  I should probably get on IRC.

**Comment by trueutkarsh** [comment]
@cbm755  I am facing a new problem. the follwing code snippet does'nt seems to work 

  cmd ={'(f, x, a, n) = _ins'
        'z=f'
        'if not isinstance(x,list):'
        '    z=(z.series(x,a,n).removeO())'     
        'var=list(x)'
        'for m in range(len(var)):'
        '    z=z.series(var[m],a[m],3).removeO()'
        'return nsimplify(z)'      
  };
Using this it woks for single variable taylor series but not multiple variable.
if this code snippet works then we can simply merge mtaylor and taylor.
Rather I am using
  cmd ={'(f, x, a, n) = _ins'
        'z=f'
        'if len(z.atoms(Symbol)) ==1 :'
        '    return nsimplify(z.series(x,a,n).removeO())'     
        'var=list(x)'
        'for m in range(len(var)):'
        '    z=z.series(var[m],a[m],3).removeO()'
        'return nsimplify(z)'      
  };
Using this single variable works and multivariable also works 
but this case
"mtaylor(sin(x+y),x)" is not working.
What am I missing ? Please help.

**Comment by cbm755** [comment]
you could just use two `cmd` and two calls to python `python_cmd`, one in case `numel(x)>1` and one when `numel(x) == 1` for now.  Once that works, worry about whether code is nicer by merging them...
