### ISSUE TITLE
undefined function

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#310]
Hi again, well a little issue, when i try tu run a function with sym arguments sadly octave says undefined function.

function code in intervals.m in @sym folder:
```
function [varargout] = intervals(varargin)

  varargin = sym(varargin);
  e=0;

  while (iscell(varargin{1}))
    varargin = varargin{:};
    e=1;
  end

  cmd = {
         'x, = _ins'
         'for i in range(len(x)):'
         '    if isinstance(x[i], sp.Set):'
         '        pass'
         '    elif not isinstance(x[i], sp.MatrixBase):'
         '        x[i] = Interval(x[i], x[i])'
         '    elif len(x[i]) == 1:'
         '        x[i] = Interval(x[i], x[i])'
         '    else:'
         '        x[i]=Interval(*x[i])'
         'return x,'
        };

  if e
    [varargout{1:nargout}] = python_cmd (cmd, varargin);
  else
    varargout = python_cmd (cmd, varargin);
  end

end
```

execution code:
```
function a(varargin)
  varargin=intervals(varargin)
end
```

error:
```
>> a([1, 2], [4, 5])
error: 'intervals' undefined near line 2 column 10
error: called from
    a at line 2 column 9
```

Thx. Sya

**Comment by latot** [comment]
Note, the code have errors, but the problem is clear

**Comment by cbm755** [comment]
hmmm, sorry to ask silly question but have you restarted octave or done `clear all; clear classes`?  (after adding new file)

Some changes are ok without restart, some are not.

**Comment by latot** [comment]
mm, if i call it normally works, but if i call it from
```
varargout = intervals(sym(varargin));
```
i get the error

**Comment by cbm755** [comment]
Maybe I have seen something like this...  There is something about using vargin/vargout where you need to know the size...  possibly if in `a` you call `varargout = cell(1, nargin)`, or something like that, and then do `varargout = intervals(sym(varargin));`

At least something like that happened to me on another project...

**Comment by cbm755** [comment]
you could debug it by testing `a` without using varargin/varargout....

**Comment by latot** [comment]
without varargin/varargout works fine:
```
a=intervals(sym([1, 2]))
pydebug: Treating unexpected SymPy obj as scalar: <class 'sympy.sets.sets.Interval'>
a = (sym) [1, 2]
```

**Comment by cbm755** [comment]
Ok, sorry I don't have a reference, but its something like I said then...

BTW, maybe you know this but look at `char(a)`: it is not an array...

**Comment by latot** [comment]
mm, i think i remove the a function, its this:
```
function [varargout] = a(varargin)
varargout = intervals(sym(varargin))
end
```

**Comment by cbm755** [comment]
maybe `varargout{:} = ...`  or `[varargout{:}] = `

But I think you hit the same issue we discussed above.  Because this works:

````
function [varargout]=b(a)
  [varargout{1:2}]=c(a)
end

function [x,y] = c(a)
  x = 2*a;
  y = 3*a;
end
````

**Comment by latot** [comment]
yes, well here i hace weird behaviors, i'll try tomorrow, i post here this problem calling with varargin because normally only is called functions from symbolic if have a sym argument, but for some reason if we call it with sym(varargin) don't recognize it..

**Comment by latot** [comment]
well, testing and testing, i only can resume this with three ways (if are more best):
1)
```
varargout = cell(1,nargout);
[varargout{:}] = f(varargin);
```
2)
```
function [varargout]=b(a)
  [varargout{1:2}]=c(a)
end

function [x,y] = c(a)
  x = 2*a;
  y = 3*a;
end
```
3)
```
function [varargout]=b(a)
  [varargout{1:nargout}]=c(a)
end
```

**Comment by latot** [comment]
updated to a working function, error persist

**Comment by latot** [comment]
my bad fixed with https://github.com/latot/octsympy/commit/7a71175daa884b6781409dddb38479c251c5b59a

**Comment by cbm755** [comment]
You're right!

But its not an octave bug: `@sym/foo` is only called when its argument is `sym` type, not when their argument is @cell type.

**Comment by latot** [comment]
so if a cell have a sym don't recognize it to use the function?

**Comment by cbm755** [comment]
That's correct: the input has type 'cell'
