### ISSUE TITLE
Deprecating SymPy 0.7.6 support

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#315]
- [x] lots of xtest's around:
    - [x] frac.m
- [x] all the assumptions workaround code.
- [x] Use `a ^ b` in setxor.

**Comment by latot** [comment]
can i remove all tests i found <= 0.7.6?

**Comment by cbm755** [comment]
Done in [dev_250 branch](https://github.com/cbm755/octsympy/tree/dev_v250)
