### ISSUE TITLE
Use version to handle behaviors in Sympy propose

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#319]
Hi, well actually this its a lot of works, with differents versions of sympy we most wait to use one or other functions, and then when it change search and change it, so propose this to handle and simplify a little this, first import this to python header:
```
from packaging.version import Version
```
ex from mpower:

```
  cmd = { 'x, y = _ins'
          'if x.is_Matrix and not y.is_Matrix:'
          '    return sympy.MatPow(x, y).doit(),'
          'else:'
          '    return x**y,'
        };

  z = python_cmd (cmd, sym(x), sym(y));

  % FIXME: with some future SymPy (>0.7.6.1?), we may be able to use:
  %z = python_cmd ('return _ins[0]**_ins[1],', sym(x), sym(y))
```
to
```
  cmd = { 'x, y = _ins'
          'if Version(sympy.__version__) > Version("0.7.6.1")'
          '    return x**y,
          'if x.is_Matrix and not y.is_Matrix:'
          '    return sympy.MatPow(x, y).doit(),'
          'else:'
          '    return x**y,'
        };

  z = python_cmd (cmd, sym(x), sym(y));
```

so handle like this versions, and  when is deprecated we can just delete that fragment and to found it only search the patron "Version(", we can save sympy version in some global var.

**Comment by cbm755** [comment]
`private/python_header.py` and `assumptions.m` have places where this could help.

**Comment by cbm755** [comment]
This is fixed right?

**Comment by latot** [comment]
yes, i consider https://github.com/cbm755/octsympy/issues/340 an special case.
