### ISSUE TITLE
python_cmd: work with "return a" (instead of "return a,")

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#324]
@latot said:

> i was thinking, if we enable the normal return of python?
> ````
> if (~iscell(A))
>   A={A};
> end
> ````
> the normal return don't is an error... so i think can help. (pass tests, atleast here)

**Comment by cbm755** [comment]
When I first wrote the ipc stuff, I think I was worried we would not be able to tell whether python returned a tuple or three separate things.

So I required the user to always return a tuple: so if you want to return a b and c, do `return (a,b,c)`.  But if you want to return a list (cell array), do `return (a,b,c),`.

But maybe we can relax that as you suggest...  Its kind of annoying to have to put that comma in all the time :)

**Comment by latot** [comment]
this is fixed with https://github.com/cbm755/octsympy/commit/a84795ccf71c8027d1699ce42cdf4e10e58447f4?

**Comment by cbm755** [comment]
thanks!
