### ISSUE TITLE
ismember creates nonbool arrays

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#326]
See the XFAIL doctest, and commented out `r = logical(r)`.   This should be fixed.

Same things (or similar) comes up in `isinf` and others.

`logical` is a bit "heavy" for this task.  Basically we can guarantee (while still in Python) that we have a matrix which contains either `true/false` (or perhaps `S.True` and `S.False`).   We should be able to pass an array of bools back to Octave.

I've hesitated to do this because we don't really support any arrays at all in the IPC layer (except lists to cell arrays).

Some other functions return a cell array and work around it like that...  Might be the right fix in the short term.

**Comment by cbm755** [comment]
(I'll probably work on this, along with some changes to isinf and friends)

**Comment by latot** [comment]
Note, actually logical don't works with syms, actually with sympy we can works with this, ex:
```
syms a b c d
m=[a b;c d]
not(m)
```
if we use logical or similiar we will lost this.
actually octave support recognize 0 as false and 1 as true, other option is use findsymbol.
