### ISSUE TITLE
python_cmd, bug empty return

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#339]
Hi, well here this bug is when we run puthon_cmd witout a return ex:
```
python_cmd('')
```
what should return? an empty cell, or just ''

**Comment by cbm755** [comment]
hmmm, yes I see: `python_cmd('1+2')`:
````
error: python_cmd: A(I): index out of bounds; value 1 out of bound 0
error: called from
    python_cmd at line 140 column 3
````
Not sure what should happen.  Maybe nargout should be set to zero, so user gets error for `a = python_cmd('')`
