### ISSUE TITLE
setxor could prepare for the future

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#340]
````
  %%FIXME: In future version of SymPy, replace (A - B) | (B - A) with A ^ B
  % Version(spver) >= Version("0.7.7.dev")
````
With @latot 's nice `Version()` work, this doesn't have to be a comment, the code could actually do this.

**Comment by latot** [comment]
mm, are a reason why i don't use version here, sympy 0.7.7 use that syntax to calc it, if we ise if here we will start recalling the same instruction in two differents way...

**Comment by cbm755** [comment]
> calling the same instruction in two differents way...

Is that a problem?

If we don't do it know, we should add it to the list in #315, to be done when we deprecate 0.7.6 (which will probably be 2017 or so).
