### ISSUE TITLE
breaking octsympy/octave with double octoutput_drv

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#352]
Hi again, well testing i think i found how we can broke this, i mean when we "leave a mess", basically its double return output with octoutput_drv like:

```
octoutput_drv("1")
octoutput_drv("2")
```

don't need to be consecutive.
a little question, how we can stop the execution of the script, whitout kill the pipe?

**Comment by latot** [comment]
maybe with ```import pdb; pdb.set_trace()``` testing

**Comment by latot** [comment]
the function myerr its breaking this too, i test this https://github.com/cbm755/octsympy/issues/118 without my err and works fine, what do you think remove  it? (we can just let python raise exceptions)

**Comment by cbm755** [comment]
> how we can stop the execution of the script, whitout kill the pipe?

I'm not sure that's possible.  E.g., I think `sympref reset` just discards it and starts a new one: see top of `system_ipc_open2`.

**Comment by cbm755** [comment]
I'm happy enough to remove `myerr` as long as everything still works.  We need to make sure the exceptions reliably make it back to Octave.

**Comment by latot** [comment]
check https://github.com/cbm755/octsympy/pull/353 why i think we can't remove myerr

**Comment by latot** [comment]
what exactly happends when you return two values?

**Comment by cbm755** [comment]
> what exactly happends when you return two values?

`readblock` reads the first one.  The second one just sits there on the stdout.  Then the *next command* fails: see my test in 701e6bba2d302ea92c52573a9f5c762754381199.

**Comment by cbm755** [comment]
fixed in #357
