### ISSUE TITLE
fail run python_format_cmd without check

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#354]
hi, well in popen2 ipc system use this:

```
s = python_format_cmd(cmd, false)
```

output with logs:
```
>>> >>>   File "<stdin>", line 10
    _outs = _fcn(_ins)
        ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "<stdin>", line 2, in <module>
NameError: name '_outs' is not defined

OctSymPy: Communication established.  SymPy v0.7.7.dev.
s = 
{
  [1,1] = def _fcn(_ins):
  [1,2] =     _outs = []
  [1,3] =     try:
  [1,4] =         z = sympy.Symbol("a")
  [1,5] =         return z,
  [1,6] =         return _outs
  [1,7] =     except Exception as e:
  [1,8] =         ers = type(e).__name__ + ": " + str(e) if str(e) else type(e).__name__
  [1,9] =         return ("COMMAND_ERROR_PYTHON", ers, sys.exc_info()[-1].tb_lineno)
  [1,10] = _outs = _fcn(_ins)
}
s2 = 
{
  [1,1] = try:
  [1,2] =     octoutput_drv(_outs)
  [1,3] = except:
  [1,4] =     myerr("PYTHON: Error in var export")
}
```

this its with popen2, i'm losted here D: in how this parts works, or the reason why this error.

//
testing, this is only in popen2, in system ipc works fine.

**Comment by cbm755** [comment]
I guess this is #344 right?  I'll take a look...

**Comment by latot** [comment]
mm, i think are teorically differents but practically similars

**Comment by cbm755** [comment]
Hmm, something to do with pasting code into python I guess.  popen2 should be like you typed the code yourself...  I don't quite understand how this relates to blank lines (our documentation says in several places not to use blank lines.

The `try:` `exception` bit seems more flexible w.r.t., blank lines.  I'll refactor a bit...

**Comment by cbm755** [comment]
Take a look at #356.  If that looks good I'll merge.

**Comment by latot** [comment]
yay, looks good, only see my little comments.

**Comment by latot** [comment]
awww, fix:
```
  cmd = { 'def _fcn(_ins):' ...
          '    _outs = []' ...
          '    try:' ...
          cmd{:} ...
          '        return _outs' ...
          '    except Exception as e:' ...
          '        ers = type(e).__name__ + ": " + str(e) if str(e) else type(e).__name__' ...
          '        return ("COMMAND_ERROR_PYTHON", ers, sys.exc_info()[-1].tb_lineno)' ...
          '' ...
          '_outs = _fcn(_ins)'
```
i try replace empty line with # but don't works D:

**Comment by cbm755** [comment]
Yeah I saw that too.  It generally seems more robust once its inside the `try:`.  Maybe they do some heuristics, not just parsing exactly what is entered.  When I play with copy-paste in ipython, the double `return` sometimes confuses it too...   At any rate, #356 does not make things worse ;-)
