### ISSUE TITLE
windows "bundle" pkg uses system python (instead of bundled py.exe)

### ISSUE THREAD

**Issue by genuinelucifer** [cbm755/octsympy#368]
I tried the following to install symbolic on octave 4.0
```
>>pkg install symbolic-win-py-bundle-2.2.4.zip
For information about changes from previous versions of the symbolic package, run 'news symbolic'.
>> pkg load symbolic
>> syms x
```
And i got the following error message after the last command
```
OctSymPy v2.2.4: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Detected Windows: using "winwrapy.bat" to workaround Octave bug #43036
Some output from the Python subprocess (pid 6304) might appear next.
extractblock: read an error back from python
str1 =
<class 'ImportError'>

str2 =
No module named 'sympy.logic.boolalg'

error: error reading back from python
error: called from
    extractblock>process_item at line 166 column 7
    extractblock>helper at line 51 column 14
    extractblock at line 13 column 8
    python_ipc_popen2 at line 82 column 7
    python_ipc_driver at line 30 column 13
    python_cmd at line 138 column 9
    sym at line 361 column 5
    syms at line 158 column 9
error: evaluating argument list element number 3
error: called from
    syms at line 158 column 9
```
Any workaround? Am I missing something?

**Comment by cbm755** [comment]
hmmm, not seen that before.  previous bundle (2.2.3) working?

Also, test with "sympref ipc system"?

Do you have any older versions of sympy installed on your machine?

**Comment by genuinelucifer** [comment]
i tried 
```
>> pkg load symbolic
>> sympref ipc system
Resetting the octsympy communication mechanism
Forcing the system() octsympy communication mechanism
>> syms x
```
But errors popped up again
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 24, in <module>
ImportError: No module named sympy
OctSymPy v2.2.4: this is free software without warranty, see source.
Using system()-based communication with Python [sysoneline].
Warning: this will be *SLOW*.  Every round-trip involves executing a
new Python process and many operations involve several round-trips.
status =  127
out = <output_block>
<item>
<f>9999</f>
<f>
&lt;type 'exceptions.ImportError'&gt;
</f><f>
No module named sympy
</f>
</item>
</output_block>


error: system() call failed!
error: called from
    python_ipc_sysoneline at line 92 column 5
    python_ipc_driver at line 34 column 15
    python_cmd at line 138 column 9
    sym at line 361 column 5
    syms at line 158 column 9
error: evaluating argument list element number 3
error: called from
    syms at line 158 column 9
```

I do not have any other version of sympy installed!

**Comment by genuinelucifer** [comment]
I tried the following but the errors remain:
```
>> pkg uninstall symbolic
>> pkg install symbolic-win-py-bundle-2.2.3.zip
For information about changes from previous versions of the symbolic package, run 'news symbolic'.
>> pkg load symbolic
>> syms x
```

**Comment by cbm755** [comment]
This might be #369: do you have another python installed?

**Comment by genuinelucifer** [comment]
Yes. I have python 2.7 and python 3.1 installed.

**Comment by genuinelucifer** [comment]
In path, I have put python 3's directory.

**Comment by genuinelucifer** [comment]
If you could suggest where to look, I might be able to fix the issue and submit a PR.

**Comment by cbm755** [comment]
start with the wrappy.bat script...  I think I just *assumed* it would prefer `py.exe` from the package directory (i.e., the one installed with the bundle).  But I don't know anything about paths on windows (well, only autoexec.bat from DOS).

I would *love* some help with all things Windows as I don't usually have access to such systems.

A possibly workaround: we could rename our bundled py.exe to `octpy.exe` or similar.

**Comment by genuinelucifer** [comment]
Finally it worked! :)
Renamed the py.exe to octpy.exe and also remove the check on the batch file. It returned 0 if python(2) was found. Instead, now it uses octpy.exe always.
Thanks for the help.

**Comment by genuinelucifer** [comment]
I actually just unzipped the release binary and did the change and then zipped it again to use.
When i downloaded the source, I didn't find any py.exe so I am assuming you keep it in the binary while releasing.

**Comment by cbm755** [comment]
It is built by this script: https://github.com/cbm755/octsympy/blob/master/make_windows_package.sh

**Comment by cbm755** [comment]
In particular, line 69/70 will need changed...   You comfortable doing a PR for this?

**Comment by genuinelucifer** [comment]
I am submitting the PR now.
