### ISSUE TITLE
maybe `char(x)` should do something different

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#375]
Someone contacted me on sourceforge suggesting using it to expose the underlying `srepr` might not be ideal....

TODO: find the conversation, post here.

**Comment by cbm755** [comment]
From a email conversation:

>>> I'm trying to run a Matlab script named scam.m in octave, and notice that sym@char appears to
>>> work differently in octave. 
>>
>> Perhaps it would be better to have "char(x)" do the same as "disp(x, 'flat')".
>
> I think that would work if the newline that disp() adds is suppressed. I'm using octave 3.8.0 on OS X. My version doesn't accept disp(x, 'flat') as far as I can tell. I did set display to flat in symprefs to try it. It works but I need to remove the newlines.
>
>> What do you think? Maybe file a new bug at github?

**Comment by cbm755** [comment]
Note: `@sym/sym.m` docs refer to `char` having this behaviour: would have to change that too.

**Comment by cbm755** [comment]
I was making a class demo today and needed to label a figure based on a `sym`, specifically something like `sym(pi)/3`.  Currently `title(char(sym(pi)/3)))` looks a bit horrid: `Rational....`.

So I do think we want `char(x)` to give `x.flat`.

  And maybe we need some other convenience function to return the srepr/pickle.

**Comment by latot** [comment]
mm, personally i only use the char function to debug, i think to simplify this we can change the char function to char or other nice format and keep this feature:
https://github.com/cbm755/octsympy/issues/651

Thinking a little, actually the options to handle some parts of octsympy are half mixed, in one part we have a user options, but in other debug options, so maybe we can reconstruct part of this and make a:
```
sympref debug 1
```
to enable or disable all this options and keep clean the user env.

**Comment by cbm755** [comment]
Ok.  I will change `char` for now.  Not sure about keeping snippets.

In case its helpful, `x.pickle` gives the same debugging use as `char(x)`, but of course not part of our "API".

If there still are any debug modes, then I agree using a common "sympref debug on" is a good idea.  But there may not be any ;-)

**Comment by cbm755** [comment]
Hmmm, in https://github.com/cbm755/octsympy/issues/91#issuecomment-56350484 I claimed SMT docs made it clear `char(x)` gave MuPAD code.  I've reread it and its not clear...

**Comment by cbm755** [comment]
At least in 2015b: "returns a string representation of the symbolic object A in MuPAD syntax."  But online docs for 2016b say "Convert symbolic objects to character vectors.".  But neither does it explicitly say its *not* MuPAD syntax.

It sounds to me like their intention is char gives a human-readable string output, or maybe its just that I want that to be true...

I could ask someone to check something on 2016b but I'm not sure what the check would be!

**Comment by mtmiller** [comment]
To me this almost seems like an implementation detail, meaning we can do what we want. Let's say `char(x)` returns MuPAD syntax in Matlab. What good does it do to be compatible with that? Is a Matlab user going to expect that `char(x)` returns a string that they can paste into `$TOOL`? Is there some internal mechanism calling `char(x)` that this function can't just be documented to be "use `srepr(x)` if you want the Python syntax to paste into Jupyter" instead?

**Comment by cbm755** [comment]
Any thoughts on exactly naming of that function?  `srepr(x)`, `sympy(x)`, `sympy_code(x)`, etc.  Note there is `ccode(x)` and `fortran(x)` already but that's not quite the same thing.

**Comment by mtmiller** [comment]
I like either `srepr(x)` or `sympy(x)`, both are probably recognizable and meaningful self-documenting names to SymPy users. My fingers stumble over `srepr` personally, but maybe that's just me.
