### ISSUE TITLE
Support saving/loading `sym` objects from files

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#376]
I've been meaning to look at saving `sym` objects to disk.  They are really just a structure with a few fields.  Only `x.pickle` (currently `char(x)` but #375 might change that) is actually important as far as SymPy is concerned.

1.  I've never promised API stability of that structure, might need to stabilize the structure a bit too.  Or at least read about loading/saving `@` classes.

2.  Should we rename `x.pickle` to `x.srepr`?  It was originally a pickle but has not been for a long time.  See also #269.

**Comment by cbm755** [comment]
How to start: look at "saveobj" and "loadobj" methods.

**Comment by genuinelucifer** [comment]
@cbm755 Should I develop 2 new functions ```saveobj``` and ```loadobj``` which would save the object (passed as argument) using python code?
else,
To let users save it using inbuilt ```save``` and ```load```, I'll have to implement saveobj function in the sym class. How do I do that?

**Comment by cbm755** [comment]
> I'll have to implement saveobj function in the sym class. How do I do that?

Create a `inst/@sym/saveobj.m` file.  And `inst/@sym/loadobj.m`.

(See the GNU Octave documentation for what they are supposed to do.)

A `sym` objection is basically a `struct`.

For `loadobj`, there is a special "magic" form of calling `@sym/sym.m`
which activates the constructor (see the source of that file).

**Comment by genuinelucifer** [comment]
Hi @cbm755 
I almost completed the functions.
I also installed octave on my linux machine so as to test the files before submitting a PR. I get the following error when I try to use any command (for any file in inst/@sym/)

**Comment by cbm755** [comment]
Are you saying you cannot run tests on some other OS?  If so, please file a separate issue for that.

**Comment by cbm755** [comment]
This error looks familiar...  Where are you running octave from?  should be `inst` (not `inst/@sym`).  Does that help?

**Comment by genuinelucifer** [comment]
Thanks. It worked from inst directory :)

**Comment by cbm755** [comment]
what about tests on Windows?  Can you run them or not?

**Comment by genuinelucifer** [comment]
I guess yes. Only objective C tests are shown undefined. Other tests are
passing.

**Comment by cbm755** [comment]
Closing
