### ISSUE TITLE
tests that create temp files should use "tempname"

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#394]
ccode, fcode may have hardcoded filenames.  Maybe others?

@genuinelucifer interested?

**Comment by genuinelucifer** [comment]
>
> @genuinelucifer interested?
>
>

Will do.

**Comment by genuinelucifer** [comment]
Hi @cbm755 .
I got busy with some other project and hence the delay in following up.
.
I looked up ```ccode``` but it seems that it doesn't create a file if no name is passed. It just returns the contents in 2 variables. So, I don't think it would be good idea to first create a temp file and then read it back.
Also, I could not find any file for ```fcode```...

**Comment by cbm755** [comment]
> Also, I could not find any file for |fcode|...

Maybe it was "function_handle"?  Look at the output from
`octsympy_tests` and you'll see something writing temp files.

**Comment by genuinelucifer** [comment]
Thanks. Found it.

**Comment by genuinelucifer** [comment]
@cbm755 Probably #411 completes this...

**Comment by cbm755** [comment]
thanks!
