### ISSUE TITLE
CI: non-deterministic test failure

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#397]
Sometimes, I get this test failure.  If I re-start the Travis run, it passes.
````
>>>>> processing @sym/subsasgn.m

***** test

 A = a;  A(I) = 2*b(I);

 B = b;  B(I) = 2*b(I);

 assert (isequal (A, B))

!!!!! test failed

Python exception: AttributeError: 'Integer' object has no attribute 'T'

    occurred at line 5 of the Python code block

shared variables 

  scalar structure containing the fields:

    b =

        1    2    3    4

        3    6    9   12

        5   10   15   20

    I =

       0   0   0   0

       0   1   0   0

       0   0   0   0

***** test

 % scalar RHS

 A = a;  A(I) = 17;

 B = b;  B(I) = 17;

 assert (isequal (A, B))

!!!!! test failed

Python exception: AttributeError: 'Integer' object has no attribute 'T'

    occurred at line 5 of the Python code block

shared variables 

  scalar structure containing the fields:

    b =

        1    2    3    4

        3    6    9   12

        5   10   15   20

    I =

       0   0   0   0

       0   1   0   0

       0   0   0   0

>>>>> processing @sym/subsindex.m
````
TODO: look into this further.

**Comment by cbm755** [comment]
Not sure how long these links last, but here is an example:
https://travis-ci.org/cbm755/octsympy/jobs/121345579

**Comment by MarcoFalke** [comment]
Another one: https://travis-ci.org/cbm755/octsympy/jobs/164867562

**Comment by mtmiller** [comment]
As you can see there is a random component to this test. I just went ahead and tested the edge cases, and sure enough:

    >> b = [1; 3; 5] .* [1:4];
    >> a = sym (b);
    >> I = false (3, 4);  ## instead of rand (size (b)) > 0.5
    >> A = a;  A(I) = 2 * b(I)
    error: Python exception: TypeError: cannot add matrix and <type 'int'>
        occurred at line 1 of the Python code block
    error: called from
        python_cmd at line 174 column 5
        mat_replace at line 40 column 15
        subsasgn at line 99 column 13
        mat_replace at line 50 column 15
        subsasgn at line 99 column 13

Or the exact error in this report:

    >> I = false (3, 4); I(end) = true;
    >> A = a;  A(I) = 2 * b(I)
    error: Python exception: AttributeError: 'Integer' object has no attribute 'T'
        occurred at line 5 of the Python code block
    error: called from
        python_cmd at line 174 column 5
        mat_mask_asgn at line 88 column 5
        mat_replace at line 71 column 7
        subsasgn at line 99 column 13

So logical indexing with a symbolic array falls apart when the index array has only zero or one elements.

**Comment by cbm755** [comment]
Thanks all, especially @mtmiller.

1.  @mtmiller can you file a new issue for that bug?
2.  Someone can make the test deterministic to close this bug.

**Comment by mtmiller** [comment]
> can you file a new issue for that bug?

Done, #598

**Comment by cbm755** [comment]
Great, so just need to make the test deterministic.  Should be a straightforward fix for someone wanting to get involved, see @mtmiller's comment above.
