### ISSUE TITLE
Mac OS X installation is difficult

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#412]
on Octave help list Ben Abbott said:
 
> Octave’s symbolic toolbox is tricky to install on OS X. I’m confident it
> can be done, but haven’t yet done it myself. My difficulty is due to
> Fink’s python which is named “python2.7”. In order for symbolic-2.3.0
> toolbox’s configure process to use Fink’s python2.7, it is necessary to
> modify configure.ac …
> 
> 16 
> -17 AC_PATH_PROG(PYTHON, python)
> +17 AC_PATH_PROG(PYTHON, python2.7)
> 18 if test -z "$PYTHON"; then
> 19   AC_MSG_ERROR(Failed to find Python)
> 20 fi
> 
> You’ll need to replace “python2.7” with the command needed to run python
> in the Anaconda environment.
> 
> Next, run ./bootstrap in order to create the configure script that uses
> the desired python command.
> 
> Then create a tarball for symbolic-2.3.0 using the corrected configure
> script.
> 
>    tar -z -c -f symbolic-2.3.0.tar.gz symbolic-2.3.0
> 
> The symbolic toolbox requires sympy >=0.7.5. Fink provides version
> 0.7.3. Thus, I created a local Fink package for version 0.7.6.1 and
> installed it. 
> 
> I then installed a local version of the Symbolic toolbox
> 
>    pkg install -local symbolic-2.3.0.tar.gz

We should have a better story than that!

**Comment by carandraug** [comment]
If there is already both a python and a python2.7 installed on the system (am I correct in assuming that this is what is happening here), how does the symbolic package then picks the right python during runtime?

Also, there is no need to change the sources. `AC_PATH_PROG` will check if the variable already exists and if so, skip the test. So one should be able to do something like:

    export PYTHON=/path/to/my/python2.7
    octave --eval 'pkg install symbolic-2.3.0.tar.gz'

or using `setenv` from within Octave (note that it expects `PYTHON` to be a path so if you set `PYTHON` to just the bin name, it will not work and look for python only in the path anyway).

**Comment by bpabbott** [comment]
Ok. I tried "export PYTHON=python2.7", but that did not work. Is it necessary to include the entire path?

**Comment by carandraug** [comment]
> Ok. I tried "export PYTHON=python2.7", but that did not work. Is it necessary to include the entire path?

Yes, it is. "note that it expects PYTHON to be a path so if you set PYTHON to just the bin name, it will not work and look for python only in the path anyway"

We could change it to use `AC_CHECK_PROG` which only looks for the bin name. But if the issue is that there's more than one python in the system, specifying the full path seems better.

But what does the symbolic package does really? Why is the symbolic package not using the first `python` in the path, the one that lacks sympy, and picking the right Anaconda's `python2.7`?

**Comment by bpabbott** [comment]
> But what does the symbolic package do really? Why is the symbolic package not using the first python in the path, the one that lacks sympy, and picking the right Anaconda's python2.7?

The first python in the path is the one provided by Fink which is able to import sympy. However, the configure process is using the system python instead.

> $ python --version
> Python 2.7.10

The system versions is the same version as python2.7, but does not see the sympy installed by Fink.

I'm not using Anaconda, but am using python2.7 provided by Fink. I assume the problem of using Fink's version and Anaconda's version are equivalent.

**Comment by cbm755** [comment]
> But what does the symbolic package does really? Why is the symbolic package not using the first ...

At *run-time*, by default it just uses whatever `popen2('python')` finds (I assume the first `python` in the PATH).

This can be configured *at run-time* with `sympref python /my/path/python`.  Supporting env vars is a good idea: didn't know Octave interpreter allowing manipulating such things when I started this project.

**Comment by carandraug** [comment]
That's interesting. [autoconf documentation](https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Generic-Programs.html) states that it searches `PATH`:

> [...] By default, these macros use the environment variable PATH. [...]
> [...]
> Macro: AC_PATH_PROG (variable, prog-to-check-for, [value-if-not-found], [path = ‘$PATH’])

so that behaviour is odd. Are you sure that it's really the first python in the path and not some python alias to python2.7?

Anyway, it seems that this whole thing won't be an issue anymore (see issue #413 about removing the whole autoconf stuff).

**Comment by bpabbott** [comment]
ummff ... you are correct. Fink's python is named "python2.7", not "python".

In any event, in order to verify the required dependencies are present, I'd prefer to keep the configure process.

**Comment by bpabbott** [comment]
Just to confirm, setting PYTHON to /sw/bin/python2.7 and then running configure works.

> export PYTHON=/sw/bin/python2.7
> ./configure

**Comment by cbm755** [comment]
Good. But that binary is still not used at run time right?

**Comment by bpabbott** [comment]
I assume I can fix that by editing the m-files. But it would be preferred if that could be done automatically.

**Comment by cbm755** [comment]
> I assume I can fix that by editing the m-files.

No need, for now you can do `sympref python /my/path/python2.7`.  But I will plan to also make it respect `$PYTHON` (#415).

>  I'd prefer to keep the configure process.

Noted, although depends if it can be made to play nice with Windows.

**Comment by cbm755** [comment]
Ok, we have warnings instead of errors from `./configure`, run-time checks, plus $PYTHON support.  I'll close this.  Re-open if anything further can be done for Mac.

**Comment by carandraug** [comment]
One further change you may be interested in, is replacing `AC_PATH_PROG` with `AC_CHECK_PROG`. The latter only checks for a program name the current one expects `$PYTHON` to be a path.

**Comment by cbm755** [comment]
Thanks Carne, but with `AC_CHECK_PROG` it only seems to work if I define $PYTHON...
````
$ echo $PYTHON
$ ./configure
checking for sort... /usr/bin/sort
checking for GNU coreutils... yes
checking for python... no
configure: WARNING: Failed to find Python: many features will not work
checking for SymPy version... no
configure: WARNING: Failed to import SymPy: many features will not work
checking for gawk... gawk
configure: WARNING: SymPy version 0.7.6 or later is recommended
````
````
$ PYTHON=/usr/bin/meh ./configure
checking for sort... /usr/bin/sort
checking for GNU coreutils... yes
checking for python... /usr/bin/meh
checking for SymPy version... no
configure: WARNING: Failed to import SymPy: many features will not work
checking for gawk... gawk
configure: WARNING: SymPy version 0.7.5 or later is recommended
````

**Comment by carandraug** [comment]
> Thanks Carne, but with `AC_CHECK_PROG` it only seems to work if I define $PYTHON...

How did you do it? It works for me. I would make a pull request but I can't find the branch where you already changed the errors into warnings.

    $ git diff
    diff --git a/src/configure.ac b/src/configure.ac
    index 4225f9b..c09c472 100644
    --- a/src/configure.ac
    +++ b/src/configure.ac
    @@ -14,9 +14,9 @@ else
       AC_MSG_RESULT(yes)
     fi
     
    -AC_PATH_PROG(PYTHON, python)
    +AC_CHECK_PROG(PYTHON, python, [python], [])
     if test -z "$PYTHON"; then
    -  AC_MSG_ERROR(Failed to find Python)
    +  AC_MSG_WARN(Failed to find Python)
     fi
     
     AX_PYTHON_MODULE(sympy, fatal)
    $ autoconf
    $ echo $PYTHON
    
    $ ./configure
    checking for sort... /usr/bin/sort
    checking for GNU coreutils... yes
    checking for python... python
    checking python module: sympy... yes
    checking for SymPy version... 0.7.5
    checking for gawk... gawk
    $ export PYTHON=python2.7
    $ ./configure
    checking for sort... /usr/bin/sort
    checking for GNU coreutils... yes
    checking for python... python2.7
    checking python2.7 module: sympy... yes
    checking for SymPy version... 0.7.5
    checking for gawk... gawk
    $ export PYTHON=python3.4
    $ ./configure 
    checking for sort... /usr/bin/sort
    checking for GNU coreutils... yes
    checking for python... python3.4
    checking python3.4 module: sympy... no
    configure: error: failed to find required module sympy

I get the error at the end because my python3.4 really does not have sympy.

**Comment by cbm755** [comment]
I just did `s/PATH/CHECK/`: RTFM eh? *wink*.

Thanks I've committed to master.  The warnings were already merged.
