### ISSUE TITLE
deprecate `sympref python meh` in favour of $PYTHON

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#419]
@mtmiller:

> But yes, now that you are using the value of `$PYTHON` from the environment, you could drop
> `sympref python` completely (or have it display a short note to the user that they should use
> `setenv PYTHON` now).

**Comment by bpabbott** [comment]
I had assumed that $PYTHON was only respected by ./configure. In which case, it would be great if the default preference was set with $PYTHON used by configure.

**Comment by cbm755** [comment]
The proposal here is to have no preference: just to respect $PYTHON.

**Comment by bpabbott** [comment]
Understood. I'm concerned that such a change will prevent a package manager from installing a functional symbolic package.

**Comment by cbm755** [comment]
Hmm that sounds bad.  Can you clarify?  Would it be worse than what we have now?

There is (now) a line in `sympref.m` that sets: `DEFAULTPYTHON = 'python'`.  A sufficiently advanced configure script (i.e., not what we have) could presumably change that at install time to `/opt/sw/weird/path/for/packages/python` or whatever.

One example is the "bundle" windows package: preparing that invokes `sed` to change the `DEFAULTPYTHON` to `octpy.exe` (which we ship)---that would still work under this proposal.  
Packagers could do something similar (if necessary).

But if the user sets $PYTHON and that breaks things, isn't that still what she intended?

**Comment by bpabbott** [comment]
I think it would be worse. What we have now could be patched to modify the default. Using <sed> for that is a good solution.

**Comment by cbm755** [comment]
Am I missing something?  Right now, packager can use `sed`.  With this proposal packager can use `sed`.  What is the difference?

Maybe I should do a branch with this change so we have something specific to compare...

**Comment by bpabbott** [comment]
With the present approach, sed can be used to change the preference.. And this change would be private to the symbolic package,

With $PYTHON the shell environment is public.

**Comment by cbm755** [comment]
But sed will still work...

The only difference I can think of is a user who set PYTHON (e.g., for some other program) and then is surprised to find Symbolic uses that python too.

But I think this is a bit like PAGER or EDITOR: I think users generally expect programs to respect those env vars (rather than providing some other configuration mechanism.)

**Comment by cbm755** [comment]
Closed by #427.
