### ISSUE TITLE
support `assume x real` as well as `assume(x, 'real')`

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#421]
```
syms x
assume x positive
assumeAlso x integer
```

Perhaps this makes it a little more obvious that `assume` is going to muck around in your namespace!

Note: SMT doesn't seem to do this.

**Comment by cbm755** [comment]
I'd like to make a decision on this for 2.5.0.  Main arguments in favour:

1.  `syms x y clear` is deprecated so it would be nice for people to change their code to `assume x y clear`.  If we don't do this, they would need to write `x = assume(x, 'clear'); y = assume(y, 'clear')`.
2.  As I mentioned above, this command form "makes it a little more obvious that `assume` is going to muck around in your namespace!"

Main argument against:

1.  SMT does not do this.

@genuinelucifer @mtmiller any objections to doing this?

@latot you already had a PR that did this so I assume you agree.  Can you do a PR that does *only* this?

**Comment by genuinelucifer** [comment]
+1
It seems perfectly reasonable to me that allowing this will help the end users.

**Comment by mtmiller** [comment]
I'm not necessarily in favor, but another pro:

1. tab-completion and help on assume would work, since it would have to be an ordinary function, not a method

I see no problem with supporting this syntax as an extension.

I guess that this command form would be a separate function that only operates on strings, with an arbitrary number of sym names? While the method form `@sym/assume` would still operate on one sym variable at a time?

**Comment by cbm755** [comment]
Thank you both for the quick replies!  @mtmiller your last comment gives me pause; had not thought of that.  Another con:

2. `assume x y positive integer` would imply that `assume(x, y, 'positive', 'integer')` should be supported (?) and we might not want to do the latter.

@mtmiller's suggestion that `inst/assume.m` could be a separate function from `inst/@sym/assume.m` is one resolution.  (I was originally assuming we just move `inst/@sym/assume.m` up one directory, but maybe not).

**Comment by mtmiller** [comment]
Yeah, I'm thinking it would be safer to have `inst/assume.m` only operate on strings, and dispatch to `@sym/assume.m` in a loop over all given symbol names. This way the true compatible `@sym/assume.m` can stay as it is and only operate on a single sym object as in Matlab, avoiding any possible confusion or complications of argument handling there.
