### ISSUE TITLE
Tests Fail due to new PyTave IPC returning python exceptions now

### ISSUE THREAD

**Issue by genuinelucifer** [cbm755/octsympy#457]
Some tests rely on certain errors to occur (like ShapeError) but with the new IPC, this will be returned as Python Exception and in octave we get a '&lt;method_name&gt; falied' instead of the error.

**Comment by cbm755** [comment]
I wonder if this will "just work" once we fix https://bitbucket.org/mtmiller/pytave/issues/24/pyexec-inconsistent-error-handling

**Comment by cbm755** [comment]
Fixed I guess?
