### ISSUE TITLE
get PyTave working on Travis CI

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#461]
The default ipc is set in `sympref`.  But Travis is going to freak out if we do that.

I wonder how hard it would be to build PyTave on Travis (its Ubuntu 14.04 I think).  No point while we have 132 failing tests but eventually we'll need this.

Configuration is in `.travis.yml`: its quite fiddly to debug :(  I suggest holding off for PyTave to mature a bit.

**Comment by cbm755** [comment]
A nice way for this to work would be if the Travis test matrix included running the full test set with popen2 as well as a separate run for pytave.  We could define a `OCTSYMPY_DEFAULT_IPC` env variable: similar to how doctests are dealt with in some runs and not others.

We might not make that env var an official part of the Symbolic API, but just use it for tests.  Or we could just `sed` something in `sympref` within the Travis yml file!

**Comment by mtmiller** [comment]
Wouldn't just putting an inline `sympref ipc $FOO` in the --eval string before running the test suite work? Rather than trying to force sympref to do something different depending on some hidden environment variable or editing the file to do something different.

**Comment by cbm755** [comment]
Fixed by f94f0f10933bc4c9aecf8e0ef8b07375f347546e (#801).
