### ISSUE TITLE
pytave: copying variables back to Python should use pytave

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#464]
At least for non-sym objects.  It will need to do something custom for `@sym` objects.

Suggested first implementation: iterate over the input cell array, recursively into any sub-cellarrays.  Much like copying from Python.

**Comment by genuinelucifer** [comment]
As i mentioned sometimes earlier,
We either:
* need to have a function specific to saving variables (pystore maybe)  in python. In this case would we want to have variable names for python or just store all variables sequentially into `_ins`? 
Or:
*  need to extend pyexec so that it has some sort of syntax (like printf)  to replace those places with the variables passed. Like "pyexec('vara = %%',  [10 10])"  to replace the '%%' with the passed variable.

After writing this again, I feel like we need the first one as the second one seems more obfuscatef.

**Comment by cbm755** [comment]
I agree, its the first one.

1. for now they go in `_ins`: this is the interface `python_cmd` expects.

2. can we use (abuse?) `pycall` for now?  It accepts inputs from Octave.

**Comment by genuinelucifer** [comment]
> for now they go in _ins: this is the interface python_cmd expects.

Ok

> can we use (abuse?) pycall for now? It accepts inputs from Octave.

Well, I thought and one solution came to define a python function which
would append values to _ins and then call it with pycall. It is working for
very basic cases. But is too fragile.
Many tests pass but many more require changes. It's a good starting point
though.
I'll do some more changes to support some more types and submit a PR
tomorrow. (facing power outage today)
Currently strings are not supported. Other basic types are supported.

**Comment by cbm755** [comment]
> Currently strings are not supported. Other basic types are supported.

Do you mean PyTave cannot import strings from Octave?  Please file an issue at `mtmiller/pytave`.

**Comment by genuinelucifer** [comment]
> Do you mean PyTave cannot import strings from Octave? Please file an
issue at mtmiller/pytave.

Well,  after furthur testing, it seems that normal strings have no problem.
Some tests in python_cmd (which I ran) had unicode strings which caused
octave to crash.
Many things work but I find it odd that if I pass 10, it is passed as a
nested list, that is, `[[10]]`!
Although after some more digging, @sym objects are also working now.
But the code is not compatible with python 3. (I used a compile function
which was moved in some other package in python 3)
Do we support both pythons?
I have only tested octsympy with python 2 only till now.

**Comment by cbm755** [comment]
1. ok file "octave unicode to python" bug then.

2. re: nested lists: without code, I cannot comment.  Well, maybe its https://bitbucket.org/mtmiller/pytave/issues/7 and `[[10]]` thing is numpy...  I suspect this behaviour will annoy us in Symbolic.

3. we do support both, and both are tested by Travis, but an implementation that is python specific will do for now.

**Comment by cbm755** [comment]
> ok file "octave unicode to python" bug then.

with "MWE" please.

**Comment by cbm755** [comment]
I think this is done.  Please file upstream issue if there still is one.
