### ISSUE TITLE
pytave: deprecate `evalpy`

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#467]
Symbolic provides the convenience function `evalpy` intended for interactive use.  We should look at whether there is anything useful there for merging with PyTave: @mtmiller.

But Symbolic should probably deprecate it to prevent confusion with PyTave's `pyeval`.

**Comment by mtmiller** [comment]
At a glance major differences look like `evalpy` allows statements, not just expressions, and allows assignment of variables into the `__main__` namespace.

If this isn't actually used by octsympy, you could underscore its name and/or add a warning message like we do to deprecated functions in Octave.

For now I kind of like the idea of keeping functions in pytave specific, one function to evaluate expressions, one to call functions, one to assign variables maybe, until we start to converge on what works best.

**Comment by cbm755** [comment]
The idea of it was:
1. variables created in Python would be automatically exported to Octave.
2. variables needed by Python would be automatically available from Octave.

First first goal works, the second needed a better ipc mechanism (like PyTave ;-).

Its not used by Symbolic: will probably deprecate as you suggest.
