### ISSUE TITLE
PyTave IPC breaks after doing 'clear all' in octave

### ISSUE THREAD

**Issue by genuinelucifer** [cbm755/octsympy#472]
Here's what I get:
```
>> syms x
OctSymPy v2.4.1-dev: this is free software without warranty, see source.
Using experimental PyTave communications with SymPy.
>> clear all
>> syms x
OctSymPy v2.4.1-dev: this is free software without warranty, see source.
Using experimental PyTave communications with SymPy.
error: pyeval: Invalid resizing operation or ambiguous assignment to an out-of-bounds array element
error: called from
    check_and_convert at line 11 column 11
    python_ipc_pytave at line 124 column 5
    python_ipc_driver at line 59 column 13
    python_cmd at line 166 column 9
    sym at line 365 column 5
    syms at line 162 column 9
```
.
It shows error in `is_list = pyeval('is_list')`... But first time this same thing works. Have tried many things (like making is_list global or declaring it on sympref reset) but nothing has fixed it so far.
.
I have to exit octave and reopen for it to work again.

**Comment by mtmiller** [comment]
Works for me

    octave:1> sympref ipc pytave
    Resetting the communication mechanism
    Forcing the PyTave communication mechanism
    octave:2> syms x
    OctSymPy v2.4.1-dev: this is free software without warranty, see source.
    Using experimental PyTave communications with SymPy.
    octave:3> x
    x = (sym) x
    octave:4> clear all
    octave:5> x
    error: 'x' undefined near line 1 column 1
    octave:5> syms x
    OctSymPy v2.4.1-dev: this is free software without warranty, see source.
    Using experimental PyTave communications with SymPy.
    octave:6> x
    x = (sym) x

**Comment by cbm755** [comment]
Works for me too.

**Comment by genuinelucifer** [comment]
Could you please try it based on my 'pytave_ex' branch (the latest PR that
I opened).
.
I don't remember exactly when I started getting this error but probably I
broke something recently.

**Comment by cbm755** [comment]
I *did* test on `pytave_ex`, cannot reproduce.

**Comment by genuinelucifer** [comment]
Probably something wrong with my octave version. I'm using 4.0.0! I cannot
get 4.0.2 yet on ubuntu 16.04 from sudo apt-get!
Which version of octave are you on?

**Comment by cbm755** [comment]
dev version from a week or two ago, that could be it.  I think PyTave doesn't really support Octave 4.0.x (but of course its great if it works).

**Comment by genuinelucifer** [comment]
Oh sorry, i forgot. I also am using dev version of octave.
But I build it atleast a month ago. I'll rebuild and try.

**Comment by genuinelucifer** [comment]
It was probably an octave issue. I checkout out the latest sources and built octave again. After rebuilding pytave again I was able to get this working..
.
Thee oct files built with previous octave sources didn't work with new one and showed that some symbol was undefined.. After rebuilding pytave with new octave, that error got resolved.
