### ISSUE TITLE
add sinc function

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#498]
depends on upstream https://github.com/sympy/sympy/issues/11286

**Comment by cbm755** [comment]
How to start: make a copy of `inst/@sym/gammaln.m` or maybe `inst/@sym/sin.m` and change appropriately.

**Comment by kritkaran94** [comment]
@cbm755 I too tested the same locally and all the examples that you wanted to be added as tests have been added. May be I could take up this issue along with ccode(sinc(x)) at the main sympy repository or the other developer who was working on this could use it for reference. In both the cases I would be happy to help. 

Results with my test 

![screen shot 2016-07-03 at 12 08 46 am](https://cloud.githubusercontent.com/assets/10063868/16542039/62e1ae34-40b5-11e6-81a0-433e7afeedb2.png)

**Comment by cbm755** [comment]
Sure, send a pull request if you want.  See above for how to get started.

**Comment by kritkaran94** [comment]
@cbm755 Please have a look at this [PR](https://github.com/sympy/sympy/pull/11336)

**Comment by cbm755** [comment]
Looks like the right idea.

**Comment by cbm755** [comment]
Are you still interested in adding this to Octsympy?

**Comment by cbm755** [comment]
This is in 1b01b62453e168cccfff6de5e072085df59a93e0, soon to be merged.
