### ISSUE TITLE
pytave: refactor to avoid pystore

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#501]
@genuinelucifer Here's an idea to avoid the pystore stuff (c.f., maillist discussion).

If you look in `python_cmd`, the line-of-code cell-array is first packed inside a function (called `_fcn`).

So:

1. use `pyexec` to define `_fcn`.
2. (perhaps we refactor the code a bit so that `_outs = _fcn(_ins)` isn't done in `python_cmd`, but rather in each of `python_ipc_*` functions.)
2. use `pycall` to call `_fcn` (replacing `_outs = _fcn(_ins)`)
2. (we'll need to assemble a cell-array to use to pass to `_fcn` for `_ins`)
3. we'll get back a list (corresponding to `_outs` in the current code).
4. loop over that list looking for things we can convert to `sym` (similar to what @genuinelucifer's code does now).

This needs pyobject and it also might depend on:

https://bitbucket.org/mtmiller/pytave/issues/27/return-lists-as-pyobject

https://bitbucket.org/mtmiller/pytave/issues/9/pyobject-needs-length-support-maybe-size

**Comment by genuinelucifer** [comment]
@cbm755 This seems like a really nice list for the current situation.  
.  
Also, if we get the namespace issue sorted out:  
https://bitbucket.org/mtmiller/pytave/issues/25/pytave-and-symbolic-play-nice-some  
then it would be really easy to implement point 4 noted here.  
We would still need this list to complete the refactoring and probably get more performance boost (I tried a few things on #499 and it seems using pytave is a lot of beneficial in terms of performance).

**Comment by cbm755** [comment]
I don't think this necessarily depends on namespace support.

**Comment by cbm755** [comment]
I guess this is fixed, current code looks like what is described here anyway---thanks.  Future namespace-related improvements could be another PR/issue.
