### ISSUE TITLE
Travis build should fail if $PYTAVE=="yes" and pytave build fails

### ISSUE THREAD

**Issue by genuinelucifer** [cbm755/octsympy#505]
Well currently even if pytave build fails, the test is run and with popen2 (as it is default) and this can lead to confusion, specially while debugging.

Yesterday one of my commits here showed build successful! I was estremely deligted, removed all my work on the testing branch and pushed a new commit to run on the actual branch. I later found out it wasn't even running with pytave!!

**Comment by cbm755** [comment]
heh, yes I think I mentioned this before too!  I think its a matter of chaining the pytave build stuff like `./configure && make && <sth>` where `<sth>` is `exit` or `die` or something like that with an exit code that causes travis to notice (0, nonzero?)

**Comment by cbm755** [comment]
I think I fixed this in 1b5b5112000bb190b17437ad90cf8774464bfa3a.
