### ISSUE TITLE
Decision: What to do with tests that need to be changed as pytave has conversion to @pyobject now

### ISSUE THREAD

**Issue by genuinelucifer** [cbm755/octsympy#506]
Since many of the types are now `pyobject`s in pytave. Should we edit `check_and_convert` to maintain the old behaviour (specially treating `dicts` as structs)? Or should we go ahead and change the tests.  
  
If we change the tests, there are 2 options:  
* Either we can change the ipc mechanisms at the start (and restore at the end) so that the tests run with the required IPC  
* Or we can have conditional asserts in the tests. For `ipc=="pytave"` assert something but for other IPCs assert something else  
  
Since, pytave currently doesn't build on windows, changing the tests to conform to pytave onyl doesn't seem as a good alternative either.

**Comment by cbm755** [comment]
Thanks for filing this, its important.

We may want to distinguish between the tests of `python_cmd` and tests of `sym` functions.  I hope the latter doesn't change too much.  The former probably will.

I think we should either do "edit check_and_convert..." or "have conditional asserts".  But I'm not sure which yet.

**Comment by cbm755** [comment]
Maybe for now we should convert `dict`s back to struct?  That's probably the quickest path to merging.  Longer term, we need to decide whether Symbolic is allowed to give the user back  `pyobject`.  But maybe one thing at a time.

**Comment by cbm755** [comment]
This can be closed.  Still to be considered what to do with dicts but for now its working.
