### ISSUE TITLE
pytave: refactor import-to-python

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#510]
@genuinelucifer please can you try to refactor the import stuff so that it works like:

````
ins = py.list()
store_vars_in_python(ins, varargin);
````

Then, consider this bit:
````
   s = strjoin(cmd, newl);
   pyexec(s)
````
Somewhere (can't find it right now) I suggested to do something like `pyexec ('def _f(_ins):` with the contents of `cmd` as the function body.  Let's do that.

Then we can:

````
outs = pycall ('_f', ins)
````

**Comment by genuinelucifer** [comment]
I have added the required changes to PR #508. I have also updated it with the other changes that you suggested.

**Comment by cbm755** [comment]
This is done I think
