### ISSUE TITLE
Update help of python_cmd - return list =! return list,

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#517]
Hi, well this issue its a little problem, basically when we execute some python return octave should recognizes the same in ```return List,``` and ```return List```, this problem appears when List its its a python list like this:

```
python_cmd('return S(divisors(_ins[0]))', 150)
warning: number of outputs don't match, was this intentional?
warning: called from
    python_cmd at line 186 column 5
ans = (sym) 1
```
from python_ipc_driver A its (as you can see we only gets the first value)
```
A = 
{
(sym) 1
(sym) 2
(sym) 3
(sym) 5
(sym) 6
(sym) 10
(sym) 15
(sym) 25
(sym) 30
(sym) 50
(sym) 75
(sym) 150
}
```

but in in this case:

```
python_cmd('return S(divisors(_ins[0])),', 150)
warning: number of outputs don't match, was this intentional?
warning: called from
    python_cmd at line 186 column 5
ans = 
{
(sym) 1
(sym) 2
(sym) 3
(sym) 5
(sym) 6
(sym) 10
(sym) 15
(sym) 25
(sym) 30
(sym) 50
(sym) 75
(sym) 150
}
```
and A from python_ipc_driver:
```
A = 
{
  [1,1] = 
  {
(sym) 1
(sym) 2
(sym) 3
(sym) 5
(sym) 6
(sym) 10
(sym) 15
(sym) 25
(sym) 30
(sym) 50
(sym) 75
(sym) 150
  }
}
```
Ideally should be ```return list,``` be equal to ```return list```.

Thx Cya

**Comment by latot** [comment]
The problem its the same with S(divisors) and divisors

**Comment by cbm755** [comment]
Isn't this explained in `help python_cmd`?  Or perhaps I've misunderstood.

**Comment by latot** [comment]
this special case don't is explained in the help D:

**Comment by cbm755** [comment]
Why isn't it covered by this?
````
     If you want to return a list, one way to to append a comma to the
     return command.  Compare these two examples:
          L = python_cmd ('return [1, -3.4, "python"],')
            ⇒ L =
              {
                [1,1] =  1
                [1,2] = -3.4000
                [1,3] = python
              }
          [a, b, c] = python_cmd ('return [1, -3.4, "python"]')
            ⇒ a =  1
            ⇒ b = -3.4000
            ⇒ c = python
````

**Comment by latot** [comment]
u, that its right, i was little confused because we actually support
```
return A
```
and its equal to
```
return A,
```
May be Doc this and explain some differences.

**Comment by cbm755** [comment]
I think its fine, `python_cmd` is mainly intended for developers, who can read the docs... ight? :-P
