### ISSUE TITLE
Creating symfun with `syms` can overwrite existing variables

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#518]
Hi, this problem, basically we suppose a f(t) symfun, if we make a new symfun like g(f), f(t) its transformed to sym(f):

```
>> syms t f(t) g(t) r(f, g)
>> t
t = (sym) t
>> f
f = (sym) f
>> g
g = (sym) g
>> r
r(f, g) = (symfun) r(f, g)
```

Cya.

**Comment by mtmiller** [comment]
According to https://www.mathworks.com/help/symbolic/syms.html, this looks like it's working correctly. When using the `syms` shortcut, any `f(x, y, z)` also automatically defines `x`, `y`, and `z` as independent variables.

**Comment by latot** [comment]
if you write it in reverse order it works:

```
>> syms f(x, y) x(t) y(t)
>> f
f(x, y) = (symfun) f(x, y)
>> x
x(t) = (symfun) x(t)
>> y
y(t) = (symfun) y(t)
```

**Comment by cbm755** [comment]
Oops, I think I discovered this while looking at one of your other bugs.  A @mtmiller says `syms` is a convenience function which just automates a bunch of stuff.  In this case, I think it has done exactly what we asked it to do.  And yes the order matters: it deals with them left to right.

I'd be surprised if SMT does any better, but it might do some other ill-defined behaviour.

**Comment by latot** [comment]
mm, the description don't match with the help of syms, from the help:
```
     Symfuns represent abstract or concrete functions.  Abstract symfuns
     can be created with ‘syms’:
          syms f(x)
     If ‘x’ does not exist in the callers workspace, it is created as a
     *side effect* in that workspace.
```
as is explained if x exist shouldn't be created again, the other way is remove this section and explain the order  matters.

**Comment by cbm755** [comment]
hmmm, possibly a problem if x already existed with assumptions then it would be overwritten.  I agree the docs are a bit misleading!

**Comment by latot** [comment]
thinking, basically we have two options, first no overwrite the function if exist, and the other, overwrite it, in the last case i think should be a warning.

**Comment by cbm755** [comment]
SMT also overwrites with no warning.
