### ISSUE TITLE
problem symvar/findsymbols don't detect symfun

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#519]
Hi again, well i found this trying to edit the diff function, i think its more simple with a example:

```
>> syms t f(g) g(t)
>> symvar(f)
ans = (sym) g
>> symvar(symvar(f))
ans = (sym) g
```

as you can see this is weird, the first part its fine the symbol of f is g, but the symbol of g is t and we get g again, as a note, symvar return a list of symbols but it don't exactly match with the input, its correct say the vars of f is g, but in the text g is printed as a symbol and should be a symfun, theoretically, this should be like this:

```
>> syms t f(g) g(t)
>> symvar(f)
ans = (symfun) g
>> symvar(symvar(f))
ans = (sym) t
```

a little trick is do this (i don't like this):

```
>> syms t f(g) g(t)
>> eval(disp(symvar(f)))
ans = (symfun) g
>> eval(disp(symvar(eval(disp(symvar(f))))))
ans = (sym) t
```

And this don't works inside a functions D:
the idea in this its can apply correctly the diff to functions, for that reason this is necessary.

Thx. Cya.

**Comment by cbm755** [comment]
Well, here's what SMT does:
````
>> syms t f(g) g(t)
>> t
 
t =
 
t
 
>> f
 
f(g) =
 
f(g)
 
>> g
 
g(t) =
 
g(t)
 
>> symvar(f)
 
ans =
 
g
 
>> 
````

`syms` goes left to right.  It first makes `f(g)` then it makes `g(t)` which overwrites the sym `g`.  It think messing around with previous symfun's would be too magical and probably annoy someone.
