### ISSUE TITLE
Support mix symfun

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#520]
Hi again, well i think this can be good here, sympy actually support it, mm, the truth i was thinking it was already supported, until i read in the syms.m `'mixing symfuns and assumptions not supported'`

What do you think?

A little example:

```
>> q=python_cmd('return S("f(g(t))")')
q = (sym) f(g(t))
>> diff(q, t)
ans = (sym)

  d        ⎛ d        ⎞│       
  ──(g(t))⋅⎜───(f(ξ₁))⎟│       
  dt       ⎝dξ₁       ⎠│ξ₁=g(t)
```

**Comment by cbm755** [comment]
Only way I know to do this is sort of what is described at the end of `help symfun`:
````
octave:39> f = symfun(sym('f(g(t))'), t)
f(t) = (symfun) f(g(t))
octave:40> diff(f)
ans(t) = (symfun)

  d        ⎛ d        ⎞│       
  ──(g(t))⋅⎜───(f(ξ₁))⎟│       
  dt       ⎝dξ₁       ⎠│ξ₁=g(t)
````
(Which works the same as your example.)

**Comment by cbm755** [comment]
This is a bit less "magical":
````
octave:46> syms f(t) g(t)
octave:47> F(t) = f(g(t))
F(t) = (symfun) f(g(t))
octave:48> diff(F,t)
ans(t) = (symfun)

  d        ⎛ d        ⎞│       
  ──(g(t))⋅⎜───(f(ξ₁))⎟│       
  dt       ⎝dξ₁       ⎠│ξ₁=g(t)
````
Maybe we should add this example to `help symfun`?

**Comment by latot** [comment]
mm, i think should be added, and if its possible update syms function:
```
>> syms f(g(t))
error: invalid symfun expression
error: called from
    assert at line 94 column 11
    syms at line 169 column 7
```

**Comment by latot** [comment]
this was already supported but now unavailable, see discussion in https://github.com/cbm755/octsympy/issues/537.

**Comment by latot** [comment]
D: i can't found what exactly code disable this feature.....
there is a mix of things

**Comment by latot** [comment]
mm, updating a little the objetive of this issue, the idea its can do this:
```
syms f(t) g(t) r(f, g)
r(f, g)=f+g
```
actually we get this error:
```
>> r(f, g)=f+g
error: Python exception: TypeError: can't convert expression to float
    occurred at line 6 of the Python code block
error: called from
    python_cmd at line 174 column 5
    double at line 87 column 8
    subsasgn at line 89 column 24
error: assignment failed, or no method for 'class = class'
```
technically its re-enable this feature..

Thx. Cya.

**Comment by cbm755** [comment]
I still haven't gone through all these...  But what you're trying to do should look like this:
````
syms f(t) g(t)
r(f, g)=f+g
````
There is no need to create an abstract symfun `r(f,g)` just to replace it with a concrete symfun on the next line.

**Comment by latot** [comment]
uu, you are right, still the same problem D:

**Comment by latot** [comment]
can be useful can use this line too (without the plus line):
```
syms r(f, g) g(t) f(t)
```

**Comment by latot** [comment]
mm, checking code i found some .... unusual things, why this code? (from subsasgn and symfun)
```
      if (all_syms)
        cmd = { 'L, = _ins'
                'return all([x is not None and x.is_Symbol for x in L])' };
        all_Symbols = python_cmd (cmd, idx.subs);
      end
```
The only you are doing is limit the functions..., but we can do that in sympy, and its useful represent values in this way, or your intentions its transform ```syms f(2)``` to ```syms f(t);f(2)```???

Well this line is one of my clues of how enable this, the next part is found what code of sym or display remove the flat:
```
octave:4> f(a)=2*a
error: class has no member 'flat'
error: called from
    private_disp_name at line 39 column 12
    display at line 103 column 8
```

Thx. Cya.

**Comment by latot** [comment]
:O new info, if you remove that lines from subsasgn and symfun this works 90%, that 10% its display, you can't call it directly but you can use it to eval in the end and you can skip problems.

**Comment by cbm755** [comment]
"git blame" will often tell you why some change was made.  The code you mention was added in commit 9424a32c815284ddb4ed8645d75958fe84cc25f0 to fix issue #443.

**Comment by latot** [comment]
:O thx!

**Comment by latot** [comment]
Hi, i found the problems with this, without the checks mix symfuns works fine, you can use it and works normally, but, display its broken there, so you can works but without show it, its that useful? Yes, because we can work wit it and show the eval of that function.

Thx. Cya.

**Comment by cbm755** [comment]
I haven't thought about it in a few years so maybe's its not the most important change...  closing for now, can always be re-opened if needed.
