### ISSUE TITLE
Decision Elliptic Integrals and Series

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#528]
Hi all, well thinking to can improve the elliptic integral to octsympy i think the best we can do its apply series to this, but for can do this we first need improve Sum of sympy, now we can do two focus to this part, first represent the elliptic integrals as the expression or set a default number of sums to keep compatibility with SMT, in that case i think the error value should be less than 1^-16 (octave support max 15 decimals), trying to mix all of this i propose this:

```
f(x) -> gives the number with error less than 1^-16
f(x, y) -> return the sum to y. (i was thinking in a error var but actually sympy can't solve factorial functions)
(or if you like, test factor by factor of the sumatory to find the error)
f(x, some_symbol) -> return the sum expression
```

Exist the possibility of use Taylor but i think will be more complicated and less efficient than series.
About other thing, maybe can be good improve some function with the name "doit", to execute Sums and Integral with it like `int(...).doit()`

What do you think? or others ideas?

Cya.

**Comment by latot** [comment]
mm, are some elliptic functions i can't found the serie, maybe use taylor there? but we should set the grade and the origin point ```f(k, grade, origin)```...

**Comment by cbm755** [comment]
We have elliptic integrals now because of #759 and #676 using SymPy's `elliptic_e` et al.

Please re-open is I've misunderstood what you're suggesting here.
