### ISSUE TITLE
Improve dawsonm

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#530]
Improve dawson in a matrix.

**Comment by cbm755** [comment]
1.  Why do we need this?  (SMT doesn't have it, Sympy doesn't have it)
2.  Even if we do want it, I'm not convinced #533 is correct: for example, wouldn't `exp` need to be `expm`?

**Comment by latot** [comment]
Ups, the second part its right, should be expm, for the first, i'm not sure, generally this type of things are interpretations, i only make it for the idea, from https://github.com/cbm755/octsympy/issues/215.
I don't like to much left ideas on the air.

**Comment by cbm755** [comment]
I'm sorry if [my comment](https://github.com/cbm755/octsympy/issues/215#issuecomment-244666406) was ambiguous: I don't think we want `dawsonm`: I just tried to say what it should look like **if** we wanted it.
