### ISSUE TITLE
Diff - Support numerical Vectors

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#534]
Hi again, well this is for compatibility with octave, a little example from test:

```
>> diff([2 6 7])
ans =

   4   1
```

Cya.

**Comment by cbm755** [comment]
um, what is this bug asking for?

Do you mean the following is wrong?
````
>> diff(sym([2 6 7]))
ans = (sym) [0  0  0]  (1×3 matrix)
````

I think it would be way too magical if that gave `sym([4 1])`.

Reopen if you meant something else.

**Comment by latot** [comment]
the problem is actually exist two diff functions, the differential and the octave diff, both are differents, in octave diff means:
```
     If X is a vector of length n, ‘diff (X)’ is the vector of first
     differences X(2) - X(1), ..., X(n) - X(n-1).
```
so, the options are, if we don't found any symbol in the matrix we can execute that, but i don't like the idea make one function with two differents behaviors, so the question would be, keep comp with SMT or add the new function to diff?

**Comment by mtmiller** [comment]
If there is no `sym` value in the matrix, then `@sym/diff` won't be called.

**Comment by latot** [comment]
yes, but should we support the octave diff if there are no symbols?
like:
```
diff(sym([2 6 7]))
(sym) [4 1]
```

**Comment by mtmiller** [comment]
Ok, those are `sym` but not _symbols_.

What you are suggesting is exactly what @cbm755 said above would be too magical and we should *not* support that.
