### ISSUE TITLE
adjoint doesn't do the same thing as SMT

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#535]
Looks like `.adjoint()` in sympy does what we call `ctranpose`.

@latot do you know how do fix this?  Otherwise, we could remove `adjoint`.

We should also document/explain what `adjoint(sym('x'))` does.

**Comment by latot** [comment]
i can fix it, but can i add an option like adjoint(A, 'conjugate') to use it naturally in SymPy?

**Comment by cbm755** [comment]
See example here: http://www.mathworks.com/help/symbolic/adjoint.html

New PR (or current code in master) does not do that example.

**Comment by latot** [comment]
checking things! https://github.com/cbm755/octsympy/pull/536
