### ISSUE TITLE
SymPy can't Simplify sqrt expressions like sqrt(x*x)/x

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#544]
Hi, well this is only if some one find a werid or incomplete simplify, actually Sympy can't simplify expressions with more than one sqrt, and have some inconsistencies in some works, all of this is explained in this issue: https://github.com/sympy/sympy/issues/11584

Lets do an example:
```
syms t r(f, g) a(f, g) f(t) g(t);
r(f, g)=(f*f+g*g)^(1/sym(2));
a(f, g)=atan(g/f);

accel(f, g)=cos(a)*(2*diff(r, t)*diff(a, t)+r*diff(a, t, 2))+sin(a)*(diff(r, t, 2)-r*diff(a, t)^2);
accel(f, g)=simplify(accel(f, g));
accel(f, g)
ans = (sym)

        ___________               
       ╱      2            2      
      ╱      g (t)        d       
     ╱   1 + ───── ⋅f(t)⋅───(g(t))
    ╱         2            2      
  ╲╱         f (t)       dt       
  ────────────────────────────────
            _______________       
           ╱  2       2           
         ╲╱  f (t) + g (t)   
```

As you can see, its a mix of a lot of things, so if some one need simplify more this i propose use this while:
```
function c = sim(x)
  r = simplify(simplify((x^2))^(sym(1)/2));
    if logical(x == r)
      c = r;
    else
      c = sim(r);
    end
end
```
the return will be something (a^2)^0.5, but will be more easy to use in complicated expressions, the example with this:
```
sim(accel)
        ╱            2 
       ╱  ⎛  2      ⎞  
      ╱   ⎜ d       ⎟  
     ╱    ⎜───(g(t))⎟  
    ╱     ⎜  2      ⎟  
  ╲╱      ⎝dt       ⎠  
```
so there now we know the solution ```diff(g, t, 2)```, and the positive solution, because the sqrt of r in polar is always positive.

Other ex.
```
>> simplify(sqrt(x*x)/x)
ans = (sym)

     ____
    ╱  2 
  ╲╱  x  
  ───────
     x   
```
now:
```
>> sim(sqrt(x*x)/x)
ans = (sym) 1
```
now return 1, but the solutions are 1 and -1.

Be careful with positive and negative solutions, they are case by case.

Now, be careful with some assumptions, some times it doesn't works correctly, for the same reason, ex:

```
>> syms x real
>> sqrt(x^2)
ans = (sym) │x│
```
As you can see makes x real creates the restriction of always the positive solution, and that means x will be always positive, why the last?
```
x=-3   /^2
x^2=(-3)^2
x^2=9   /sqrt
x = -3 or 3  -> checking first eq, its -3, 3 is discarded.
```
if ```sqrt(x^2) == abs(x)``` you can't solve with a ```x<0``` because its a contradiction ```-3 == 3```, so for that can be true its forced ```x``` to be positive.

Cya.

**Comment by cbm755** [comment]
Not much we can do here, its upstream eh?

**Comment by latot** [comment]
Yes, nothing we can do D:

**Comment by cbm755** [comment]
I looked over your example.  I think it worked as expected, as explained upstream.

Provided x is real, `sqrt(x^2)` can be replaced with `abs(x)`.  For example, the equation
`sqrt(x^2) == 3` has solutions `x=-3` and `x=3`.  The equation `abs(x) == 3` also has solutions `x=-3` and `x=3`.  So I think *it is valid* to simplify `sqrt(x^2)` to `abs(x)`.

**Comment by latot** [comment]
Hi, that part is valid, but only in half, when we works with eq, every step are conditions that must be respected, in my example i start from ```x==x```, but if you start from ```sqrt(x^2)``` you can't solve to ```x```, and abs don't is exactly a solution, seems more a trick to simplify this:
```
x=-3
x^2=9
sqrt(x^2)=3 or -3
abs(sqrt(x^2))=3 or abs(-3) //there is right
```
Math is correct, but considering Sympy can't solve integrals with abs seems a bad idea, are other ways to do this without abs, i explain a lot of that in the issue of Sympy.
```
>> python_cmd('return _ins[0].doit()', int(abs(x), x, 1, 2))
ans = (sym)

  2       
  ⌠       
  ⎮ │x│ dx
  ⌡       
  1       
```
Can you reopen this plis? the main issue of simplify still is present.

Thx. Cya.

**Comment by latot** [comment]
Hi again, i wrote new arguments why we can't use abs to solve all ```sqrt(x**2)``` expressions, here is:
https://github.com/sympy/sympy/issues/11584#issuecomment-245480947
don't contradict your comment but expand the abs utility concept in simplify to functions, not only numbers like the examples.

**Comment by cbm755** [comment]
I'm leaving this closed.  If upstream behaviour changes (which I doubt) then we'll change too.

**Comment by latot** [comment]
okidokis.
