### ISSUE TITLE
adjoint fails for scalars

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#546]
@latot what should `syms a` and then `adjoint(a)` give?  Is the adjugate of a 1x1 matrix just  `1`?

Anyway, right now it gives an error.

**Comment by latot** [comment]
to fix the we need a decision check this issue plis https://github.com/cbm755/octsympy/issues/547

**Comment by cbm755** [comment]
Simplest thing to do for now is just work around it like e.g., `@sym/inv` and `@sym/svd` do.
