### ISSUE TITLE
Symbols are not matrix in python, in octave x == [x]

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#547]
Hi, well this is a little problem, first sympy tolerate apply some matrix functions to symbols, but when that happen x its the representation of the matrix, but this contradicts the behavior we have in octave, basically this:

```
>> syms x
>> x == [x]
ans = (sym) True
```

Here we have two ways, keep comp with SMT (we need check the behavior in this cases), or keep Sympy compatibility.

Now the second part is when we send some var from octave to python if the matrix is of 1x1 don't is transformed to matrix:

```
>> syms x
>> python_cmd('return _ins[0].is_Matrix,', [x])
ans = 0
>> python_cmd('return _ins[0].is_Matrix,', x)
ans = 0
```

So this causes this https://github.com/cbm755/octsympy/issues/546
But we must be careful, some functions in Sympy like adjoint support a symbol matrix representation  and works fine:

```
>> syms x
>> a=python_cmd('return _ins[0].adjoint(),', x)
a = (sym)

   †
  x 

>> disp(a, 'flat')
  adjoint(x)
```

Thx. Cya.

**Comment by latot** [comment]
maybe we can keep x as representation of matrix and explicit that in the doc, with that ```x != [x]``` but will can keep comp of SMT and Sympy

**Comment by cbm755** [comment]
I thought #15 dealt with this.

The current behaviour is:

1. On return, all `1x1` Sympy matrices are converted to scalars.
2. Some `@sym` methods such as `svd` convert scalars to `1x1` matrices so that they DTRT.  `@sym/adjoint` should be one of these.
3. Other `@sym` methods such as `sin` work component-by-component on matrices: they tend to use `uniop_helper` or `binop_helper`.

Sorry, but its not clear to me what you want to change...

**Comment by latot** [comment]
mm, more than a change its define a behavior, as you say that is the default behavior now, but what happen when Sympy accept as symbol a matrix representation?

```
>> syms x
>> a=python_cmd('return _ins[0].adjoint(),', x)
a = (sym)

   †
  x 

>> disp(a, 'flat')
  adjoint(x)
```

**Comment by cbm755** [comment]
I think that refers to the adjoint of the Symbol, rather than matrix conjugate transpose of a matrix x.

**Comment by cbm755** [comment]
You're right in the sense that every special case we have that is different from SymPy increases the maintenance burden.

Not much can be done about that in this case.  We can think carefully before adding more code that makes us different than SymPy.

**Comment by latot** [comment]
Okidokis, Thx.
