### ISSUE TITLE
Improve support for querying available assumptions

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#548]
Hi, well, i think this is necessary for this:

```
Ok, pulled the trigger.

Its possible this will screw up for someone who wants:

syms q prime
to give two symbols named q and prime. But meh :)
```

At least notice to the user.

if you don't like this maybe a way to check assumptions.

Cya.

**Comment by cbm755** [comment]
"help assumptions" explains how to list them...

Interesting idea to display at startup.  But its already so noisy that people think something has gone wrong...

**Comment by latot** [comment]
mm, so i think the best option can be do a new function to check assumptions, or expand the assumptions function. if you like what do you prefer?

**Comment by latot** [comment]
i think expand the actual assumptions function can be a bad idea, i was thinking in this syntax:
```
assumptionsCheck prime real zero
```
and return warnings to every not found assumptions and an error if that case, but mix this with the actual assumption..., we can't mix it.

Well what do you think with this propose?

**Comment by cbm755** [comment]
I don't see how it will help.  We already have `assumptions('possible')`.

Fundamentally, the `syms` syntax is ambiguous.  E.g., `syms foo bar meh`: is `meh` supposed to be a variable or assumption?  Currently its taken as an assumption if it matches anything in the output of `assumptions('possible')`.

Consider an example: `syms x postive`: here I have misspelled `positive` so I silently get two variables `x` and `postive`.  I don't think there is anything we can do about that.

**Comment by mtmiller** [comment]
Agree with @cbm755 (feels like this issue is jumping in the middle of another thread that I'm missing). I don't think listing an "assumptions banner" at the start is a good idea, or overthinking it too much at all. If the user can't do what they want with the simple syntax of `syms`, then they should use `sym`, `symfun`, and `assume` instead.

**Comment by latot** [comment]
@mtmiller its right, the initial point of this was that, but now the focus is found some way to do this more easy.

mm, the conflict its when ppl can't know if an assumption is available in scripts, part of the idea is keep compt with SMT, and personally i works a lot with scripts, if i run the script in some Octave/Matlab i need know if it will works, to do that we can do a new function to know this, like this:
```
assumeCheck prime polar
syms var prime polar
```
So, if prime or polar don't is available in that version of Sympy we get an error saying the not available  assumptions.

**Comment by cbm755** [comment]
There will surely be a one-liner that does what you want, something like:
````
assert (any (strcmp (assumptions ('possible'), 'prime')))
````

If either have a suggestion that is better than `assumptions ('possible')`, we could change it (Matlab's SMT does not do this so no compatibility issue).  I suppose it could be extended in a way to check if a given assumption is valid, as @latot wants...  I will retitle.

**Comment by mtmiller** [comment]
No, `assumptions('possible')` seems good to me. We could have a function `isassumption()` that does the above check for a string or cell array of strings.
