### ISSUE TITLE
Standardize Copyright Headers

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#553]
Edited: You know, read this comment to know the format: https://github.com/cbm755/octsympy/issues/553#issuecomment-247376971

Hi, a little question actually are some... formats of the header, its possible standardize this? like actually:
```
 %% Copyright (C) 2003 Willem J. Atsma
 %% Copyright (C) 2014-2016 Colin B. Macdonald
```
Write to:
```
 %% Copyright (C) 2016 Willem J. Atsma and Colin B. Macdonald
```

Thx. Cya.

**Comment by mtmiller** [comment]
No, this loses information about who held copyright on the source on a certain time period. AIUI it's important to keep track of when and by whom copyright was held on a piece of source code, which is typically done by file.

Now if the file is significantly rewritten such that it contains essentially none of the original code (or spirit of the code?) that existed in 2003, then the older declaration could be removed.

**Comment by latot** [comment]
Okis, so tis right this?
```
 %% Copyright (C) 2003-2016 Willem J. Atsma and Colin B. Macdonald
```
or have the same problem?

**Comment by mtmiller** [comment]
That would imply (to my reading) that Willem and Colin worked together as a team on the code continuously between 2003 and 2016, which is not true.

I've talked with @cbm755 about this elsewhere, I think the clearest thing is for each author who contributes significantly to have a distinct Copyright line with the set or range of years that significant work was made.

    %% Copyright (C) 2001 Alice Smith
    %% Copyright (C) 2004, 2007 Bob Jones
    %% Copyright (C) 2010-2011 Carlos Davis
    %% Copyright (C) 2003, 2012, 2014-2016 David Brown

This is the format that is the most sensible IMHO, for four authors working independently as the primary developer on the same file over different sets of years.

**Comment by cbm755** [comment]
Yes, what @mtmiller said.  We need to go through and patch existing files to match this format.

**Comment by latot** [comment]
okidokis, Thx.
For now renaming this to that propose!

**Comment by latot** [comment]
Hi, i'm little confuse, lets suppose this, @mtmiller  do a file then:
```
%% Copyright (C) 2001 Mike Miller
```
then @cbm755 edit it:
```
%% Copyright (C) 2001 Mike Miller
%% Copyright (C) 2005 Colin B. Macdonald
```
now if @mtmiller edit the file this year, should we add a new line?, or what format use?

Thx.

**Comment by cbm755** [comment]
````
%% Copyright (C) 2001, 2016 Mike Miller
%% Copyright (C) 2005 Colin B. Macdonald
````
Then later Colin makes changes from 2016 until 2018:
````
%% Copyright (C) 2001, 2016 Mike Miller
%% Copyright (C) 2005, 2016-2018 Colin B. Macdonald
````
