### ISSUE TITLE
Check diff(f, 2, x) behavior in SMT

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#554]
Hi, well actually this format don't is documented in SMT, so when we can check this we can remove or keep this feature from diff.

Related commit: https://github.com/cbm755/octsympy/pull/552

Exp of the problem: https://github.com/cbm755/octsympy/pull/523

Cya.

**Comment by cbm755** [comment]
Still supported in 2015b.  I guess no hurry for us to to remove that feature.  (anywhere there are notes next to the tests for it documenting it for the future.)
