### ISSUE TITLE
Check sym2poly behavior in SMT, sym2poly(f, x) is double?

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#555]
With this function its necessary check this things:

```
sym2poly(f, x) is double?? sym2poly of f is numeric!
sym2poly(sym(pi)) is double?? check extra symbols.
```

Maybe open a new issue with checks for SMT...

Cya.

**Comment by cbm755** [comment]
first is an error and second is double.

This is discussed and I think dealt with in #543, closing
