### ISSUE TITLE
Update factorial doc

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#562]
Hi, well i think the doc of factorial should be updated:

```
>> syms n
>> simplify(factorial(n)==gamma(n+1))
ans = (sym) True
```

The actual factorial doc only show integer examples, but with a lot of simplifications we get no integer factorials, there its the relation with the gamma function, technically its the same use gamma or factorial but the difference its gamma support non integers numbers.

I don't know if touch the factorial.m file:

```
     Note: this file is autogenerated: if you want to edit it, you might
     want to make changes to ’generate_functions.py’ instead.
```

Thx. Cya.

**Comment by cbm755** [comment]
Well our docs are not a mathematics textbook...

But yes and could add `@seealso{@@sym/gamma}, and similarly in `@sym/gamma`.  But you'll have to remove factorial and gamma from the autogen function list.

Maybe `syms n positive integer` is nicer.

Do a PR if you want, I suppose I'm ok with it.

**Comment by cbm755** [comment]
see `src/generate_pythons.py`.

**Comment by latot** [comment]
its ok if i add a line like this?:
```
For non-integer check @@sym/gamma.
```
or only the seealso?

**Comment by cbm755** [comment]
`For non-integer, @pxref{@@sym/gamma}.`

(Personally I think seealso is fine.)

**Comment by cbm755** [comment]
I'll close this: feel free to re-open if you want to do a PR for it.
