### ISSUE TITLE
update docs to note diff(f, x, y) assumed equal to diff(f, y, x)

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#563]
Hi, here a weird bug from sympy:

```
>> diff(f, x, y)
ans(x, y) = (symfun)

     2          
    ∂           
  ─────(f(x, y))
  ∂y ∂x         

>> diff(f, y, x)
ans(x, y) = (symfun)

     2          
    ∂           
  ─────(f(x, y))
  ∂y ∂x    
```

This can't be fine....

Thx. Cya.

**Comment by latot** [comment]
From sympy: https://github.com/sympy/sympy/issues/11641

**Comment by cbm755** [comment]
1.  First, let's check what SMT does...

2.  Let's document his behaviour in `help diff`: "For partial derivatives, note that the expression is assumed to have sufficiently continuous derivatives so the derivatives commute", followed by your example.

**Comment by latot** [comment]
mm, i'm agree with have compat we SMT, but i think we shouldn't be limited for this, in my opinion if we can have a function with better precision than SMT we should use it.

obvs we can have both with funcs like {func}sane like sym2polysane.

**Comment by latot** [comment]
Or an extra idea, if we use a general var in sympref like "precision" to can select what function use?
like if we set that var to true sym2poly will call to sym2polysane.
What do you think?

**Comment by cbm755** [comment]
We should do what SymPy does.  Almost certainly, they will continue to commute.

SMT says: ["To improve performance, diff assumes that all mixed derivatives commute"](http://www.mathworks.com/help/symbolic/diff.html).

So only action needed here is to update the `help @sym/diff` text.

**Comment by latot** [comment]
mm, i think there are two ideas,
  *do what Sympy does
  *SMT compat
In the first normally i'm agree, but in Sympy actually the vars commute only when we works with a sym function when don't are defined, if we diff a discontinuous function this will works fine.
To say in other way:
```
syms f(x, y)
diff(f, x, y, x) == diff(f, x, 2, y)   % f don't is defined so commute
%% But with a g(x, y) discontinuous, (only imagine some func, don't a representation)
diff(g, x, y) ~= diff(g, y, x)    %g is defined not commute
```

The second, SMT assume derivatives commute, this differ from Sympy, i like Sympy behavior with this part because we can work with discont funcs, always exist the option of sort the vars before execute Sympy but i don't think that make to much sense, i think this like an advantage over SMT.

About taylor, maybe we can add a new feature like:
```
taylor(f, [x, y, z, w], 'continuous', true)
```
then change the algorithm for performance in this.

So, about update diff help, we need say it only happen when the function don't is evaluated! (very important).

Thx

**Comment by cbm755** [comment]
In your example, f is a abstract symfun and g is supposed to be a concrete symfun right?

Can you give an explicit example for `g`?  Do you *know* SMT commutes mixed partials in the concrete symfun case?  Its not clear to me from their docs.

SymPy and our current behaviour seems good to me.

Taylor efficiency improvement could be a different PR/issue but I'd rather do that effort in upstream sympy instead.

**Comment by latot** [comment]
yes, f is abstract and g its concrete.

Sadly i can't found an example now, i'll research it, don't are very common functions.

The current behavior of SymPy in abstract f its very probable will works in all common cases, but it will don't works when the theorem of Clairaut isn't satisfied.


About taylor performance are several ways to improve it, the basic idea i have its in the fixme, basically a cache var to allow the diffs and don't diff all the time.
Other annexed idea can be add a new argument to taylor 'continuous' to say is assumed the function as continuous in every diff and use other algorithm.
Or other way its check the continuity (i'm not very sure how for indef diffs) in this case use the continuous algorithm, ideally if we found how do this only do in high order of functions, in low order can be a waste of time.

About taylor, you like up this code to sympy?

Thx. Cya.

**Comment by cbm755** [comment]
Only examples I know are pointwise, e.g., `g = (x*y^3 - x^3*y)/(x^2 + y^2)` which has `g_{xy}` and `g_{yx}` equal to `1` and `-1` (or maybe the other way around) at (0,0).

MuPAD is the only CAS I know that that tries to be precise near singularities.  Most others do the symbolic manipulations and leave it to the user to be careful with the limits.

Anyway, here we should just document this.

> About taylor, you like up this code to sympy?

Our design goal is as thin as possible so yes most significant things should ideally move to sympy.
