### ISSUE TITLE
subsasgn val(1,1) returns the full matrix

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#571]
Hi, well i don't know if i do something wrong, but anyway better ask, from the subsasgn.m i can't access to a part of val, when i try call it, it returns the full matrix, ex:
```
a=sym([1, 2;3, 4]);
```
now go to subsasgn.m:
```
function out = subsasgn (val, idx, rhs)
val(1,1)  %%Add this line to print the first value of row/column when val is matrix
  switch idx.type
```
now back to octave:
```
>> a(1,1)=2;
ans = (sym 2×2 matrix)

  ⎡1  2⎤
  ⎢    ⎥
  ⎣3  4⎦
```
as you can see this line have a semicolon so the result don't is printed, the result is ```val(1,1)``` we add in the subsasgn.m file.

Why ```val(1,1)``` print the full matrix instead of 1?
i try this from taylor and i get the same result, seems this happens when we use a matrix from a function? or to access a matrix from a internal function use a special syntax?

Thx.

**Comment by mtmiller** [comment]
Yes, this is the correct behavior. Try the same with a non-symbolic matrix:

    >> x = [1, 2; 3, 4];
    >> x(1,1) = 5
    x =
    
       5   2
       3   4

The correct return value for `subsasgn` is the full array, either when calling it directly or indirectly via indexing operators.

**Comment by latot** [comment]
Hi, sorry seems i was less clear, the problem don't is the return, its when we try access to the var internally, the example of the issue can be summarized with this:
```
a=sym([1, 2;3, 4]);
%%in subsasgn val is a
%% then access to the matrix internally
val(1,1)
ans = (sym 2×2 matrix)

  ⎡1  2⎤
  ⎢    ⎥
  ⎣3  4⎦
```
As you can see this don't make to much sense.

As a note, i in the main example put the wrong matrix, maybe that's why i cause this confusion, plis check this again.

**Comment by mtmiller** [comment]
Oh, I see. This is because indexing does not call the class overridden `subsasgn` or `subsref` methods if Octave is already evaluating a class method, presumably to prevent infinite recursion. If you are inside of any class method, you would need to call `subsasgn` or `subsref` directly on the object, for example instead of

    val(1,1)

use

    subsref (val, substruct ("()", {1, 1}))

**Comment by latot** [comment]
Ohh, Thx very much!

**Comment by cbm755** [comment]
Dupe of my nemesis bug #17: this is IMHO the worst aspect of Octave/Matlab OO programming.  Especially as I have to rediscover it repeatedly ;-)  Our source code is full of comments of me cursing about it.

AFAICT, you can't even call the *superclass*'s subref with `()`.
