### ISSUE TITLE
Can't compile Pytave on Gentoo - Octave 4.0.3

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#572]
First, @cbm755 very sorry for do this here, my account of bitbuckets is bug, so i can't do this directly.
This issue is for @mtmiller, basically i can't compile it, i can preconf, conf, but compile fails, here the logs: https://gist.github.com/latot/c12afdb24b88f662fc6a82428d3cded9

Thx . Cya.

**Comment by mtmiller** [comment]
@latot Basically you need to build pytave against Octave 4.2.0 (which is in its release candidate stage now). There have been a lot of API changes between 4.0 and 4.2, and it wasn't worth the effort to make pytave work with both.

**Comment by latot** [comment]
Okidokis! Thx.

**Comment by latot** [comment]
Its possible include this info in the README or INSTALL?

**Comment by cbm755** [comment]
I think INSTALL.md says it:

````
Linked and tested with:

    Python 2.7
    Boost::Python 1.58
    Octave 4.1 (development version)
````

**Comment by latot** [comment]
Now you can update a little it:
```
Linked and tested with:

    Python 2.7
    Boost::Python 1.58
    Octave >=4.1 (development version)
```

**Comment by latot** [comment]
@mtmiller and @cbm755 can you give me yours installed files of pytave plis?, my actual installation its little weird, i don't even know if all files are installed:
```
/usr
/usr/_pytave.a
/usr/_pytave.la
/usr/_pytave.so -> _pytave.so.0.0.0
/usr/_pytave.so.0 -> _pytave.so.0.0.0
/usr/_pytave.so.0.0.0
```
maybe i need change something in the conf to install it.

**Comment by cbm755** [comment]
Sorry, I've never installed pytave; I just use it from wherever I built it with "addpath" cmd in Octave (or equivalent cmdline option).

**Comment by mtmiller** [comment]
> Sorry, I've never installed pytave

Correct, if you read the message that `make install` prints, it suggests how to run Octave to test/use it.

**Comment by latot** [comment]
mm, so theoretically, where the files should be installed?, this put me to think, pytave have a right install directory for the command ```make install```?

**Comment by mtmiller** [comment]
This is getting way OT on this resolved issue. Let's keep pytave development discussions on the octave mailing list or on bitbucket.

**Comment by latot** [comment]
I'm using this way because my bitbucket account is bug D:
I send a mail for support and now only just left wait.
