### ISSUE TITLE
interval(children(n)) should works?

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#573]
Hi, here a new question, this command should be implemented or not?, i think this can help to define part of this issue, https://github.com/cbm755/octsympy/issues/314

an example:
```
>> a=interval(sym(1), 2);
>> b=interval(sym(5), 6);
>> c=union(a, b)
c = (sym) [1, 2] ∪ [5, 6]
>> p=c&interval(sym(10), 11)
p = (sym) [10, 11] ∧ [1, 2] ∪ [5, 6]

interval(children(c))==c
interval(children(p))==p
```

What do you think, or try to do this with other thing?

Only as a note, we always can do this: ```sym(char(n))```

Thx. Cya.

**Comment by cbm755** [comment]
I don't think we allow that for other functions.  E.g.,:
````
A = finiteset(1, 2)
B = finiteset(children(A))
````
Note B is a set containing the matrix `[1 2]`, which is not the same as A: and that behaviour seems to fit the docs.

**Comment by cbm755** [comment]
Actually, I'm not sure what `children(interval(sym(1), 2))` is supposed to do!
