### ISSUE TITLE
decision: rename `pytave` in code, docs, and interface

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#593]
I would like to avoid exposing the name `pytave` to users, since I don't expect the project to ever be used or installed under that name. I vote for calling it `native` in the docs and in the `sympref` interface ("native" meaning it is linking to / invoking the Python runtime directly). Other suggestions?

**Comment by mtmiller** [comment]
Also open to rebuttals and completely different opinions on why I am wrong 😄

**Comment by cbm755** [comment]
Sounds fine to me.  If Pytave is merged into upstream Octave, we (Symbolic) will likely drop the other interfaces soon afterwards anyway.
