### ISSUE TITLE
bool values are evaluated incorrectly

### ISSUE THREAD

**Issue by MarcoFalke** [cbm755/octsympy#597]
Steps to reproduce:

```matlab
matlab:1>> if sym(4)>0 disp '1'; else disp '0';end
1
```

```octave
octave:1> if sym(4)>0 disp '1'; else disp '0';end
warning: implicit conversion from scalar to sq_string
0
```

So the same command gives opposite results on octave and matlab.

(This might be related to #579)

**Comment by cbm755** [comment]
I think this is #191, upstream bug https://savannah.gnu.org/bugs/?43097.  I think this is fixed in the upcoming Octave 4.2.

I'll close for now.
