### ISSUE TITLE
Treatment of unit imaginary

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#604]
Octave has `I` and `i` and `j`.  Matlab has `i` and `j`.
- [x] Currently: `sym(I)`, `sym(i)` and `sym(j)` gives the symbolic imaginary unit `sym(i)`.  This seems good to me.
- [ ] `sym('I')` gives `sym(i)`.  SMT gives a symbolic variable named `I`.
- [ ] `sym('i')` gives `sym(i)`.  SMT gives a symbolic variable named `i`.
- [x] ~~`sym('j')` gives `sym(i)`.~~
- [x] `sym('j')` gives symbolic var named `j`.  SMT gives a symbolic variable named `j`.

I tend to think the SMT behaviour is what a user would expect.  @latot do you agree?

I guess `sym('inf')` and `sym('oo')` should not have special treatment either.  Looks like strings should generally just make symbols.  But this does move us further from SymPy...  In particularly `sym(char(x))` is (almost?) an identity right now.

**Comment by latot** [comment]
mm, i'll try explain what i think about this, first excluding the char function, i think we shouldn't enable python expressions to octave, only in one direction, octave->python.
Now, i can't think a simple way to approach this, my collision point is the ```sym(char(s))```, if no one use it i think will be fine but don't is the case, one of my questions is, that expression is supported for SMT?, for now i'll assume it, if we disable the python expressions we will break the ```sym(char())```, but if we enable it the behavior with SMT will differs in the python expressions.

So, no matter what decision you choose, with this scene we will differ from SMT.
Obvs, exist complex solutions, like store the constants in a new struct/value of sym, and choose what value return case by case.

For now my vote is keep python expressions enabled from sym function, i think i prefer can't use some vars like ```i``` to loose the ```char``` functionality.

**Comment by mtmiller** [comment]
I noticed this recently with `pi` as well, which isn't really a big deal to me because I can't imagine anyone wanting to use a variable named `pi`, but:

    >> r = sym ("rho")
    r = (sym) ρ
    >> double (r)
    error: Python exception: TypeError: can't convert expression to float
        occurred at line 6 of the Python code block
    error: called from
        python_cmd at line 174 column 5
        double at line 87 column 8
    >> p = sym ("pi")
    p = (sym) π
    >> double (p)
    ans =  3.1416

**Comment by latot** [comment]
mm, maybe send a warning saying its a system constant?

**Comment by cbm755** [comment]
I'm pretty sure SMT has `sym('pi')` working like ours: at least it used too.  But lots of their string-quoted stuff has been deprecated lately so it should be checked.  Thank you both for your feedback on this so far.

**Comment by cbm755** [comment]
Symbolic release notes say "Support of character vectors that are not valid variable names and do not define a number will be removed in a future release."   Here, they are talked about `sym('1 + exp(pi)')`, I think `sym('pi')` is still their encouraged syntax for to get a symbolic pi
