### ISSUE TITLE
sym(true) == sym(false) returns an expression, possibly a SymPy bug?

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#609]
I noticed this odd result:

    >> sym(true)
    ans = (sym) True
    >> !sym(true)
    ans = (sym) False
    >> sym(true) == true
    ans = (sym) True
    >> sym(true) == sym(true)
    ans = (sym) True
    >> sym(false) == false
    ans = (sym) True
    >> sym(false) == sym(false)
    ans = (sym) True

So far so good, but now this:

    >> sym(true) == sym(false)
    ans = (sym) True = False
    >> false == sym(true)
    ans = (sym) False = True

I do get the same results in SymPy, so maybe this is a bug in SymPy or maybe it's done this way for a reason I don't understand.

    >>> from sympy import *
    >>> Eq(true, true)
    True
    >>> Eq (true, false)
    Eq(True, False)

**Comment by cbm755** [comment]
cannot reproduce with sympy master so fixed upstream I guess.  (I don't have a specific issue reference to know whether there is an upstream unit test in place or not).
