### ISSUE TITLE
Trying to install the bundle on Windows

### ISSUE THREAD

**Issue by joshessman** [cbm755/octsympy#610]
I keep getting this "Use of uninitialized value in lc at /usr/lib/perl5/5.8/utf8_heavy.pl line 123." error when trying to install the symbolic math bundle.  What might be causing this and how can I fix it?

Thanks.

**Comment by joshessman** [comment]
Just found this code snippet that fixed the issue for me: http://www.nntp.perl.org/group/perl.modules/2010/01/msg69392.html

Hope this helps anyone who has a similar issue!

**Comment by cbm755** [comment]
Thanks!  Can you elaborate whether the change is made in `utf8_heavy.pl` or somewhere else?  (just to help others)

I guess/hope this is Someone Else's Problem (?)

**Comment by joshessman** [comment]
Yes, it is indeed in `utf8_heavy.pl`, around line 123 as stated above.  I have attached a revised `utf8_heavy.pl` (in .txt form as GitHub does not allow .pl uploads)  so that others with this issue can quickly solve it.

 [utf8_heavy.txt](https://github.com/cbm755/octsympy/files/515084/utf8_heavy.txt)

**Comment by cbm755** [comment]
For the record, cross referencing to https://savannah.gnu.org/bugs/?49839

**Comment by mtmiller** [comment]
Thanks, I should have noted that when I commented there last month.

I have only seen this error mentioned when installing the symbolic package on Windows with `pkg`, which led me to believe the error is from the perl version of makeinfo (GNU Texinfo 5 or higher, running under an obsolete version of perl bundled with MSYS), as it processes all doc strings in the package at install time.
