### ISSUE TITLE
deprecate `sym(x, 'clear')`

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#612]
As @latot has pointed out (thx!), SMT has deprecated this syntax.

I think `assume(x, 'clear')` needs to work instead (if it doesn't already).

**Comment by latot** [comment]
Hi, i clear the code and update that in this pr, https://github.com/cbm755/octsympy/pull/594

**Comment by cbm755** [comment]
@latot, re #692, we're going to need to deprecate.  This means keep `sym(x, 'clear')` but issue a warning.  Assuming we deprecate in 2.5.0, then we can remove the code probably in 2.6.0.

**Comment by cbm755** [comment]
@mtmiller can I get your advice on deprecation?

The new hotness `assume(x, 'clear')` is working.  Should we immediately deprecate `syms x clear` and `sym(x, 'clear')` so that upcoming 2.5.0 shows users a deprecation warning.  Or should I release 2.5.0 as-is and have 2.6.0 give a deprecation warning.

Possibly relevant: SMT deprecated in one of 2016a or 2016b.

Perhaps more relevant is that this `clear` stuff is quite a burden maintenance-wise (especially in `sym`) because it trolls through the `caller`'s workspace doing unspeakable things.  I suspect @latot and @genuinelucifer would like it gone ASAP. 

I lean towards minimizing maintenance burden.

**Comment by mtmiller** [comment]
@cbm755 I see no problem with putting in a deprecation warning immediately. I guess how long you leave it in there, enabled but deprecated, depends on how quickly you think people upgrade and how easy it is to adapt to the new syntax. When it's completely removed, will `sym(x, 'clear')` report an error?

**Comment by cbm755** [comment]
Thanks @mtmiller.  I filed #733 to make sure that does given an error in the future.  I will add deprecation warnings now.

**Comment by cbm755** [comment]
I've just noticed that we never documented these deprecated forms of "clear", so that suggests we do not need an very long deprecation period!
