### ISSUE TITLE
assume([x y], 'real') don't works

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#616]
Hi:

```
octave:4> assume([x y], 'real')
error: assert (isempty (asm)) failed
error: called from
    assert at line 92 column 11
    sym at line 327 column 7
    assume at line 116 column 8
```

Thx. Cya.

**Comment by cbm755** [comment]
Do you know if SMT supports this?

**Comment by mtmiller** [comment]
Someone should test to confirm, but looks like it from the [docs](https://www.mathworks.com/help/symbolic/assume.html):

> If `expr` is a vector or matrix, then `assume(expr,set)` sets an assumption that each element of `expr` belongs to `set`.

**Comment by cbm755** [comment]
might be nice for 2.5.0 to help with the deprecation of `syms x y clear`.

@latot do you have time to do a PR for this?  Or maybe @nvs-abhilash wants to try a deep-dive into our messy horrible no-good assumptions hackery.
