### ISSUE TITLE
Implement assume(x, 'clear')

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#617]
Move clear from sym to assume for SMT compat.

Thx. Cya.

**Comment by cbm755** [comment]
This is fairly urgent so we can get 2.5.0 out.

**Comment by cbm755** [comment]
@latot, did you have some code for this?  Can it be reworked into some self-contained commits?

If not, I can try to implement this.

**Comment by latot** [comment]
from sym file, just use this code with a condition:

```
        % ---------------------------------------------
        % Muck around in the caller's namespace, replacing syms
        % that match 'xstr' (a string) with the 'newx' sym.
        context = 'caller';
        S = evalin(context, 'whos');
        evalin(context, '[];');  % clear 'ans'
        for i = 1:numel(S)
          obj = evalin(context, S(i).name);
          [newobj, flag] = symreplace(obj, x, s);
          if flag, assignin(context, S(i).name, newobj); end
        end
        % ---------------------------------------------
```

where x should be the sym object.

Thx. Cya.

**Comment by cbm755** [comment]
Yes, that sounds right.  Do you have time to do a PR?  Not sure when I'll get to it :-/

**Comment by latot** [comment]
mm, only in case, i send this yesterday https://github.com/cbm755/octsympy/issues/716

**Comment by cbm755** [comment]
Thanks!  For some reason I don't get emails for *new* PRs, only changes to existing ones.  Must look into that...
