### ISSUE TITLE
assume(x) and assumeAlso(x) don't return the correct error

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#627]
Hi:

```
octave:24> assume(a)
error: 'ca' undefined near line 116 column 20
error: called from
    assume at line 116 column 8
octave:24> assumeAlso(a)
error: sym: assumption must be a string
error: called from
    assert at line 94 column 11
    sym at line 347 column 11
    assumeAlso at line 92 column 8
```

Thx. Cya.

**Comment by cbm755** [comment]
Is this supposed to:
A. do the same as `assume(x, 'clear')`
or 
B. list the assumptions on x?

**Comment by latot** [comment]
C. Return an error of not supported yet, send 1 var implies set the condition with 1 expression, ex:

```
assume(x>0)
```

**Comment by cbm755** [comment]
Ah I see.   Unlikely to be supported either, given differences in assumptions system between SymPy and MuPAD.

Yes, error message sounds good, something like "general algebraic assumptions are not supported".

**Comment by latot** [comment]
pr for this https://github.com/cbm755/octsympy/pull/724
