### ISSUE TITLE
Shared private functions need a test to be sure are equals

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#628]
Hi, like for, `magic_double_str`, exist in `/private` and `/sym/private`.

Thx. Cya.

**Comment by mtmiller** [comment]
There is no way to test private functions in Octave, and seems unlikely that there will be until someone can make a sound argument [upstream](https://savannah.gnu.org/bugs/?38776) why that would be a good idea and how to make it work robustly.

Other than "test all the things", is there a good reason for wanting to test these private functions directly instead of sufficiently testing the public functions that use them?

**Comment by latot** [comment]
Hi, its right we can't compare function by function and values, for that reason i approach this in the pr comparing the files and checking if they are equals.

Maybe i don't explain this in the right way, the idea of the issue is a test to be sure both files are equals, because when you have two copies is too easy edit one and forget the other.

Thx for your comment.

**Comment by mtmiller** [comment]
Ok, thanks, I misread the description without the context.

**Comment by genuinelucifer** [comment]
Hi @latot , actually we should not do this! I was trying to convert everything to classdef and I came across this problem.  
Ex: If `magic_double_str` in `/private` wants to call itself it can directly call using it's name `magic_double_str`. But the one in `/@sym/private` (which will be moved to `/@sym` has to call `sym.magic_double_str`!! So, I had to drop your tests for this reason for this to work properly.

**Comment by latot** [comment]
Hi, sadly i can't understand very well the problem...................
Why ```magic_double_str``` wants call it self?
Actually the code don't need it, or you have other idea in mind?

**Comment by genuinelucifer** [comment]
Sorry, `magic_double_str` seems good. You added another file in that PR `norm_logic_strings` which calls itself and caused the problem. Either it should not call itself or you could remove the 1 test which compares contents of `norm_logic_strings` in the 2 directories, or I could do it in my classdef PR.. not a big issue for now.

**Comment by latot** [comment]
mm, i think exist a better solution, just in the same function i'll make a new helper function, and we can call it self from there and avoid this problems.
