### ISSUE TITLE
None problem - char(isinf(a)) returns empty

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#632]
Hi, well this don't is the first time i get this, but for now an example:
```
octave:18> char(isinf(a))
ans = 
```
So seems this happen with None but only when is called from a function directly:
```
octave:20> char(python_cmd('return None'))
ans = None
```
```
>>> x=S("x")
>>> srepr(x.is_infinite)
'None'
```

Thx. Cya.

**Comment by latot** [comment]
Or this is configured intentionally?

**Comment by mtmiller** [comment]
In Octave, a `logical` is a numerical value just like an int or float.  `char(false)` is the same as `char(0)` or `"\0"`, and `char(true)` is the same as `char(1)` or `"\1"`. The function is returning a logical value, and the string it converts to is a single NUL byte.

If you want a function that will return a string "true" or "false", the only function I know that does that is `mat2str`. The purpose of `mat2str` is basically like Python's `repr`, to return a string that can be passed back into `eval` to construct the equivalent data structure.

**Comment by latot** [comment]
mm, thx for your explanation:
```
octave:21> char(python_cmd('return str(bool("hola"))'))
ans = True
octave:22> char(python_cmd('return str(bool(None))'))
ans = False
octave:23> char(python_cmd('return bool("hola")'))
ans = 'some weird char'
octave:24> char(python_cmd('return bool(None)'))
ans = 
```
python ```bool``` converts only None to a null char, so we get an empty expression with char.

I don't like the idea works with a empty expression in octsympy ({}, [], don't are empty), it feels can do problems, maybe if is None returns false?, and other point, as is explained in the file ```uniop_bool_helper```, None represent it can't be calculated or decided, so its confuse return 0, 0 its assumed as false, so maybe instead of use bool indiscriminately, use it only for True/False values? and other return it normally?

Thx. Cya.

**Comment by cbm755** [comment]
@mtmiller's explanation explains what's happening here.  

Rest of this looks like commentary on #57 and/or #308.  Closing.
