### ISSUE TITLE
Round inconsistent in py2/py3, sound return a symbolic Integer?

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#635]
Hi all, well this happen because round don't return a Sympy object, return an int, and for other weird reasons:

```
octave:7> a=sym([1 2])
a = (sym) [1  2]  (1×2 matrix)
octave:8> round(a)
ans = (sym) [1.0  2.0]  (1×2 matrix)
```

Now the weird things:

```
octave:9> python_cmd('return str(type(round(Integer("3"))))')
warning: called from
    python_cmd at line 186 column 5
ans = <type 'float'>
```

```
>>> str(type(round(Integer("3"))))
"<class 'int'>"
```

For some reason the returned object is different from python to octave.........

Well, Thx. Cya.

**Comment by mtmiller** [comment]
Hm? Are you sure you're comparing the right version of Python?

On my system, with Python 2.7

    >> a = sym ([1, 2])
    >> round (a)
    ans = (sym) [1.0  2.0]  (1×2 matrix)

And with Python 3.5

    >> a = sym ([1, 2])
    >> round (a)
    ans = (sym) [1  2]  (1×2 matrix)

And running the same commands in Python 2 vs 3 confirms the difference.

See also http://python3porting.com/differences.html#rounding-behavior.

**Comment by latot** [comment]
Hi, yes, i test this in octave and python 3.4, so maybe exist a difference between 3.4 and 3.5 too.

Thx. Cya.

**Comment by mtmiller** [comment]
No, rounding in Python 3.4 is the same as in 3.5. I think you're using Python 2 with Octave, can you double check that? What does `x = python_cmd("return sys.version")` give you?

I think the more interesting difference in rounding is the following.

Python 2

    >> round (sym ([2:6]) ./ 2)
    ans = (sym) [1.0  2.0  2.0  3.0  3.0]  (1×5 matrix)

Python 3

    >> round (sym ([2:6]) ./ 2)
    ans = (sym) [1  2  2  2  3]  (1×5 matrix)

Not just the types of the values, but the rounding direction has changed. I would think we want to match Octave rounding behavior, so that `round(2.5) == round(sym(2.5))` is always true.

**Comment by latot** [comment]
:O 

You are right i'm using python 2, i forgot i restart octave with python 2, i was using python 3.
I'm agree to match the behavior with octave, and we need add this to new tests.

Thx. Cya.

**Comment by cbm755** [comment]
Maybe round should call `x.round()`.  Or maybe `Rational(x.round())`.  Anyway, sympy's round, not builtin python round.  This should also give a better error for `syms x`; `round(x)`.

**Comment by cbm755** [comment]
Sorry, `Integer(x.round())` not rational.
