### ISSUE TITLE
Add travis build status / link to README

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#644]
It would be nice to have a link / status box for the most recent master travis build status on the front page (which I guess means it has to be added to README.md).

**Comment by cbm755** [comment]
I guess so, but what is benefit of such other than advertising for the CI service?  Does it increase confidence in our project or something?

**Comment by mtmiller** [comment]
My personal reason is as a bookmark, just to make it easier to get to the build status from the github project page. Maybe there is some small benefit to signaling confidence in the project status (I originally stuck it under the **Status** section header). Definitely not to advertise a proprietary CI service.

I thought it would be helpful to have a link from the main project page to the CI status page, to be able to see the current build logs (I often visually compare my local results to the CI build logs to see what I messed up). But if you'd rather I just use my own bookmark to get there, I can live with that 😉

**Comment by cbm755** [comment]
yeah ok, I guess the readme file isn't used for anything else...
