### ISSUE TITLE
`test @sym/psi` fails in Octave 4.2 (with SymPy 1.0)

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#646]
The SymPy Octave code generation fails on `psi` ↔ `polygamma` with SymPy 1.0. The test is skipped when running in Octave 4.0, because the `psi` function was not added until 4.2. There should be some check in place to prevent the round trip test from failing, maybe print a warning, if SymPy does not support this function.

    >> test @sym/psi
    ***** test
     % round trip
     if (exist ('psi','builtin'))
     syms x
     f = psi (x);
     h = function_handle (f);
     A = h (1.1);
     B = psi (1.1);
     assert (A, B)
     end
    !!!!! test failed
    function_handle: python codegen failed: polygamma(0, x)

**Comment by mtmiller** [comment]
In case it wasn't clear, with Octave 4.0.x or earlier, most tests in psi.m are skipped because Octave did not have a native `psi` function.

With Octave 4.2 and SymPy 1.0.1.dev (git master), the tests are not skipped and they do pass.

It's only with Octave 4.2 (or hg default) but still using SymPy 1.0 or older that the test fails with an error.

**Comment by cbm755** [comment]
`%!test` needs conditionals ;-)  `%!xtest if meh`.

But I think you're right.

**Comment by mtmiller** [comment]
Yeah there is a `%!testif foo` syntax, but unfortunately the set of tests is built in to Octave.

See [upstream #49507](https://savannah.gnu.org/bugs/?49507).

For now the best we can do is basically what you have now, skip the entire test body or display a warning message if feature missing.

I guess I will copy one of the SymPy version checks done in some of the other unit tests.
