### ISSUE TITLE
`test @sym/ne` fails with SymPy 1.0.1.dev (git master)

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#648]
Test passes with current release SymPy 1.0, but with SymPy git master:

    >> test @sym/ne
    ***** test
     % oo
     syms oo x
     e = oo ~= x;
     assert (isa (e, 'sym'))
     s = strtrim (disp (e, 'flat'));
     % SymPy <= 0.7.6.x will be '!=', newer gives 'Ne', test both
     assert (strcmp (s, 'oo != x') || strcmp (s, 'Ne(oo, x)'))
    !!!!! test failed
    assert (strcmp (s, 'oo != x') || strcmp (s, 'Ne(oo, x)')) failed
    >> syms oo x
    >> disp (oo ~= x, 'flat')
      True

This appears to be a change from SymPy 1.0 to the dev version:

    >>> from sympy import *
    >>> Ne (oo, Symbol ('x'))
    True

**Comment by cbm755** [comment]
I think this is upstream #10927.

**Comment by mtmiller** [comment]
Thanks for already catching this months ago and pointing to the upstream issue

**Comment by mtmiller** [comment]
Resolved upstream, closing as fixed.
