### ISSUE TITLE
regression: op_helper with empty args: `sym([]) == sym([])` should be empty 

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#650]
It was recently changed by #640.  I accidentally merged without tracking this down.

**Comment by cbm755** [comment]
Current behaviour in master:
````
octave:9> [] == []
ans = [](0x0)
octave:10> sym([]) == sym([])
ans = (sym) True
````

But previous behaviour, e.g., before merging #640, gave:
````
octave:5> sym([]) == sym([])
ans = (sym) []  (empty 0×0 matrix)
````
and in fact this was unit tested :(

**Comment by cbm755** [comment]
I think the new `op_helper` fails in some way if all (some?) args are empty.  For example, after the first loop, `q` is still the `Matrix([0])` but I guess it should be the empty matrix?

@latot, can you try to fix this and restore the removed test?

**Comment by cbm755** [comment]
This needs to work too:
````
>> sym(zeros(3,0)) == zeros(3,0)
ans = (sym) []  (empty 3×0 matrix)
````
and should be added to the tests  (it currently gives `True`)

**Comment by latot** [comment]
Hi, i'll send a patch, i'm thinking a little thing, some functions need use [] as element but others as matrix, so i need found a way to balance this.

**Comment by cbm755** [comment]
Would this help?

1.  Loop `_ins`, looking for the maximum shape.  (and check that all are same size or scalar).
2.  Create `q` after the loop, based on the maximum shape found.
