### ISSUE TITLE
Up Octave dep to 4.0.3 (and drop `bin/winwrapy.bat`)

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#654]
Sometime later when we don't want to support Octave 4.0.2, we can remove the `bin/` dir.

- [ ] update DESCRIPTION for minimum Octave
- [ ] This will also fix #231.
- [ ] In making this decision, consider the current Ubuntu LTS.

I guess this is for after 2.5.0.

**Comment by genuinelucifer** [comment]
We would probably also need to consider what octave version would completely support the new classdefs. After latot's PR is merged, I can try to finish the classdef PR and then we could check and update the dependency..

**Comment by mtmiller** [comment]
> what octave version would completely support the new classdefs

Let's try to stick with classdef features that 4.0.3 supports for now if possible?

I am hoping to have some time to work on improving classdef for 4.4, so feel free to try some features and send me bug reports. But the basics should work in 4.0.3.

**Comment by cbm755** [comment]
Unfortunately it looks to me like Ubuntu 16.04 LTS [is still 4.0.0](https://launchpad.net/ubuntu/xenial/+source/octave).

**Comment by mtmiller** [comment]
However, the [PPA](https://launchpad.net/~octave/+archive/ubuntu/stable) installs Octave 4.2.1 now for both 14.04 and 16.04.

**Comment by mtmiller** [comment]
Other than the [Windows popen2 bug](https://savannah.gnu.org/bugs/?43036), I don't see a reference here, why do you want to bump the minimum to 4.0.3?

**Comment by mtmiller** [comment]
* Ubuntu 14.04 LTS is now old but still supported - Octave 3.8.1
* Ubuntu 16.04 LTS is the current LTS - Octave 4.0.0
* Ubuntu 18.04 LTS is almost here - Octave 4.2.2
* The [PPA](https://launchpad.net/~octave/+archive/ubuntu/stable) now provides 4.2.2 for all LTS users

**Comment by cbm755** [comment]
That winwrapy.bat was a workaround for something, probably the Windows issue you link too.  I don't see a way to have a minimal version that depends on OS, so easiest for me to bump to 4.0.3 for all OSes.

**Comment by mtmiller** [comment]
Thanks. That's what the bat file said in its comments.

FWIW, I am planning on never including the patch number in dependencies for my packages. I would just declare it as `octave (>= 4.0)` and assume that the user has the latest bug-fixed version of that series. And when we go to major releases only, I would just write it as `octave (>= 5)`.
