### ISSUE TITLE
string matrix don't are passed correctly to python - only pass the first row

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#664]
Hi all:
```
octave:133> a=['a', 'b';'c', 'd'];
octave:134> python_cmd('return _ins[0]', a)
warning: number of outputs don't match, was this intentional?
warning: called from
    python_cmd at line 186 column 5
ans = ab
```
And as a note, i can confirm in ```_ins``` only exist one element, so don't exist ```_ins[1]```

Thx. Cya.

**Comment by cbm755** [comment]
Confirmed.  Your example was hard for me to understand.  Here's how I hit it:

````
>> a = ['abc'; 'defg']
a =

abc 
defg

>> q = python_cmd('dbout(_ins); return _ins[0]', a)
pydebug: ['abc ']
q = abc 

>> q = python_cmd('dbout(_ins); return _ins[1]', a)
pydebug: ['abc ']
error: Python exception: IndexError: list index out of range
    occurred at line 1 of the Python code block
error: called from
    python_cmd at line 174 column 5
````

Maybe we should just assert that strings are 1D in the IPC code.

**Comment by mtmiller** [comment]
Just for a perspective, there are quite a few places in Octave code where a multi-dimensional char matrix is truncated to a single row and treated as a string.

    >> s = ['hello'; 'world'];
    >> fputs (stdout, s);
    hello
    >> fprintf (stdout, s);
    hello
    >> error (s)
    error: hello
    >> warning (s)
    warning: hello
    >> struct (s, 12)
    ans =
    
      scalar structure containing the fields:
    
        hello =  12
    
IMHO it's entirely acceptable to follow this pattern and allow char matrices to be truncated to their first row when they are used in a context where the concept of a "string" is expected.

**Comment by cbm755** [comment]
That is scary.  Silent data loss, no warning :(

I think I *want something* in place, especially given the current fragile IPC: otherwise its undefined and some worse behaviour might be possible.

But maybe that *something* could just be a unit test: testing that the first row is passed and subsequent rows just disappear.

**Comment by cbm755** [comment]
I guess you probably know, but Matlab's behaviour is different:
````
>> s = ['abc'; '123']
s =
abc
123
>> error(s)
??? a1b2c3
 ````

I'm sorry for the attitude: I actually thought Matlab forbid these things altogether (it doesn't seem to autopad to longer row, instead giving an error)

**Comment by mtmiller** [comment]
Yeah I know Matlab supports char arrays, but I don't know how different their behavior is in various functions that expect a string like system, warning, error, sprintf, struct.

They do document this form, which is compatible between Octave and Matlab (pads with trailing spaces)

    >> s = char ('one', 'two', 'three', 'this is a long string')
    s =
    one                  
    two                  
    three                
    this is a long string

Same applies to `char ({'a', 'b', 'something'})`. And converting from a char array to a cell array of strings automatically deletes trailing whitespace. All of these constructions and conversions are documented and compatible, I'm just not sure if Matlab _always_ flattens a char array when it expects to get a string, whether it ever truncates like Octave does, or if there is ever a case where it may actually throw a warning or error. Ad hoc maybe.

**Comment by mtmiller** [comment]
I also debugged a little and found that `undo_string_escapes` is basically the point where the char array is truncated to a char row vector in octsympy (python_copy_vars_to.m line 60).

So this is just one example of many that expects a 1-D string and that's what it returns, truncating if it gets more than that.

OTOH `sym(['ab'; 'cd'])` returns a sym variable named 'acbd'.

**Comment by mtmiller** [comment]
I see a FIXME, so I'm going to raise this upstream, should make a nice goal for 4.4.

**Comment by mtmiller** [comment]
Reported upstream, see [bug #49536](https://savannah.gnu.org/bugs/?49536). Feel free to add details or comments there. It's good that you're adding a test to at least capture the current behavior, and maybe something will change in a future version.
