### ISSUE TITLE
Allow sympref to take settings from a scalar struct argument

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#668]
Feature request:

    >> old = sympref ();
    >> sympref ...
    %% run some code
    %% now restore all settings
    >> sympref (old);

Basically iterate through all key-value pairs in the struct and set them.

**Comment by cbm755** [comment]
Sounds reasonable.  I think SMT recently added a `sympref` command: [looks like their's does that](http://www.mathworks.com/help/symbolic/sympref.html).
