### ISSUE TITLE
Hurwitz Zeta function

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#678]
Hi all, well i think we can improve this, the proposed new format can be:

```
zeta(z, n, h)
```

Where the arguments for the zeta function are ```n``` and ```h```

Thx. Cya.

**Comment by cbm755** [comment]
Oops, I forgot about this and filed #891.   I'll close that in favour of this.

In Mathworks SMT, zeta does `zeta(x)` and `zeta(n,x)`.  **We should keep that ordering.**  (I think Maple also has this ordering for the derivatives).

Re: three inputs: is that the "Lerch transcendent"?  If so, that is `sympy.functions.special.lerchphi` in Sympy.  I'd prefer not to overload `zeta.m` to do that.

**Comment by cbm755** [comment]
Oops, should've re-read the whole thread...  will update later.
