### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#686]
Hi all, well thinking a little for example with snippets, i think can be useful have a debug mode for this, for example to print the data in display like snippet but with an easy code, this i think only will use some lines, other point is actually when we have errors the python line code is printed, this is very useful but we want expose python code for the user?

So in my opinion i would like have this two features:

 - Print srepr in display
 - Python code line error move to here

What do you think?, someone have and idea can be useful? like a feature or something?

Thx. Cya.

**Comment by cbm755** [comment]
1.  If not one was using "snippet" before, why they are going to start using this new debug mode?  See PR #687: maybe this is enough?

2.  When things go wrong in interpreted languages, a scary looking stack trace is fairly normal.  So I think our current behaviour (quoting the line of Python code) is consistent with Octave.

**Comment by latot** [comment]
Okis, so only to confirm, if we need/found other ways to get debug data we will improve it directly?

**Comment by cbm755** [comment]
Sorry I don't understand what you mean.  I don't mind the idea of having a debugging mode, but currently we have no debugging features.

**Comment by latot** [comment]
Okis, i misread your intentions, so lets keep this open?, or close and re-open when we need it?

**Comment by cbm755** [comment]
Let's close for now.
