### ISSUE TITLE
Python error line reporting should be more robust

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#688]
IIRC, recently-added code does some calculations and then indexes into `cmd` based on `cmdlineerrno`.  There should be some basic sanity checks here in case that index is out-of-range.

Otherwise, its annoying when the error reporting code itself fails with errors.

**Comment by latot** [comment]
mm, errcmdlineno and errlineno use the python lines, and cmd will always get > 0 lines, so the only case i can think is when python send the wrong line number....., and in that case we can't do something.....

**Comment by cbm755** [comment]
Well we can give a message like "something has gone wrong: cannot identify line number" while still reporting the python error.  I just want to avoid the case where there is some unexpected bug *we* haven't thought of and the user get's "index out of bounds" instead of the error from Python.
