### ISSUE TITLE
Deprecate `octsympy_tests`, or at least use Octave tools

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#696]
I'd like to deprecate and then remove `octsympy_tests`.  I think its a fork of `__run_test_suite__` that I put in place to support some old Octave that we no longer support.  Let's trim it down, calling standard Octave tools instead.  Perhaps we can even remove it altogether if the standard tools are good enough.

CC @mtmiller as I think he's interested in such things in core.

**Comment by cbm755** [comment]
I had various concerns about the `runtests`, `test` and `__run_test_suite__` tools in core Octave.  I'll try to document them here.

This works:
````
>> __run_test_suite__ ({'@double'}, {})
````

These fail on Octave 4.3.0+ (hg tip from few weeks ago):
````
>> [pass, fail, xfail, skip] = __run_test_suite__ ({'@double'}, {})
---- 8< ----
error: 'np' undefined near line 125 column 12
error: called from
    __run_test_suite__ at line 125 column 10

>> [pass, fail, xfail, skip] = __run_test_suite__ ({'@symfun'}, {})
---- 8< ----
=: nonconformant arguments (op1 is 1x1, op2 is 1x16)
error: 'np' undefined near line 125 column 12
error: called from
    __run_test_suite__ at line 125 column 10

>> __run_test_suite__ ({'@symfun'}, {})
---- 8< ----
=: nonconformant arguments (op1 is 1x1, op2 is 1x16)
````

On Octave 4.0.3, the `@symfun` one fails with `A(I) = X: X must have the same size as I` instead.  And the return argument examples fail with `error: element number 1 undefined in return list`.

**Comment by cbm755** [comment]
1.  the "`np` undefined" looks like an easy fix upstream.  I will prepare a patch.  I guess no one is using the return values of `__run_test_suite`!
2.  The "nonconformant argument" is trickier: it happens b/c some tests do "clear".  This happens within a function.  But it also clears global variables.  `__run_test_suite__` uses some global variables.
3.  There is `try`, `unwind` stuff in there.  That can occur and then `nfail` is never set, causing an error.

**Comment by cbm755** [comment]
1.  patch sent upstream: https://savannah.gnu.org/patch/?9251
2.  worked around by using "clear variables" instead of "clear".
3.  not reported upstream yet.

**Comment by mtmiller** [comment]
These now work fine for me with git master and Octave 4.2.1 or dev

    >> [pass, fail, xfail, skip] = __run_test_suite__ ({'@double'}, {})
    
    …
    pass =  60
    fail = 0
    xfail =  1
    skip = 0
    >> [pass, fail, xfail, skip] = __run_test_suite__ ({'@symfun'}, {})
    
    …
    pass =  86
    fail = 0
    xfail = 0
    skip = 0

Since 1 is fixed upstream, 2 is worked around, do you have a test case where 3 happens?

**Comment by cbm755** [comment]
@mtmiller, I filed https://savannah.gnu.org/bugs/?51660 with one trivial way to hit 3.  Not sure if this is important or not but don't want lose it if this particular issue gets closed.
