### ISSUE TITLE
[maint] [CI] use a specific version of octave-doctest

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#697]
Can we *easily* specify a special version of `octave-doctest`?  Otherwise I have to carefully coordinate doctest releases with changes to our CI (which is impossible because someone else has to actually formally make the sourceforge releases). This caused some trouble yesterday.

Maybe we should just pull the tarball we want to use instead of calling `pkg install -forge doctest`.

**Comment by mtmiller** [comment]
Or clone the GitHub repo and pin it to a particular tag or commit?

**Comment by mtmiller** [comment]
Using `--path` instead of `pkg install` / `pkg load`?
