### ISSUE TITLE
simplify makes immutable matrices, can't be concatenated

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#700]
Immutable matrices are annoying, cause trouble for vertcat for example:

````
>> syms x
>> A = [x; x];
>> B = simplify(A);
>> char(A)
ans = MutableDenseMatrix([[Symbol('x')], [Symbol('x')]])
>> char(B)
ans = ImmutableMatrix([[Symbol('x')], [Symbol('x')]])
>> 
>> [A; x]
ans = (sym 3×1 matrix)

  ⎡x⎤
  ⎢ ⎥
  ⎢x⎥
  ⎢ ⎥
  ⎣x⎦

>> [B; x]
error: Python exception: TypeError: unbound method col_join() must be called with MutableDenseMatrix instance as first argument (got ImmutableMatrix instance instead)
    occurred at line 10 of the Python code block
error: called from
    python_cmd at line 176 column 5
    vertcat at line 63 column 5

````

Strangely, `B` can be assigned too, maybe we have a special check in place...

````
>> A(2) = 7
A = (sym 2×1 matrix)

  ⎡x⎤
  ⎢ ⎥
  ⎣7⎦

>> B(2) = 7
B = (sym 2×1 matrix)

  ⎡x⎤
  ⎢ ⎥
  ⎣7⎦

>> char(B)
ans = MutableDenseMatrix([[Symbol('x')], [Integer(7)]])
````

**Comment by latot** [comment]
mmmm, maybe this can be changes from upstream instead?

**Comment by cbm755** [comment]
Yes it might be.  Can you narrow down the sympy behaviour we are relying on here?  Then we can decide if its a valid upstream bug, or whether we are doing something wrong with an ImmutableMatrix.

**Comment by latot** [comment]
Hi, i check that, simplify returns a inmutable object from sympy (python), so i think don't is a octsympy problem, but i think we will need use a patch to cover this at least for now.

**Comment by cbm755** [comment]
I think it might be an upstream problem.  But I think we can workaround by calling `MatrixBase.vstack` instead of `Matrix.vstack` and same in `horzcat`.

**Comment by latot** [comment]
mm, i think we can instead change the concatenation function we can change the simplify function to return a mutable object instead, keep inmutable object can have other hidden problems.

**Comment by cbm755** [comment]
Perhaps, but hard to guarantee there isn't *some* Immutable object around coming from some other function.

I filed upstream as: https://github.com/sympy/sympy/issues/11944, wiht some proposed upstream fixes.

I think we could/should do the `MatrixBase` thing here; its not wrong and will work around the problem independent of what upstream does.

**Comment by cbm755** [comment]
You could file a separate issues for having our `simplify` return MutableMatrix (note *our simplify* **not** upstream's `sympify`; similar spelling, *very* different methods).
