### ISSUE TITLE
subsasgn: add test for 2D array input

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#702]
While reviewing #690, I wondered about this test:

````
%!test
%! % indexing with a smaller 2-dimensional array
%! b = eye (3);
%! a = sym (b);
%! I = [2 3; 4 5];
%! a(I) = -2*I;
%! b(I) = -2*I;
%! assert (isequal (a, sym (b)));
%! assert (size (a), [3 3]);
````

I think it failed before #690 with an error, maybe it passes now.

**Comment by cbm755** [comment]
@genuinelucifer this seems to work now.  Do you think it needs a test or is this case already covered by your recent changes from #710?

**Comment by genuinelucifer** [comment]
Well, there are tests where the index matrix is smaller as compared to the matrices being indexed. So, I think this is covered.

**Comment by cbm755** [comment]
ok thanks, so the above test could be added to `@sym/subsasgn`: easy fix.
