### ISSUE TITLE
Passing sympy code to sym should be idempotent in most cases

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#706]
@latot's sym rewrite changes some things.  Here's one I don't like:
````
>> sym('Float("1.23")')
123/100
````
I think the "rational=true" thing added in #704 might be too aggressive; perhaps it should be done only if `x` actually looks like a number.

**Comment by latot** [comment]
mm, is a nice point, personally, only in priorities, i think octsympy is normally used for high precision work, so i think i very improbable someone wanna use float (for the context), i'm not saying we should forget this, only set the priority the normal use of octsympy. (note, even if i say this as normal use, is only a conclusion of what i read about the project with others, if i'm wrong with this please tell me)

Now out of what i wrote, i'm agree that need a solution, but i think disable rational will produce more work than try solve only the float function, so imagining a solution, maybe extract the float function from the expression and replace it with dummy, the eval it normally, and to finish, replace the dummy with the eval of the original float.

**Comment by cbm755** [comment]
I think you're right about the symbolic and high-precision use-case.

Our docs suggest this example should work: "The underlying SymPy string representation can also be passed directly to sym".

How about we use the "rational=true" thing if the input matches a regexp for a number?  In particular, no `(` or `)`.  Do you have an example where that will give an undesirable result?

**Comment by latot** [comment]
mmm, i think is nice, and this i think will be solved when we can implement this objetive https://github.com/cbm755/octsympy/issues/625, or maybe we can just disable sooner as expected that feature and finish that part, anyway for now i think is a nice solution.

Note, mm, re-thinking a little, maybe instead search (), search some pattern with a expression followed with () like, "f2(" "h(" and similars, you know, search function pattern, and in the future i think we can simplify it again..

And to complement this, in the issue i show above we should add to the warning, octsympy will can't transform to rational the expression if it have a mix of fraction and functions.

Thx. Cya.

**Comment by cbm755** [comment]
I think I agree re: #625 but that might a while in the future.

But maybe we should change the *documentation* in `sym` now in case we don't want to support `sym(<sympy code>)` in the future.  We could still have it working but maybe should not be advertising it...
