### ISSUE TITLE
Check access to matrix with symbolic index

### ISSUE THREAD

**Issue by latot** [cbm755/octsympy#711]
Hi all, similar to previous issues, but check if this works properly when we send a symbolic index matrix.

**Comment by cbm755** [comment]
Can you give an example?  Or reference a previous comment.

I guess this is intended for @genuinelucifer

**Comment by genuinelucifer** [comment]
I think this will be fixed with the PR #710 because as far as I can see all other cases except boolean give the desired indexing.
