### ISSUE TITLE
Should we keep the warnings in subsref and subsasgn?

### ISSUE THREAD

**Issue by genuinelucifer** [cbm755/octsympy#714]
Currently we are giving warning for some probable errors which are not given by the `double` class.  
Examples:
```
>> % subsref
>> b = [1:4]; b = [b; 3*b; 5*b];
>> a= sym(b);
>> a([false false]);
warning: A and I in A(I) not same shape: no problem, but did you intend this?
warning: called from
    mat_access at line 37 column 7
    subsref at line 69 column 11
>> b([false false]);
>>
```
```
>> % subsasgn
>> b = [1:4]; b = [b; 3*b; 5*b];
>> a = sym(b);
>> I = logical([1 0 1 0; 0 1 0 1; 1 0 1 0]);
>> rhs = 2*b(I);
>> rhs2 = reshape(rhs, 2, 3);
>> a(I) = rhs2;
warning: B neither vector nor scalar in indexed A(I)=B: unusual, did you intend this?
warning: called from
    mat_replace at line 40 column 7
    subsasgn at line 100 column 13
>> b(I) = rhs2;
>>
```

**Comment by latot** [comment]
Hi, my vote is drop the warnings, octave don't send it in the same context, maybe check matlab too?

**Comment by genuinelucifer** [comment]
I checked in Matlab R2016a and it doesn't give any warnings.

**Comment by cbm755** [comment]
FTR: I'm not a fan of magical broadcasting: just hides bugs and unclear thinking IMHO.  But I agree we should respect upstream Octave's point of view.

So I'll accept a PR for this.  Also some tests should simplify because of it.

**Comment by nvs-abhilash** [comment]
@cbm755 can I take work on this issue?

**Comment by cbm755** [comment]
Sure, @genuinelucifer can probably review and help if needed

**Comment by genuinelucifer** [comment]
Surely. Go ahead.

**Comment by nvs-abhilash** [comment]
Ok, I am working on it.
