### ISSUE TITLE
non-deterministic test failures (again)

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#735]
Deja vu, but I'm seeing non-deterministic test failures from `@sym/subsref`:

````
>>>>> processing @sym/subsref.m

***** test

 % 1D arrays, does right with despite warning

 r = [1:6];

 ar = sym(r);

 c = r';

 ac = sym(c);

 Ir = rand(size(r)) > 0.5;

 Ic = rand(size(c)) > 0.5;

 assert (isequal (ar(Ir), r(Ir)))

 assert (isequal (ac(Ic), c(Ic)))

 s = warning ('off', 'OctSymPy:subsref:index_matrix_not_same_shape');

 assert (isequal (ar(Ic), r(Ic)))

 assert (isequal (ac(Ir), c(Ir)))

 warning (s)

!!!!! test failed

assert (isequal (ac (Ir), c (Ir))) failed
````
Last time, this was caused by `rand` choosing some "corner case" (e.g., such as all true or all false).  Maybe @nvs-abhilash (or someone else) feels like playing detective to track this down to a simpler case?

**Comment by cbm755** [comment]
See #397 for last time.  Maybe @MarcoFalke is still interested too?

**Comment by cbm755** [comment]
Its possible this is indicative of some regression from recent changes to indexing so milestoning for 2.5.0 (if it turns out not to be a regression from 2.4.0 then I don't care if its fixed now or later).

**Comment by nvs-abhilash** [comment]
I hope it's not due to my contributions, is it?

**Comment by mtmiller** [comment]
If `Ir` is a 1×6 `false` row vector:

    >> assert (isequal (ac(Ir), c(Ir)))
    error: assert (isequal (ac (Ir), c (Ir))) failed
    error: called from
        assert at line 92 column 11
    >> ac(Ir)
    >> ac(Ir)
    ans = (sym) []  (empty 1×0 matrix)
    >> c(Ir)
    ans = [](0x1)

And the equivalent error if `Ic` is a 6×1 `false` column vector.

And yes this is a regression from 2.4.0.

**Comment by mtmiller** [comment]
In 2.4.0, `ac(false(1,6))` yields `(sym) []  (empty 0×1 matrix)`. On master, it's `(sym) []  (empty 1×0 matrix)`.

**Comment by cbm755** [comment]
> I hope it's not due to my contributions, is it?

Probably not, `git bisect` can be used to track down which commit caused a regression.  This is likely related to the remove of `private/mat_mask_asgn`.

**Comment by mtmiller** [comment]
Bisected to 47952239.

**Comment by cbm755** [comment]
> I hope it's not due to my contributions, is it?

And even if it was, its just about finding and fixing.  Any joking about throwing sticks at **cough, cough** @genuinelucifer is just for giggles.

**Comment by nvs-abhilash** [comment]
`git bisect` is indeed a very useful tool.

**Comment by mtmiller** [comment]
Not that I understand this fully, but here's what I see empirically with logical indexing of Octave arrays (leaving syms alone for now).

If `x` is a row vector

    >> x = rand (1, 10);
    >> x(false)
    ans = [](0x0)
    >> x(false (1, 3))
    ans = [](1x0)
    >> x(false (3, 1))
    ans = [](1x0)

If `x` is a column vector

    >> x = rand (10, 1);
    >> x(false)
    ans = [](0x0)
    >> x(false (1, 3))
    ans = [](0x1)
    >> x(false (3, 1))
    ans = [](0x1)

If `x` is a matrix

    >> x = rand (10, 10);
    >> x(false)
    ans = [](0x0)
    >> x(false (1, 3))
    ans = [](1x0)
    >> x(false (3, 1))
    ans = [](0x1)

The tests added in 4795223 only test against a matrix. Some more tests should be added there for both row and column vectors, where the singleton dimension of the vector, not of the indexing array, is what determines the size of the result.
