### ISSUE TITLE
Inconsistent floating point precision in symbolic package

### ISSUE THREAD

**Issue by przemekklosowski** [cbm755/octsympy#762]
The symbolic package does variable precision arithmetic, but is pretty inconsistent. vpa(pi,..) can give arbitrary number of digits of pi, but vpa(pi/2,..) only calculates 50 digits followed by zeros, and in actuality only first 16 digits are even accurate. Other constants like 'e' are approximated crudely by fractions, with something like 8-9 significant digits. 
I have several suggestions.
 First, use at least double precision in the rational approximations to 'regular' floating point numbers. This should be as easy as using rats(..., 16) instead of rats(...) when converting such numbers in the symbolic package.
Second, rephrase the warning about rational approximations, to explicitly warn that the precision from the rational approximation is at most 16 digits
Third, and most tricky, avoid producing spurious digits (e.g. digits 17-50 in the output of vpa(pi/2,50)),

**Comment by cbm755** [comment]
Thanks for filing this.  Some of this we sorted out on the mailling list.  Here's a summary:

1.  `vpa(pi, 100)` is magic.  Most other doubles such as `vpa(pi/2, 100)` are going to give only 15 digits plus 85 digits of pseudorandom nonsense.
2.  `vpa(e, 100)` might gain that kind of magic, that is #591.
3.  "This should be as easy as using rats(..., 16)".  First of all, note this is about `sym(...)` not vpa (vpa shouldn't be using rats, if it is, that's a bug).  Second, I don't think that 16 does what you think: `help rats` says it refers to the *length of the resulting string*.  I've filed #763 for this.
4.  "rephrase the rats warning": good idea, I've filed #764.
5.  "Third, and most tricky, avoid producing spurious digits".   `vpa(d, 50)` is impossible where `d` is some double.  If the input is provided as `vpa(1/3, 50)` or `vpa(pi/2, 50)`, it is possible using `argn`.  This is #497.  I'm undecided if its dangerous b/c it encourages this sort of sloppiness or if its helpful ;-)  I'd be happy for further discussion on this particular topic to be continued at #497.

I think that addresses you comments; re-open if I've missed something.
