### ISSUE TITLE
Cannot create abstract @symfun object using Pytave IPC

### ISSUE THREAD

**Issue by nvs-abhilash** [cbm755/octsympy#769]
After a small discussion [here](http://octave.1599824.n4.nabble.com/Error-creating-abstract-Symfun-in-Sybolic-Package-with-Pytave-td4682380.html) it was clear that this code is generating error:

```
sympref ipc native
sym f(x)
```

The above code generates the following error:
```
error: pyexec: error in return value type conversion
error: called from
    subsref at line 58 column 9
    subsref at line 56 column 7
    check_and_convert at line 46 column 5
    python_ipc_native at line 104 column 5
    python_ipc_driver at line 55 column 13
    python_cmd at line 164 column 9
    sym at line 396 column 19
```
Also, there are many tests failing when native IPC is used. This i what I got when I ran `octsympy_tests`:
```
Summary:

  PASS      2061
  FAIL        47
  XFAIL       33
  TIME      467s (422s CPU)
```
And I guess these fails are due to above error.

**Comment by mtmiller** [comment]
This is now resolved upstream, 46 of the 47 test failures are resolved with this fix.

**Comment by cbm755** [comment]
thank you both!
