### ISSUE TITLE
IPC differences: int return types converted to Octave

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#772]
The following difference remains between the default `popen2` ipc and the `native` ipc:

    >> sympref ipc popen2
    >> x = python_cmd ('return 42');
    >> sympref ipc native
    >> y = python_cmd ('return 42');
    >> x
    x =  42
    >> y
    y = 42
    >> class (x)
    ans = double
    >> class (y)
    ans = int64

Looks like the `popen2` ipc method converts any Python `int` type to an Octave double, regardless of precision overflow, while the `native` ipc method converts Python `int` objects to Octave int64.

This results in a test failure with `test python_cmd`:

    !!!!! test failed
    ASSERT errors for:  assert (q,1)
    
      Location  |  Observed  |  Expected  |  Reason
         ()           O            E         Class int64 != double

I suggest these should be made to agree, we just have to decide what the conversion should be to be consistent.

**Comment by mtmiller** [comment]
As a followup, there are also differences between Python 2 and 3 with the `popen2` ipc driver

_Python 2:_

    >> setenv PYTHON python2
    >> sympref ipc popen2
    Resetting the communication mechanism
    Forcing the popen2() communication mechanism
    >> x = python_cmd ('return 2'); class (x)
    ans = double
    >> x = python_cmd ('return 2**32'); class (x)
    ans = double
    >> x = python_cmd ('return 2**64'); class (x)
    Traceback (most recent call last):
      File "<stdin>", line 2, in <module>
      File "<stdin>", line 12, in octoutput_drv
      File "<stdin>", line 99, in octoutput
    ValueError: octoutput does not know how to export type <type 'long'>
    error: Python exception: ValueError: octoutput does not know how to export type <type 'long'>
        occurred while copying variables from Python.
        Consider filing an issue at https://github.com/cbm755/octsympy/issues
    error: called from
        python_cmd at line 184 column 5

_Python 3:_

    >> setenv PYTHON python3
    >> sympref ipc popen2
    Resetting the communication mechanism
    Forcing the popen2() communication mechanism
    >> x = python_cmd ('return 2'); class (x)
    ans = double
    >> x = python_cmd ('return 2**32'); class (x)
    ans = double
    >> x = python_cmd ('return 2**64'); class (x)
    ans = double
    >> x = python_cmd ('return 2**128'); class (x)
    ans = double

**Comment by cbm755** [comment]
Probably `popen2` should be modified to return `int64` like pytave does.

I also notice a warning about `long` when pytave uses Python 2:
````
octave:144> py.sys.version
ans = [Python object of type str]

  2.7.13 (default, Jan 12 2017, 17:59:37) 
  [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

octave:145> y = python_cmd('return 7*_ins[0]', int64(6))
x = [Python object of type long]

  42

warning: something was not converted from pyobject
warning: called from
    check_and_convert at line 66 column 7
    python_ipc_native at line 104 column 5
    python_ipc_driver at line 55 column 13
    python_cmd at line 164 column 9
y = [Python object of type long]

  42

octave:146> 
````

**Comment by mtmiller** [comment]
Right, so here is the logic used by pytave (and by Matlab):

_Python 2_

    >> class (py.int (2))
    ans = int64
    >> class (py.int (2**100))
    ans = py.long

_Python 3_

    >> class (py.int (2))
    ans = py.int
    >> class (py.int (2**100))
    ans = py.int

Both conversions that octsympy is using now have flaws. I'm not sure whether it's better to add a test of the value to see whether it can be converted (may add some overhead, maybe try it and profile it?), or to convert to double unconditionally and take the hit on loss of dynamic range for large values.

**Comment by mtmiller** [comment]
I'm thinking we don't want to leak the implementation, right? Outside of the ipc functions, no octsympy code should have to deal with py objects, so we have to convert Python long integers to something. So either have a range assert or convert to double unconditionally? Other options?

**Comment by cbm755** [comment]
I agree about leaking implementation, at least for now.  That can be revisited once pytave is the dominant/only ipc.

I've done PR #774 to try to address this.

**Comment by mtmiller** [comment]
This is resolved now right?

**Comment by cbm755** [comment]
yes, thanks.  (I forgot to put Fixes #xyz in a commit)
