### ISSUE TITLE
How to convert from symbolic matrix to regular matrix?

### ISSUE THREAD

**Issue by DanielMartensson** [cbm755/octsympy#781]
Hello!

I wonder if it's possible to convert from symbolic matrix to regular matrix, in symbolic package?
Beacuse some times I need to use regular matrices who are computed from the symbolic package.

Haven't found a function for that.

**Comment by mtmiller** [comment]
Do you mean converting a symbolic matrix of numbers to an Octave numeric value? Like this?

    >> x
    x = (sym 4×4 matrix)
    
      ⎡16  2   3   13⎤
      ⎢              ⎥
      ⎢5   11  10  8 ⎥
      ⎢              ⎥
      ⎢9   7   6   12⎥
      ⎢              ⎥
      ⎣4   14  15  1 ⎦
    
    >> y = double (x)
    y =
    
       16    2    3   13
        5   11   10    8
        9    7    6   12
        4   14   15    1
    
If you mean something else, can you give an example of what you have and what you want to convert it to?

**Comment by DanielMartensson** [comment]
Thank you! That solves my problem!

**Comment by mtmiller** [comment]
@DanielMartensson Great, can you click on the _Close issue_ button if this is resolved for you?
