### ISSUE TITLE
tests of @sym/solve rely on arbitrary order of solution vector

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#785]
Both the unit tests and doc tests of the @sym/solve.m function rely on an arbitrary order to the solution set. If the solution set is returned in reverse order, the test fails. For example, running the tests in PyPy 5.7.0, I get

    >>>>> processing @sym/solve
    ***** test
     % Multiple outputs with multiple solns
     syms x y
     [X, Y] = solve(x*x == 4, x == 2*y);
     assert (isequal (X, [2; -2]))
     assert (isequal (Y, [1; -1]))
    !!!!! test failed
    assert (isequal (X, [2; -2])) failed
    shared variables   scalar structure containing the fields:
    
        x =
    
          <class sym>
    
        y =
    
          <class sym>
    
        e =
    
          <class sym>
    
    ***** test
     % Multiple outputs with multiple solns, specify vars
     syms x y
     [X, Y] = solve(x*x == 4, x == 2*y, x, y);
     assert (isequal (X, [2; -2]))
     assert (isequal (Y, [1; -1]))
    !!!!! test failed
    assert (isequal (X, [2; -2])) failed
    shared variables   scalar structure containing the fields:
    
        x =
    
          <class sym>
    
        y =
    
          <class sym>
    
        e =
    
          <class sym>
    

The solution may be `X = [2; -2]` and `Y = [1; -1]`, but running under PyPy the solution comes out as `X = [-2; 2]` and `Y = [-1; 1]`.

Could use `sort(X)` and `sort(Y)` to ensure a consistent ordering. That loses information about which element of X goes with which element of Y, so it becomes harder to understand for future test editors. Other ideas?

**Comment by cbm755** [comment]
I suspect there are other non-deterministic tests like this but I think I fixed the ones you found.
