### ISSUE TITLE
"multirow char array" error message agreement with pytave conversion

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#789]
@cbm755 I didn't realize at the time of #778 that the error messages had to agree between the two projects to make the unit test function catch the right message.

Since then I rewrote all of the error handling in pytave to raise more accurate error messages and tested it all there, only to find when I tested octsympy with my latest that the message I went with doesn't match your error regex.

One option would be to change the error pattern to only look for "multirow char array", since we at least use that terminology in common.

I tried to make my error messages consistent with the phrasing that Octave uses, which mostly looks like

    error: invalid conversion from foo to bar

and sometimes looks like

    error: unable to convert foo to bar

**Comment by cbm755** [comment]
Not a problem, I was looking out for this: I will adjust the octsympy errors and/or the regex
