### ISSUE TITLE
NotImplementedError when solving equations with "norm(v)"

### ISSUE THREAD

**Issue by tly000** [cbm755/octsympy#790]
This small script should find the circle with radius 3 that touches P1 and P2:

```octave
P1 = sym([1; 1.2]);
P2 = sym([0; 3.2]);
C = sym('C',[2 1]);

E1 = norm(P1 - C) == 3;
E2 = norm(P2 - C) == 3;

S = solve(E1,E2)
```

The output error is:
```
error: Python exception: NotImplementedError: solving Abs(C21 - 6/5) when the argument is not real or imaginary.
    occurred at line 7 of the Python code block:
    d = sp.solve(eqs, *symbols, dict=True)
error: called from
    python_cmd at line 179 column 7
    solve at line 130 column 9
    symbolicSolve at line 15 column 3
```

I can easily fix the error by implementing my own `symNorm` like that:
```
function n = symNorm(V)
  n = sqrt(V.' * V);
end
```

**Comment by mtmiller** [comment]
If the values `C` are real, then try

    assume(C, 'real')
    E1 = ...
    E2 = ...
    S = solve(E1, E2)

With the “real” assumption factored in, it works for me.

Without that assumption added, then `norm(x)` is not the same thing as `sqrt(x.'*x)`.

**Comment by tly000** [comment]
Ah thanks, I havent thought about complex values. So this is not a bug afterall, sorry for the confusion :)
