### ISSUE TITLE
Revise the pytave branch

### ISSUE THREAD

**Issue by genuinelucifer** [cbm755/octsympy#791]
Pytave can now be successfully built and installed on windows. It runs smoothly on cli version of octave. On gui it causes crash.  
I tried to use pytave IPC on symbolic but found that all the pytave code is on another branch which too old. And pytave has evolved which needs to be incorporated too (example: using new py.* syntax and strings are now kept as python strings). The old branch gives errors when used with new pytave.  
We should probably polish the old branch to incoporate the new pytave changes and also maybe include it in master branch so that users may switch to pytave even when using master branch. [definitely not make it default but atleast provide an option]. I can start some work in this regard today..

**Comment by cbm755** [comment]
summary from mailing list: pytave branch is no more, use `sympref ipc native`.

Closing for now, reopen if I missed something important.
