### ISSUE TITLE
[maint] run CI tests on pytave

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#793]
@mtmiller do recent changes to pytave make this do-able?  No hurry, just wanted to have an issue number for it.

**Comment by mtmiller** [comment]
Yes I think so. All tests now pass for me locally. It would have to be against `OCT=daily` (at least until we have a 4.2 apt installable).

**Comment by mtmiller** [comment]
Hmm, see also #461

**Comment by mtmiller** [comment]
And to clarify, yes pytave does build and run against the gcc and pythons that are available in Ubuntu 14.04 that Travis CI currently targets. I'm using 14.04 in pytave CI as well.

**Comment by cbm755** [comment]
Fixed by f94f0f10933bc4c9aecf8e0ef8b07375f347546e (#801).
