### ISSUE TITLE
sympref tests failing on windows

### ISSUE THREAD

**Issue by genuinelucifer** [cbm755/octsympy#795]
8 tests in sympref.m fail on windows.  
Output of `test sympref verbose`:  
```
octave:4> test sympref verbose
>>>>> D:\repos\octsympy\inst\sympref.m
***** shared sympref_orig
 sympref_orig = sympref ();
***** test
 % test quiet, side effect of making following tests a bit less noisy!
 sympref quiet on
 a = sympref('quiet');
 assert(a == 1)
***** error <line 1> python_cmd('raise ValueError');
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 22] Invalid argument: 'D:\repos\\octsympy\\inst\\private\\python_header.py'
status =  1
out =
ind = [](0x0)
!!!!! error failed.
Expected <line 1>, but got <sysoneline ipc: system() call failed!>
```
  
Also, the IPC is not restored when the tests fail!

**Comment by cbm755** [comment]
Can you try the following?
````
sympref ipc system
python_cmd('raise ValueError')
````

I thought I tested this on a windows box before or soon after the last release (but I only have sporadic access so I might not have).

Does it happen with 2.5.0 and stable Octave?  I probably only tested the "bundle" package.

**Comment by genuinelucifer** [comment]
on using system ipc, the system call is failing on windows:
```
octave:3> python_cmd('raise ValueError')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 22] Invalid argument: 'D:\repos\\octsympy\\inst\\private\\python_header.py'
OctSymPy v2.5.1-dev: this is free software without warranty, see source.
Using system()-based communication with Python [sysoneline].
Warning: this will be *SLOW*.  Every round-trip involves executing a
new Python process and many operations involve several round-trips.
Warning: "sysoneline" will fail when using very long expressions.
status =  1
out =
ind = [](0x0)
error: sysoneline ipc: system() call failed!
error: called from
    python_ipc_sysoneline at line 141 column 5
    python_ipc_driver at line 62 column 15
    python_cmd at line 164 column 9
```

**Comment by genuinelucifer** [comment]
I tried the same with release 2.5 of symbolic and octave 4.2.0 as well as 4.2.1 (both stable releases) and the error occurs on both octave versions.

**Comment by mtmiller** [comment]
So `D:\repos\\octsympy\\inst\\private\\python_header.py` is an incorrect file name? Is it the mix of single and double backslashes? Does the file exist at that location if you ignore the file separators? If you fix the constructed file name to `python_header.py` in the driver does everything else work?

**Comment by genuinelucifer** [comment]
Actually the main problem was that the main command issued is `python -c "some_string"` where some_string also contains double quotes and hence part of the string is being treated as a separate argument. But fixing that led to other issues.

>Does the file exist at that location if you ignore the file separators?

Yes.

> If you fix the constructed file name to python_header.py in the driver does everything else work?

Well, yes, given that I change the path separator. I know different path separators are preffered in windows and linux but in windows both the path separators work properly so I don't know the cause of prefering a different path separator for windows.  
The following diff works well for me and the tests in sympref pass:
```diff
diff --git a/inst/private/python_ipc_sysoneline.m b/inst/private/python_ipc_sysoneline.m
index 9fccbaf..f826d07 100644
--- a/inst/private/python_ipc_sysoneline.m
+++ b/inst/private/python_ipc_sysoneline.m
@@ -69,8 +69,9 @@ function [A, info] = python_ipc_sysoneline(what, cmd, mktmpfile, varargin)
   % Windows.  We have a 8000 char budget, and the header uses all
   % of it.
   mydir = fileparts (mfilename ('fullpath'));
+  mydir = strrep(mydir, '\', '/');
   % execfile() only works on python 2
-  headers = ['exec(open(\"' mydir filesep() 'python_header.py\").read()); '];
+  headers = ['exec(open(\"' mydir '/' 'python_header.py\").read()); '];
   %s = python_header_embed2();
   %headers = ['exec(\"' s '\"); '];
```

**Comment by mtmiller** [comment]
If changing the pathname separator alone fixes this bug, maybe it's because some of the backslash characters are double backslashed, or more of them need to be double backslashed? It's interesting that similar code using `fileparts` and `mfilename` works fine in python_header.m, where the file is read by Octave, but fails when pasting the file name into a string that is passed to Python.

You might want to look at the functions `fullfile`, `canonicalize_file_name`, and `undo_string_escapes`, some combination of these may help generate a file name that can be passed to Python and resolve correctly. Using a Python raw string may help also.

**Comment by mtmiller** [comment]
Sorry, `canonicalize_file_name` and `undo_string_escapes` are Octave specific, but they may help determine what needs to be done to the file name to get it into a form that works in the constructed Python script.

**Comment by genuinelucifer** [comment]
I will look at other functions too but how about the following diff (since it is just escaping issue):
```diff
diff --git a/inst/private/python_ipc_sysoneline.m b/inst/private/python_ipc_sysoneline.m
index 9fccbaf..77a8f5a 100644
--- a/inst/private/python_ipc_sysoneline.m
+++ b/inst/private/python_ipc_sysoneline.m
@@ -69,8 +69,9 @@ function [A, info] = python_ipc_sysoneline(what, cmd, mktmpfile, varargin)
   % Windows.  We have a 8000 char budget, and the header uses all
   % of it.
   mydir = fileparts (mfilename ('fullpath'));
+  mydir = strrep([mydir filesep()], '\', '\\');
   % execfile() only works on python 2
-  headers = ['exec(open(\"' mydir filesep() 'python_header.py\").read()); '];
+  headers = ['exec(open(\"' mydir 'python_header.py\").read()); '];
   %s = python_header_embed2();
   %headers = ['exec(\"' s '\"); '];
```
This shouldn't cause problems on linux too as there won't be any `\` in `mydir` on linux...

**Comment by mtmiller** [comment]
If that diff works, looks good to me.

**Comment by cbm755** [comment]
Cool, send a PR.

Is this happening b/c your repo is on `D:`?  Otherwise, I'm not sure why this hasn't been noticed before!  Do the existing double `\\` become `\\\\` with this change?

**Comment by mtmiller** [comment]
@cbm755 #454 sounds very similar, maybe it has happened before but is hard to pinpoint. Maybe it has to do with the pathname, hopefully doesn't have to do with how directories are added to Octave's load path, hopefully `fileparts(mfilename('fullpath'))` returns something consistent between systems and users and pathnames.

**Comment by genuinelucifer** [comment]
>  Do the existing double \\ become \\\\ with this change?

seems so. Value of `mydir` before and after strrep:
```
mydir = d:\repos\octsympy\inst\private
mydir = d:\\repos\\octsympy\\inst\\private\\
```
  
I don't think it's related to D drive in particular. But i cant say why this wasn't seen earlier.

**Comment by cbm755** [comment]
Perhaps the backslashes were causes some escaped chars (like `\r`) whereas in other cases they just became standard chars (`\p` to `p`).  That might explain why it happens on some paths not others.

Anyway, I merged your fix.

**Comment by mtmiller** [comment]
> Perhaps the backslashes were causes some escaped chars (like \r)

Yes! That explains #454, if the username was "anon", then the `\a` was interpreted as the BEL character, which is the same as `chr(7)`.
