### ISSUE TITLE
Why do i get: Using rat() heuristics for double-precision input (is this what you wanted?)

### ISSUE THREAD

**Issue by DanielMartensson** [cbm755/octsympy#797]
Hi!

Why do i get Using rat() heuristics for double-precision input (is this what you wanted?) all the time?
I don't want it.

**Comment by mtmiller** [comment]
Please give an example that demonstrates what you are doing and what you think OctSymPy should be doing differently.

**Comment by cbm755** [comment]
Usually this means you are using `sym(1/10)` when you should use `sym(1)/10`.  The warning and docs will be improved soon to help folks understand what is happening here, see #764.

**Comment by cbm755** [comment]
Also, I just filed #798, to summarize my plans around this.

**Comment by DanielMartensson** [comment]
Hi! Here is an example.

`>> a
a =  3542.3
>> b
b =  0.023000
>> A
A = (sym) [2  4⋅a]  (1×2 matrix)
>> A*a*b
warning: Using rat() heuristics for double-precision input (is this what you wanted?)
warning: called from
    sym at line 225 column 7
    mtimes at line 65 column 5
warning: Using rat() heuristics for double-precision input (is this what you wanted?)
ans = (sym 1×2 matrix)

  ⎡1425793  1425793⋅a⎤
  ⎢───────  ─────────⎥
  ⎣  8750      4375  ⎦

>>

`

**Comment by mtmiller** [comment]
Reposting with the formatting cleaned up

    >> a
    a =  3542.3
    >> b
    b =  0.023000
    >> A
    A = (sym) [2  4⋅a]  (1×2 matrix)
    >> A * a * b
    warning: Using rat() heuristics for double-precision input (is this what you wanted?)
    warning: called from
        sym at line 256 column 9
        mtimes at line 65 column 5
    warning: Using rat() heuristics for double-precision input (is this what you wanted?)
    warning: called from
        sym at line 256 column 9
        mtimes at line 65 column 5
    ans = (sym 1×2 matrix)
    
      ⎡814729  814729⋅a⎤
      ⎢──────  ────────⎥
      ⎣ 5000     2500  ⎦
    

So these warnings are coming from implicit conversion, when multiplying a sym that was constructed "correctly" against any floating point value. If I'm reading #764 and #798 correctly, there will still be a warning issued in this scenario. So I guess this falls under #764, improving the wording and the docs so users understand better what this means.

**Comment by cbm755** [comment]
@DanielMartensson oops I meant to ask your opinion on #800.  Its now been merged but if you get a chance, please look over and make suggestions to improve it further.
