### ISSUE TITLE
add kron

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#80]

**Comment by trueutkarsh** [comment]
@cbm755  is this about Kronecker tensor product ?
Also do we have a wrapper for numpy , or we need to do this ourselves ?

**Comment by cbm755** [comment]
Yes, that's right.  I don't think we should depend on Numpy.  Check if Sympy has an appropriate command...  Otherwise some list comprehension trickery might be needed.

**Comment by trueutkarsh** [comment]
@cbm755  #383
