### ISSUE TITLE
After compiliing Octave for Centos 7 and installing the symbolic package it complains that SymPy is too old even there is a newer version in the system

### ISSUE THREAD

**Issue by aarelovich** [cbm755/octsympy#807]
So after a very long morning I've managed to compile and run Octave 4.2.1, the sole reason for this being to get the symbolic package working. So I install it with pkg install -forge symbolic, I load it with pkg load symbolic and then try syms y(x).

I get:

OctSymPy v2.5.0: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
error: SymPy is installed but is too old (sympy-0.7.6 found, 1.0 required)
error: called from
    assert_have_python_and_sympy at line 44 column 7
    python_ipc_popen2 at line 78 column 5
    python_ipc_driver at line 58 column 13
    python_cmd at line 164 column 9
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13

However If I do this:
pip list | grep sympy
I get: 
sympy (1.0)

So how do I tell octave to actually use the newer version of SymPy?

**Comment by cbm755** [comment]
First, can you test from the command line (outside of Octave):
````
$ python
Python 2.7.13 (default, May 10 2017, 20:04:28) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.0'
>>> 
````

If that also imports the wrong sympy version then I wonder if changing the environment variables $PYTHON_PATH would help? You can do this within Octave with `getenv` and `setenv`.

**Comment by guaramania** [comment]
Hello,

I face the same problem on ubuntu16.04 LTS since I updated my symbolic toolbox on octave.
```
>> pkg load symbolic
>> syms y(x) a(x) b(x);
OctSymPy v2.6.0: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
error: SymPy is installed but is too old (sympy-0.7.6 found, 1.0 required)
error: called from
    assert_have_python_and_sympy at line 44 column 7
...
```

I updated all my python setup with **sudo pip install -U sympy** , **sudo -H pip3 install --upgrade pip** , **sudo -H pip2 install --upgrade pip** and **sudo pip-review --local --interactive**
And when I **locate sympy** I get the following folders

```
...
/usr/local/lib/python2.7/dist-packages/sympy
/usr/local/lib/python2.7/dist-packages/sympy-0.7.6.egg-info
...
/usr/local/lib/python2.7/dist-packages/sympy/vector/tests/test_vector.pyc
/usr/local/lib/python3.5/dist-packages/sympy
/usr/local/lib/python3.5/dist-packages/sympy-1.1.1-py3.5.egg-info
```


This mean that sympy-1.1.1 is already setup but only in python 3.5 . As I have sympy 0.7.6 with python 2.7.12 in ubuntu and I don't want to break up everything, is there a way to tell octave to use sympy-1.1.1 with python 3.5?
I don't have $PYTHON_PATH in my env. Would it be the right solution?

Thanks in advance,
Gabriel

**Comment by cbm755** [comment]
Try `setenv PYTHON python3` at the Octave prompt?  You may need to do `sympref reset` after you do this (if you have already created any syms)

**Comment by aarelovich** [comment]
I agree. The solution should work. Follow Colin's Advice

**Comment by cbm755** [comment]
Please confirm if this works.

Also: can one of you let me know if `help sympref` is good enough or some improvement we could make there?  Also should `help syms` or similar refer readers to `help sympref` so they can find this info themselves?

**Comment by guaramania** [comment]
Dear Colin,

The `setenv PYTHON python3` worked well with my setup. I tried a bit to get the information with `help sympref`. I think that adding the availability to set python3 would help users who have sympy on this version of python with their distros. Also, maybe adding this command at the beginning of the octave's wiki page of symbolic toolbox. 
I have to say that compare to standard packages, pythons packages are a bit of a mess to manage on a system.

Anyway, thanks for your advice Colin,
Kind regards

**Comment by mtmiller** [comment]
@aarelovich was this the problem on your end as well? Configuring python3 found the expected version of SymPy?

For some users, I can see how this configuration is still very obscure. One observation is that the error message only asks if SymPy is installed, it doesn't advise anything about having more than one Python environment or suggest to look at the sympref help. There is still a non-obvious disconnect between having a Python setup that the user knows works, and not knowing whether or how octsympy is finding Python.

I don't like to pack too much information into a single spontaneous error message. But what if the unable-to-run-python-or-sympy error pointed to some command, let's call it "octsympy_diagnose", that the user could be advised to run? It could do a more verbose display of what it thinks the Python environment is, Python version, SymPy version or lack thereof, etc. And maybe give suggestions like, are we finding the right Python? If not, try setting the `PYTHON` environment variable.

**Comment by cbm755** [comment]
Thank you @guaramania we will try to tweak the text of sympref a bit.

And good idea about the wiki: It really could use an "Help! it can't find Python" section.  Do you have time to start such a thing?  If you start it, others will help!  http://wiki.octave.org/Symbolic_package

There is also Issue #771.  @mtmiller, maybe your idea is a good compromise for #771 which I think we felt was "too smart for its own good".

> I have to say that compare to standard packages, pythons packages are a bit of a mess to manage on a system.

I don't disagree.  Pythonistas will just tell us how easy pip/virtualenv/etc are... but my philosophy has always been "if my distro (Fedora) doesn't have it, then I'm not sure I can be bothered".

**Comment by cbm755** [comment]
@mtmiller `sympref diagnose`?

**Comment by cbm755** [comment]
For reference in this discussion, the relevant function is https://github.com/cbm755/octsympy/blob/master/inst/private/assert_have_python_and_sympy.m

It does have separate error messages for "can't find python", "can't find sympy" and "sympy too old".

Perhaps the `is your "path" configured correctly` would be better as
  `If you do have Python installed, see "help sympref" for tips on how to select it.`

Or what if every error msg in that file had one more line:
   `Some systems have more than one Python installed, see "help sympref" for tips.`?

**Comment by mtmiller** [comment]
@cbm755 I was thinking about an extra line as well, but that's where, to me at least, it starts to look like too many information lines in one error message.

That's why I thought it would be helpful if all of those errors were maybe pruned to one line, with a consistent and obvious pointer to a "wizard" type function like `sympref diagnose` that could give a lot more information at the user's request.
