### ISSUE TITLE
exmp(A*t) gives "could not compute the eigenvalues"

### ISSUE THREAD

**Issue by DanielMartensson** [cbm755/octsympy#808]
Hello!

I cannot create the state transition matrix e^At. It seems that the expm can't compute the eigenvalues.
I have always problem to compute the state transition matrix in GNU octave. 

> syms t
>  A
> A =
> 
>    0.0000e+00   1.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00
>   -1.7778e+03  -5.0000e+02   1.7778e+03   3.0000e+02   0.0000e+00   0.0000e+00
>    0.0000e+00   0.0000e+00   0.0000e+00   1.0000e+00   0.0000e+00   0.0000e+00
>    1.7778e+01   3.0000e+00  -5.9603e+01  -5.9460e+00   4.1825e+00   0.0000e+00
>    0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00   0.0000e+00   1.0000e+00
>    0.0000e+00   0.0000e+00   1.7925e+05   0.0000e+00  -4.1081e+05  -4.2857e+04
> 
>  expm(A*t)
> warning: Using rat() heuristics for double-precision input (is this what you wanted?)
> warning: called from
>     sym at line 225 column 7
>     numeric_array_to_sym at line 36 column 14
>     sym at line 203 column 7
>     mtimes at line 65 column 5
> warning: Using rat() heuristics for double-precision input (is this what you wanted?)
> warning: Using rat() heuristics for double-precision input (is this what you wanted?)
> warning: Using rat() heuristics for double-precision input (is this what you wanted?)
> warning: Using rat() heuristics for double-precision input (is this what you wanted?)
> warning: Using rat() heuristics for double-precision input (is this what you wanted?)
> warning: Using rat() heuristics for double-precision input (is this what you wanted?)
> warning: Using rat() heuristics for double-precision input (is this what you wanted?)
> warning: Using rat() heuristics for double-precision input (is this what you wanted?)
> error: Python exception: AttributeError: could not compute the eigenvalues
>     occurred at line 4 of the Python code block
> error: called from
>     python_cmd at line 176 column 5
>     expm at line 54 column 5
> 

If Octave can compute the eigenvalues while doing the state transition matrix, I will gives me a huge exactly state transition matrix. It's not requried to have an exactly state transition matrix. 

> pkg load symbolic
> syms t
> OctSymPy v2.4.0: this is free software without warranty, see source.
> Initializing communication with SymPy using a popen2() pipe.
> Some output from the Python subprocess (pid 15321) might appear next.
> Python 2.7.13 (default, Jan 19 2017, 14:48:08)
> [GCC 6.3.0 20170118] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> 
> OctSymPy: Communication established.  SymPy v1.0.
>  A = [2 3; 2 10]
> A =
> 
>     2    3
>     2   10
> 
>  expm(A*t)
> ans = (sym 2×2 matrix)
> 
>   ⎡    ⎛    1                         3                  ⎞  t⋅(-√22 + 6)
>   ⎢  3⋅⎜───────── + ─────────────────────────────────────⎟⋅ℯ
>   ⎢    ⎜  √22                                           2⎟
>   ⎢    ⎜- ─── - 2             ⎛  4⋅√22   22⎞ ⎛  √22    ⎞ ⎟
>   ⎢    ⎜   2        (4 + √22)⋅⎜- ───── + ──⎟⋅⎜- ─── - 2⎟ ⎟
>   ⎢    ⎝                      ⎝    3     3 ⎠ ⎝   2     ⎠ ⎠
>   ⎢- ─────────────────────────────────────────────────────────────────── - ────
>   ⎢                                -4 + √22
>   ⎢                                                                        (4 +
>   ⎢
>   ⎢
>   ⎢
>   ⎢       ⎛    1                         3                  ⎞  t⋅(-√22 + 6)
>   ⎢       ⎜───────── + ─────────────────────────────────────⎟⋅ℯ             - ─
>   ⎢       ⎜  √22                                           2⎟                 ⎛
>   ⎢       ⎜- ─── - 2             ⎛  4⋅√22   22⎞ ⎛  √22    ⎞ ⎟                 ⎜
>   ⎢       ⎜   2        (4 + √22)⋅⎜- ───── + ──⎟⋅⎜- ─── - 2⎟ ⎟                 ⎝
>   ⎣       ⎝                      ⎝    3     3 ⎠ ⎝   2     ⎠ ⎠
> 
> 
> 
> 
> 
>             t⋅(√22 + 6)                                t⋅(-√22 + 6)
>          3⋅ℯ                                        9⋅ℯ
>   ────────────────────────────────  ───────────────────────────────────────────
>         ⎛  4⋅√22   22⎞ ⎛  √22    ⎞                       ⎛  4⋅√22   22⎞ ⎛  √22
>    √22)⋅⎜- ───── + ──⎟⋅⎜- ─── - 2⎟  (-4 + √22)⋅(4 + √22)⋅⎜- ───── + ──⎟⋅⎜- ───
>         ⎝    3     3 ⎠ ⎝   2     ⎠                       ⎝    3     3 ⎠ ⎝   2
> 
>          t⋅(√22 + 6)                                         t⋅(-√22 + 6)
>         ℯ                                                 3⋅ℯ
>   ─────────────────────────                   - ───────────────────────────────
>     4⋅√22   22⎞ ⎛  √22    ⎞                               ⎛  4⋅√22   22⎞ ⎛  √22
>   - ───── + ──⎟⋅⎜- ─── - 2⎟                     (4 + √22)⋅⎜- ───── + ──⎟⋅⎜- ───
>       3     3 ⎠ ⎝   2     ⎠                               ⎝    3     3 ⎠ ⎝   2
> 
> 
>                                  ⎤
>                                  ⎥
>                                  ⎥
>                                  ⎥
>                  t⋅(√22 + 6)     ⎥
>               3⋅ℯ                ⎥
>   ──── + ────────────────────────⎥
>      ⎞             ⎛  4⋅√22   22⎞⎥
>   - 2⎟   (4 + √22)⋅⎜- ───── + ──⎟⎥
>      ⎠             ⎝    3     3 ⎠⎥
>                                  ⎥
>            t⋅(√22 + 6)           ⎥
>           ℯ                      ⎥
>   ───── + ────────────           ⎥
>       ⎞     4⋅√22   22           ⎥
>    - 2⎟   - ───── + ──           ⎥
>       ⎠       3     3            ⎥
>                                  ⎦
> 
> 

The state transition matrix should be in decimal form. To do that I use:

> vpa(expm(A*t), 3)
> ans = (sym 2×2 matrix)
> 
>   ⎡       t⋅(-√22 + 6)           t⋅(√22 + 6)           t⋅(-√22 + 6)         t⋅(
>   ⎢0.926⋅ℯ             + 0.0736⋅ℯ              - 0.32⋅ℯ             + 0.32⋅ℯ
>   ⎢
>   ⎢         t⋅(-√22 + 6)          t⋅(√22 + 6)          t⋅(-√22 + 6)          t⋅
>   ⎣- 0.213⋅ℯ             + 0.213⋅ℯ             0.0736⋅ℯ             + 0.927⋅ℯ
> 
>   √22 + 6) ⎤
>            ⎥
>            ⎥
>   (√22 + 6)⎥
>            ⎦
> 
> 

The only problem is when it comes to 3x3 matrices or larger....it won't work for me. My computer is fast, but Octave cannot compute the state transition matrix if A is the dimension 3x3 or larger. 

Information: 
GNU octave version: 4.0.3
Symbolic version: 2.4.0-2
Operative system: Lubuntu Linux 17.04

**Comment by cbm755** [comment]
`A` looks like a floating-point double-precision matrix: mixing floating point into symbolic calculations is usually not a good idea (see #764, and #800, which hopefully improves the docs).

Finding, symbolically, the eigenvalues of a 6x6 matrix really is a hard problem: there cannot exist a general formula for the roots of a 6 degree polynomial (which is an equivalent problem).

I suspect you want to use "eig" to compute the eigenvalues *numerically* (a much easier problem!)
