### ISSUE TITLE
Audit: older functions that need symvar

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#81]
I wrote a lot of code before I wrote symvar.  Many SMT functions use symvar if the user does not specify a variable (e.g., `diff(sin(x))` automatically differentiates w.r.t. `x`).  Here is a list of functions to audit and check if they need symvar support somewhere.

In many cases there will also be a `todo` or `FIXME` in the code.  This is not enough, fix or file a bug.

(A check mark shall mean fixed, or a bug has been filed.)
- [x] assumeAlso.m
- [x] assume.m
- [x] ccode.m
- [x] curl.m
- [x] diff.m
- [x] divergence.m
- [x] dsolve.m
- [x] expand.m
- [x] ezplot3.m
- [x] ezplot.m
- [x] factor.m
- [x] findsym.m
- [x] fortran.m
- [x] fourier.m
- [x] gradient.m
- [x] horner.m
- [x] ifourier.m
- [x] int.m
- [x] jacobian.m
- [x] laplacian.m
- [x] limit.m
- [x] matlabFunction.m
- [x] mod.m
- [x] prod.m
- [x] simplify.m
- [x] solve.m
- [x] subs.m
- [x] sym2poly.m
- [x] sym.m
- [x] symprod.m
- [x] symsum.m
- [x] symvar.m
- [x] taylor.m

**Comment by cbm755** [comment]
fourer/ifourier fixed by @AlexanderMisel in #225.

**Comment by cbm755** [comment]
Factor done in #347.

**Comment by latot** [comment]
I propose if is possible in the function it uses ```python_cmd``` instead of symvar handle it from python, what do you think?

**Comment by cbm755** [comment]
maybe, but then need to repeat the logic from symvar: its non-trivial.

**Comment by latot** [comment]
you already done taylor via https://github.com/cbm755/octsympy/commit/63240082541c297538849ce1b798e24780749c89
