### ISSUE TITLE
matrix factorizations may change names in dev sympy

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#812]
Old names are deprecated so we'll probably get lots of warnings.

**Comment by mtmiller** [comment]
I see the following from the test suite:

    /path/to/sympy/core/decorators.py:38: SymPyDeprecationWarning: 
    
    cholesky has been deprecated since SymPy 1.1. Use
    cholesky_decomposition instead. See
    https://github.com/sympy/sympy/issues/12389 for more info.
    
      _warn_deprecation(wrapped, 3)
    /path/to/sympy/core/decorators.py:38: SymPyDeprecationWarning: 
    
    LUdecomposition has been deprecated since SymPy 1.1. Use
    LU_decomposition instead. See
    https://github.com/sympy/sympy/issues/12389 for more info.
    
      _warn_deprecation(wrapped, 3)
    /path/to/sympy/core/decorators.py:38: SymPyDeprecationWarning: 
    
    QRdecomposition has been deprecated since SymPy 1.1. Use
    QR_decomposition instead. See
    https://github.com/sympy/sympy/issues/12389 for more info.
    
      _warn_deprecation(wrapped, 3)

**Comment by cbm755** [comment]
I guess we need to query the sympy version and DTRT (until we drop support for sympy 1.0)

**Comment by cbm755** [comment]
AFAIK, not going to happen.
