### ISSUE TITLE
compatibility with sympy 1.1.1

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#813]
Sympy 1.1 is coming.  We should do a new release soon after as there have been various compatibility fixes since 2.5.0.

**Comment by mtmiller** [comment]
I've been using SymPy dev with Python 3.6.1 for a while now, running the full test suite against the 1.1 branch now to see if I missed anything.

**Comment by cbm755** [comment]
good idea: there has been a kind of scary flurry of activity upstream.

**Comment by mtmiller** [comment]
The only failures and warnings I see now, you've already reported in #812 and #814.

**Comment by cbm755** [comment]
The Octave Symbolic pkg test suite in master now passes on sympy-1.1rc1.  CC @asmeurer FYI.

(For better or worse, the new matrix stuff has been reverted.)

**Comment by asmeurer** [comment]
@cbm755 @mtmiller if you and other interested parties could comment on https://github.com/sympy/sympy/issues/12389 that would be great. One reason I reverted the deprecations for the release was that I didn't feel there was enough discussion from the community. 

(p.s. thanks for testing the release candidate!)

**Comment by cbm755** [comment]
Will check again with the upcoming 1.1.1, then do our release: so far, no test failures...

**Comment by asmeurer** [comment]
Thanks. I want to do the final release of 1.1.1 tomorrow (assuming no issues come up).

**Comment by cbm755** [comment]
all passing with 1.1.1rc1.

**Comment by asmeurer** [comment]
Can you check the 1.1.1 branch too. There was a [matrix PR](https://github.com/sympy/sympy/pull/13031) merged into it.

**Comment by cbm755** [comment]
oops, thought that was in rc1, I will test...

**Comment by cbm755** [comment]
@asmeurer 1.1.1 branch looks fine to me!
