### ISSUE TITLE
qr(x) test fails with upcoming sympy

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#814]
[updated title as there's been some reverting in the 1.1 branch upstream]

**Comment by mtmiller** [comment]
SymPy 1.0:

    >>> [q, r] = Matrix([S('x')]).QRdecomposition()
    >>> q
    Matrix([[x/Abs(x)]])
    >>> r
    Matrix([[Abs(x)]])

SymPy 1.1 branch:

    >>> [q, r] = Matrix([S('x')]).QR_decomposition()
    >>> q
    Matrix([[x/Abs(x)]])
    >>> r
    Matrix([[x**2/Abs(x)]])

**Comment by mtmiller** [comment]
The following difference now (back in Octave):

    >> syms x
    >> assume x clear
    >> [q, r] = qr (x)
    q = (sym)
    
       x 
      ───
      │x│
    
    r = (sym)
    
        2
       x 
      ───
      │x│
    
    >> q*r
    ans = (sym)
    
        3 
       x  
      ────
         2
      │x│ 
    
    >> assume x real
    >> q*r
    ans = (sym) x

This limits the test case a bit more but allows it to pass under either SymPy 1.0 or the latest changes.

**Comment by cbm755** [comment]
Let's just put `syms x real` at the top of the test.

**Comment by cbm755** [comment]
@siefkenj its not urgent at all but just so its on your radar... is this change in how `QR_decomposition` deals with `Symbol`s deliberate?  Mostly just pointing this out in case its indicative of some deeper bug.

FWIW, the old result is closer to the double-precision QR output:
````
>> x = 1 - 1i
x =  1 - 1i
>> [q, r] = qr(x)
q = -0.70711 + 0.70711i
r = -1.4142
>> q2 = x/abs(x)
q2 =  0.70711 - 0.70711i
>> r2 = abs(x)
r2 =  1.4142
````

Compared to the new formulae:
````
>> q3 = x/abs(x)
q3 =  0.70711 - 0.70711i
>> r3 = x^2/abs(x)
r3 =  0.00000 - 1.41421i
````

**Comment by mtmiller** [comment]
@cbm755 since this passes with SymPy 1.1 now, remove milestone tracker from this issue?
