### ISSUE TITLE
popen2 on windows is sensitive to stderr output (e.g., by python)

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#82]
Upstream Octave:

https://savannah.gnu.org/bugs/?43036

FIXME: workaround this.

**Comment by cbm755** [comment]
We have a workaround since long time ago.  Only thing needed is fixing this upstream.

**Comment by okejokej** [comment]
Hi! Just wanted to note that it'd be helpful if it'd be more explicitly(that is, somewhere outside of the file itself) stated that winwrapy.bat might require editing before the package actually begins functioning.
It seems to apply to more than just old systems as both my XP and Win 7 machines just flip the table if there's an attempt of using symbolic package without editing the bat file(to leave only the necessary minimum).

Cheers!

**Comment by cbm755** [comment]
thanks @okejokej 

Perhaps you could [edit part of the wiki](https://github.com/cbm755/octsympy/wiki/Notes-on-Windows-installation) with your experiences on XP?  (I don't really know what edits to the wrapper that you're referring to)

**Comment by okejokej** [comment]
Alright, added a note about it at the bottom - I completely missed that Wiki ^^

**Comment by cbm755** [comment]
thanks!  And I know I know what changes you're talking about too :-)

Where do you suggest documenting this where you would have found it?

**Comment by okejokej** [comment]
I think it would be good to put a link to that wiki in package's description on Octave-Forge, that is if it allows links, of course :P If not, some mention of Wiki's existence, perhaps.

**Comment by cbm755** [comment]
Added to the README for now, thanks for the suggestions.

**Comment by cbm755** [comment]
@mtmiller has proposed a patch at https://savannah.gnu.org/bugs/?43036 and needs testing.

**Comment by cbm755** [comment]
Many thanks to @mtmiller and Tatsuro MATSUOKA, this is fixed upstream!
