### ISSUE TITLE
wiki: update ubuntu instructions

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#829]
https://github.com/cbm755/octsympy/wiki/Notes-on-GNU-Linux-installation

@mtmiller what is the version of "octave-symbolic" in versions of Ubuntu that people commonly use?  Can you update the bit in the wiki about Ubuntu?  Maybe move it ahead of fedora.

We should consider moving that wiki to the official Octave wiki.

**Comment by mtmiller** [comment]
Page updated. Current Ubuntu LTS has 2.2.4, current release has 2.4.0. Debian stable has 2.4.0, oldstable has ancient 1.1.0 (analogous to Ubuntu old-LTS, also 1.1.0).

**Comment by cbm755** [comment]
thanks for that info!  Out of curiosity, I went looking, found this https://tracker.debian.org/pkg/octave-symbolic

I wanted to know if they run the test suite, so I looked for the Debian equivalent of a Fedora .spec file, and found https://sources.debian.net/src/octave-symbolic/2.5.0-2/debian/rules/
From that, I guess they do the rest suite (yah!).

**Comment by mtmiller** [comment]
Yes, but I think errors are ignored at this point.

If you want to see the results, look in https://buildd.debian.org/status/package.php?p=octave-symbolic, also linked from the tracker.debian.org tool.
