### ISSUE TITLE
CI test failure on @double/cosint.m, possibly due to PPA update to Octave 4.2.1

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#837]
I am seeing a CI test failure today with Octave installed from the PPA. I have just updated the PPA to Octave 4.2.1, and maybe something in the build or the libraries used is introducing this.

    ***** test
     % compare both sinint and cosint to expint
     x = pi;
     C1 = cosint (x);
     S1 = sinint (x);
     R = expint (1i*x);
     C2 = -real (R);
     S2 = imag (R) + pi/2;
     assert (C1, C2, -10*eps);
     assert (S1, S2, -10*eps);
    !!!!! test failed
    ASSERT errors for:  assert (C1,C2,-10 * eps)
      Location  |  Observed  |  Expected  |  Reason
         ()        0.073668     0.073668     Rel err 4.5212e-15 exceeds tol 2.2204e-15

**Comment by mtmiller** [comment]
And i'm unable to reproduce this difference in tolerance in a clean 14.04 container running the exact same Octave binary image 😞

**Comment by mtmiller** [comment]
I confused myself, working on too many things at once, I was trying to reproduce using the daily binary. This error occurs with the PPA build only. I _can_ reproduce locally using 4.2.1 installed from the PPA.

With PPA Octave 4.2.1:

    >> C1 = cosint (pi);
    >> R = expint (1i * pi);
    >> C2 = -real (R);
    >> sprintf ("%.20g", C1)
    ans = 0.073667912046425532147
    >> sprintf ("%.20g", C2)
    ans = 0.07366791204642519908

and with Octave default branch built today:

    >> sprintf ("%.20g", C2)
    ans = 0.073667912046425504391

I'm not sure why there wasn't a problem with Octave 4.0, but the more accurate rewrite of expint in Octave's default branch closes the tolerance up again.

Loosen the test tolerance to pass the test with 4.2 version of expint.m?

**Comment by cbm755** [comment]
Sure loosen tolerance.  Let me know if you prefer I do it.
