### ISSUE TITLE
something wrong with symbolic and the pager?

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#840]
@DanielMartensson notes a problem with the pager in #835, on this example:
````
A = [1 3 4; 2 4 5; 0 3 2]
syms t
expm(A*t)
````
Apparently "It's says that it needs to collect data".

So far, I cannot reproduce this.  I don't usually use the pager, but I tried this with `more on`.  And it seems fine to me: the paper runs and if I scroll far enough (or press "f" enough times), I get my prompt back.

I also played with `A = [1 3 4; 2 4 5; 0 0 2]`, which is faster (< 10 seconds) and still brings up the pager.

**Comment by cbm755** [comment]
@DanielMartensson what happens if you try this with `more off`?

**Comment by mtmiller** [comment]
The message `Waiting for data... (interrupt to abort)` only happens with `less +F`, which is less for "act like `tail -f`". `+F` is definitely not in the default flags passed to the pager by Octave. This looks like user error to me.

**Comment by cbm755** [comment]
Actually, with the slower example, I can see:
`````
Waiting..............
ans = (sym 3×3 matrix)

...
`````
And if I press "q" instead of scrolling to the bottom I get `warning: broken pipe`.  None of that happens on the faster example.

What OS are you on?  What is the environment variable $PAGER set to?

**Comment by mtmiller** [comment]
Oh, or possibly user error by entering uppercase `F` instead of lowercase `f` at the prompt.

**Comment by cbm755** [comment]
Ah!  Thanks @mtmiller.  That is probably what happened here.  That's not a very friendly feature of "less"!  There is something not quite right here though as I get the broken pipe warning.

**Comment by mtmiller** [comment]
The `warning: broken pipe` is typical when a process is piping to less, but less exits before the input has finished being written to stdout. This is the standard error message for a SIGPIPE. This is coming from either Octave or the Python subprocess, not sure which. I can't reproduce at the moment, but I see this message so often I just consider it standard practice.

**Comment by mtmiller** [comment]
Ok, the warning message does come from Octave, and it is printed whenever any child process sends Octave a SIGPIPE. This is typical when a child process exits, but the parent is still trying to `write()` data to the child through a `pipe()`.

The simplest way to reproduce this is to set the `PAGER` to `head`, which exits immediately after 10 lines, while Octave continues writing to it:

    >> PAGER ("head");
    >> x = rand (100)
    x =
    
     Columns 1 through 6:
    
       9.2973e-01   9.1540e-01   3.0539e-01   1.5726e-01   7.0363e-01   3.4181e-01
       9.9679e-01   6.4220e-01   9.4433e-01   1.1724e-01   6.5038e-01   2.7229e-01
       4.0489e-01   3.7649e-01   2.7751e-02   8.5397e-01   4.9869e-01   9.0535e-01
       6.8095e-01   7.8792e-01   1.9700e-01   2.6278e-01   8.7734e-01   6.3542e-02
       3.3294e-01   4.8779e-02   4.6734e-01   8.2727e-02   2.1436e-01   9.5128e-01
       4.6555e-01   1.8123e-01   7.3761e-01   7.6262e-01   5.7083e-01   6.2788e-01
    warning: broken pipe

**Comment by cbm755** [comment]
Thanks for tracking that down. Now that I play with it, I can reliably get the "warning: broken pipe" just from `rand(1000, 10)` but not from `rand(500,10)`.  Anyway, its nothing to do with Symbolic.

@DanielMartensson try `more off`.

**Comment by mtmiller** [comment]
Same, it has to do with terminal size and the kernel's pipe buffer size, usually 64k. If Octave outputs more than enough data to fill the pipe, write blocks, then you quit the pager, then Octave gets SIGPIPE and its blocking write returns with errno set to EPIPE.

**Comment by DanielMartensson** [comment]
@cbm755 What do you mean with "Try more off"? What "off"?

**Comment by mtmiller** [comment]
@DanielMartensson Use the command

    >> more off

in Octave to disable the pager completely.
