### ISSUE TITLE
abs() does not work with octsympy properly

### ISSUE THREAD

**Issue by DanielMartensson** [cbm755/octsympy#841]
Hi!

When I use abs() with octsympy, octsympy cannot simplify the equation.

Here is an example:

```
>> H = @(q) (q - 0.1) / (q - 0.2);
>> syms w
>> simplify(abs(H(exp(i*w)))^2)
             2
  │ ⅈ⋅w   1 │
  │ℯ    - ──│
  │       10│
  │─────────│
  │  ⅈ⋅w   1│
  │ ℯ    - ─│
  │        5│
```

The issue is that abs() is still there and octsympy have not compute it. The real answer should be this:

```

     cos(w)   101
   - ────── + ───
       5      100
  ───────────────
    2⋅cos(w)   26
  - ──────── + ──
       5       25
```

**Comment by mtmiller** [comment]
Your expression for what it should be is only valid if w is real.

If I choose _w_ = -_i_, then it's not a valid simplification.

**Comment by mtmiller** [comment]
Compare with what you get after using

    assume w real

**Comment by DanielMartensson** [comment]
Thanks! Much better!

```

  ⎛    ⅈ⋅w      ⎞  ⅈ⋅w
  ⎝10⋅ℯ    - 101⎠⋅ℯ    + 10
  ─────────────────────────
    ⎛   ⅈ⋅w     ⎞  ⅈ⋅w
  4⋅⎝5⋅ℯ    - 26⎠⋅ℯ    + 20
```

Is there a way to make so octsympy can feel the e^{i*w} can be replaced with cos(w) + i*sin(w) ?

**Comment by cbm755** [comment]
try `rewrite(<meh>, 'sin')` (I haven't tried it yet myself)

**Comment by cbm755** [comment]
original issue is not a bug.
