### ISSUE TITLE
should vpa warn when string input contains a decimal point?

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#847]
From a discussion at https://savannah.gnu.org/bugs/?func=detailitem&item_id=51748

Things like `vpa('0.1')` and `vpa('sqrt(2)')` are ok and recommented.

But these are likely to lose precision: `vpa('sin(0.1)')`, `vpa('2**0.1')`, `vpa('2*0.1')`: here we could consider issuing a warning.

Also
 * the docs should be expanded to warn about this
 * the docs should mention that `vpa('0.1')` is correct usage.

**Comment by mtmiller** [comment]
Should we try to regex match and warn against complex expressions that may not work as intended?

Another interesting side-effect happens with an unrecognized function name

    >> vpa('abs(1)')
    ans = (sym) abs(1)
    >> vpa('sqrtt(2)')
    ans = (sym) sqrtt(2)

**Comment by cbm755** [comment]
Minor correction to something I said above: `vpa('sqrt(2)')` is not so much "recommended" as "not yet deprecated", which means I'm not as worried about `vpa('abs(1)')` as I otherwise would be.

Basically, things you put in strings to `vpa` and `sym` are interpreted as Python (unless we do some parsing ourselves, which we do in some cases).

SMT has deprecated non-number strings in vpa/sym calls.
