### ISSUE TITLE
function_handle returns parse error - syntax error

### ISSUE THREAD

**Issue by Halolegend94** [cbm755/octsympy#854]
Hi,

Thank you for this library. While trying to solve e^{At} i encountered a parsing error.

 The following code
```
A = [
    1250  -25113  -60050  -42647  -23999;
     500  -10068  -24057  -17092   -9613;
     250   -5060  -12079   -8586   -4826;
    -750   15101   36086   25637   14420;
     250   -4963  -11896   -8438   -4756];
[V, D] = eig(A);
syms t;
eat_s = V * exp(D * t) * inv(V);

fh = function_handle(eat_s);
```
returns a parsing error, syntax error. You can also see this performing only `exp(D * t) * inv(V)`. Instead, only `exp(D * t)` is fine. I also attach the output.
```
@(t) [(51685/74 + 8199*1i/43)*exp(t.*(-4 + 3i)) (-277599/23 - 9213*1i*pi/16)*exp(t.*(-4 + 3i)) (-89758/3 - 142510*1i*pi/83)*exp(t.*(-4 + 3i)) (-187685/9 - 79552*1i*pi/73)*exp(t.*(-4 + 3i)) (-396296/33 - 30204*1i*pi/43)*exp(t.*(-4 + 3i)); (51685/74 - 8199*1i/43)*exp(t.*(-4 - 3i)) (-277599/23 + sqrt(3272365)i)*exp(t.*(-4 - 3i)) (-89758/3 + sqrt(29096062)i)*exp(t.*(-4 - 3i)) (-187685/9 + 6*sqrt(325577)i)*exp(t.*(-4 - 3i)) (-396296/33 + 4*sqrt(304349)i)*exp(t.*(-4 - 3i)); (388212/217 + 1i*pi/4089402170)*exp(-5*t) (-819503/28 - 1i*pi/300412695)*exp(-5*t) (-117023*pi/5 - 1i*pi/113541977)*exp(-5*t) (-161953*pi/10 - 1i*pi/168510444)*exp(-5*t) (-147771/5 - 1i/89373328)*exp(-5*t); (21859/50 + 1i*pi/19841023058)*exp(-2*t) (-131289*pi/71- 1i*pi/1456787573)*exp(-2*t) (-215785/14 - 1i/175275416)*exp(-2*t) (-75817*pi/23 - 1i*pi/817190402)*exp(-2*t) (-56029/9 - 1i/433437535)*exp(-2*t); (-2915*pi/182 - 1i*pi/174414145760)*exp(-t) (33812/51 + 1i*pi/12819036768)*exp(-t) (sqrt(3082379) + 1i*pi/4845460061)*exp(-t) (71872/61 + 1i*pi/7190926054)*exp(-t) (31718/45 + 1i/3814092764)*exp(-t)]
```
*EDIT*

It seems that code like `sqrt(45)i` is generated, and octave doesnt like it. It should be `sqrt(45)*i`.

EDIT 2: as pointed out by @mtmiller, it is a sympy problem. I created an [issue](https://github.com/sympy/sympy/issues/13977)   in their repo

EDIT 3: quick fix (at least it worked for my case) [here](https://github.com/sympy/sympy/pull/13978)

**Comment by mtmiller** [comment]
This looks like an issue for SymPy:

    >>> from sympy.utilities.codegen import codegen
    >>> expr = (1 + sqrt(3)*I)*exp(t)
    >>> [(_, out)] = codegen (('foo', expr), 'Octave', header=False)
    >>> print(out)
    function out1 = foo(t)
    
      out1 = (1 + sqrt(3)i)*exp(t);
    
    end

**Comment by Halolegend94** [comment]
I go there and open the issue then. Maybe we can keep this open to report the  outcome of the discussion in sympy issue.

**Comment by mtmiller** [comment]
Yeah, please post a link to the SymPy issue here, @cbm755 will add the upstream tag

**Comment by Halolegend94** [comment]
I posted the issue and also a fast fix (pull request to sympy) that worked for my personal issue.

**Comment by cbm755** [comment]
Thank you both!  Wonderful this is almost fixed before I even get around to checking my mail ;-)

**Comment by mtmiller** [comment]
[SymPy issue #13977](https://github.com/sympy/sympy/issues/13977)

**Comment by cbm755** [comment]
Fixed upstream by @Halolegend94 in https://github.com/sympy/sympy/pull/13978, thanks!

Unfortunately, I suppose its not worth working around this in our package so I guess this will remain a bug until the next sympy is released.  I will add a test at least...
