### ISSUE TITLE
ctrl-c can break the python ipc: error messages should suggest "sympref reset"

### ISSUE THREAD

**Issue by Halolegend94** [cbm755/octsympy#855]
As title says. A code example follows. System info: octave 4.0, octsympy v2.6.0, sympy v1.1.1

```
>> vpa(5, 32)
A = (sym) 5.0000000000000000000000000000000
out = <output_block>
<item>
<f>1020</f>
<f>Float('5.0', precision=110)</f>
<f>1</f>
<f>1</f>
<f>5.0000000000000000000000000000000</f>
<f>5.0000000000000000000000000000000</f>
<f>5.0000000000000000000000000000000</f>
</item>
</output_block>

error: ipc_popen2: something unexpected happened sending variables to python
error: called from
    python_ipc_popen2 at line 167 column 5
    python_ipc_driver at line 59 column 13
    python_cmd at line 164 column 9
    vpa at line 103 column 7
>>```

**Comment by cbm755** [comment]
Hmmm, that's a mystery.  I cannot reproduce on Octave 4.2.1.  Is this reproducible after restarting Octave?

Does `vpa(5)` work?

Does it work with the slow `sympref ipc system`?

What OS are you on?

If you could get the git master code, you could run `sympref diagnose`...?

**Comment by Halolegend94** [comment]
I tried again this morning. It seems it is a more general problem, because I had the same error this morning after working on issue https://github.com/cbm755/octsympy/issues/854 . Sometimes commands execute correctly, other times the output i've shown happens, and also other times the execution of a command seems blocked (computing forever, with message `waiting...`).

I use Ubuntu 16.04. In octave, i tried to run sympref ipc system and then executing
`M = V * syexp(D .* t) * inv(V);`
but it gets stuck and doesnt return.

I run the diagnosis and this is the output
```
Symbolic package diagnostics
============================

Python and SymPy are needed for most features of the Symbolic package.

The Python interpreter is currently: "python".

Computers may have more than one Python interpreter installed.  If you
need to, you can select a different one using the PYTHON environment
variable (see "help sympref").  For example, to use Python 3, try
    setenv PYTHON python3
    sympref reset

Attempting to run python -c "print(\"Python says hello\")"

status = 0
output = Python says hello

Good, Python ran correctly.


SymPy Python Library
--------------------

SymPy is a Python library used by Symbolic for almost all features.

Attempting to run python -c "import sympy; print(sympy.__version__)"

status = 0
output = 1.1.2.dev

SymPy must be at least version 1.0; you have version 1.1.2.dev.

Good, a working version of SymPy is installed.


Python XML Parsing and DOM Support
----------------------------------

The XML DOM library is used by Symbolic for passing values to and from Python.
Some older versions of Python formatted XML output differently.  As long as you
have any reasonably recent version of Python, this should pass.

Attempting to run python -c "import xml.dom.minidom as minidom; doc = minidom.parseString(\"<item>value</item>\"); print(doc.toprettyxml(indent=\"\"))"

status = 0
output = <?xml version="1.0" ?>
<item>value</item>



Your kit looks good for running the Symbolic package.  Happy hacking!
```

**Comment by mtmiller** [comment]
Are you only able to reproduce this after interrupting another long-running SymPy command? I can reproduce by doing something like

    syms t
    rand (10) * exp (t * eye (10))
    ^C

Interrupting this long-running call at the right time can certainly break the I/O control between Octave and Python. And then I get

    >> vpa (5, 32)
    ans = PYTHON: successful variable import
    >> vpa (5, 32)
    A = (sym) 5.0000000000000000000000000000000
    out = <output_block>
    <item>
    <f>1020</f>
    <f>Float('5.0', precision=110)</f>
    <f>1</f>
    <f>1</f>
    <f>5.0000000000000000000000000000000</f>
    <f>5.0000000000000000000000000000000</f>
    <f>5.0000000000000000000000000000000</f>
    </item>
    </output_block>
    
    error: ipc_popen2: something unexpected happened sending variables to python
    error: called from
        python_ipc_popen2 at line 167 column 5
        python_ipc_driver at line 59 column 13
        python_cmd at line 164 column 9
        vpa at line 103 column 7
    

Is this how you are getting this? Does the `sympref reset` command help you get back to a working state?

**Comment by cbm755** [comment]
Exactly who gets Ctrl-c and when seems buggy on Octave in general.  For example, I often plot in a loop and sometimes Ctrl-c just crashes octave instead of interrupting.  I'd always assumed the behaviour @mtmiller notes was similar; comes the octave interpreter catches the Ctrl-c and sometimes it gets to the Python interpreter, depending in phase of moon or something.

Maybe we can automatically do a 'sympref reset' somewhere to improve the user experience w.r.t. ctrl-c?

**Comment by mtmiller** [comment]
Or at least hint in the error message for the user to try `sympref reset`?

**Comment by Halolegend94** [comment]
Thanks a lot guys. It seems it is working now, with `sympref reset`. Yeah I used CTRL + C since the computation was taking too much (indeed the expressions were getting a bit large). Using `simplify` after every step helped. I would wait a day or two before closing the issue, just in case.

**Comment by cbm755** [comment]
Leave it open to remind me to look into hints or auto reset...

**Comment by cbm755** [comment]
btw, I just saw this:
````
error: Python exception: KeyboardInterrupt: 
    occurred while copying variables from Python.
    Consider filing an issue at https://github.com/cbm755/octsympy/issues
error: called from
    python_cmd at line 184 column 5
    double_to_sym_heuristic at line 46 column 7
    sym at line 379 column 13
    numeric_array_to_sym at line 36 column 14
    sym at line 359 column 7
````
I agree that error message should not encourage sending bugs.   It should mention ctrl-c and say to try "sympref reset".
