### ISSUE TITLE
error using symbolic package (self contained)

### ISSUE THREAD

**Issue by kurokirasama** [cbm755/octsympy#861]
Hello,

i followed the instructions:
```
pkg install symbolic-win-py-bundle-2.6.0.zip
load symbolic
syms x
```
but i got the following error:
```
error: 'python_ipc_popen2' undefined near line 59 column 15
error: called from
    python_ipc_driver at line 59 column 13
    python_cmd at line 164 column 9
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
```

**Comment by cbm755** [comment]
Does it persist after restarting Octave?

Also try `sympref reset`?  Sometimes this can happen after after ctrl-c out of a long operation.  It can also happen if you change the installation files on disk (i.e., during development).

**Comment by kurokirasama** [comment]
yes.

I tried but nothing changed. I'll try to install python and sympy and normal symbolic packages and see if it works.

**Comment by cbm755** [comment]
Octave version?  OS?  Does "sympref ipc system" work?

What does this do?
````
>> pkg load symbolic
>> which sympref
'sympref' is a function from the file /home/cbm/octave/symbolic-2.6.0/sympref.m
>> which syms
'syms' is a function from the file /home/cbm/octave/symbolic-2.6.0/syms.m
>> ls -l "/home/cbm/octave/symbolic-2.6.0/private"
total 112
-rw-r--r--. 1 cbm users 1815 Jan 20 22:51 assert_have_python_and_sympy.m
-rw-r--r--. 1 cbm users 2502 Jan 20 22:51 check_and_convert.m
-rw-r--r--. 1 cbm users 2810 Jan 20 22:51 do_highbyte_escapes.m

---- 8< ----
````

Maybe `ls -l` needs to be some other command if you're on Windows?

**Comment by cbm755** [comment]
Also what happens if you `chdir` to whatever `/home/cbm/octave/symbolic-2.6.0` is on your computer and try `syms x` from inside that directory.

**Comment by kurokirasama** [comment]
I did all your suggestions, with no luck. I reinstalled octave and everything seems fine now...
BTW, I'm on windows 10...

**Comment by cbm755** [comment]
ok, so I gather something was broken in your Octave installation and now its fixed.

I will close, reopen if you see it again.
