### ISSUE TITLE
Error when installing symbolic package

### ISSUE THREAD

**Issue by paridhicambridge** [cbm755/octsympy#862]
Thanks for the instructions on how to install symbolic package, however I get the following error:

pkg install -forge symbolic
Use of uninitialized value in lc at /usr/lib/perl5/5.8/utf8_heavy.pl line 123.
Use of uninitialized value in lc at /usr/lib/perl5/5.8/utf8_heavy.pl line 123.
Use of uninitialized value in lc at /usr/lib/perl5/5.8/utf8_heavy.pl line 123.
Use of uninitialized value in lc at /usr/lib/perl5/5.8/utf8_heavy.pl line 123.

How to resolve this?

**Comment by mtmiller** [comment]
This is the same as #610. It is an issue with the Octave Windows build, and it's not an error, the package is installed just fine.

**Comment by cbm755** [comment]
thanks for reporting and triage.

**Comment by paridhicambridge** [comment]
That's good to know, thanks for clarifying.

**Comment by HongYang57** [comment]
Thank you very much.
