### ISSUE TITLE
`sympref reset` should try harder

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#87]
Try a hard Fourier transform---or perhaps even an easy one :(

```
syms x k
f = exp((x-1)^2)
fourier(f, x, k)
>> Waiting.........
```

If you ctrl-c, python is still running.

```
>> sympref reset
Resetting the octsympy communication mechanism
Closing the Python pipe...
```

And there it says.

It would be nice if `sympref reset` killed the subprocess somehow in this case.

**Comment by mtmiller** [comment]
I can't reproduce this in Octave 4.2 in terminal or GUI mode, can you? Resolved?

**Comment by cbm755** [comment]
I cannot reproduce, will close.

Note its certainly possible to get the pipe in a confused state, for example, by ctrl-c interrupting as per above, I was able to make this happen:
````
>> syms y
% lots of pseudo-xml errors
% but then try again:
>> syms y
>> y
y = PYTHON: successful variable import
>>
````
(But `sympref reset` fixes it for me.)  Nothing really to be done about that except adopt a more robust ipc!
