### ISSUE TITLE
gammainc test fails on upcoming Octave 4.4.0

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#877]
I ran our tests on stable branch of Octave, one failure:

```
octave:4> test @sym/gammainc
***** test
 % compare to double
 xs = sym(1)/1000; x = 1/1000; a = 1;
 A = gammainc (x, a);
 B = double (gammainc (xs, a));
 assert(A, B, -eps)
!!!!! test failed
ASSERT errors for:  assert (A,B,-eps)

  Location  |  Observed  |  Expected  |  Reason
     ()       0.0009995    0.0009995     Rel err 3.0373e-14 exceeds tol 2.2204e-16 by 3e-14
```
Should investigate if this is worrisome upstream, or we can just relax the tolerance.

**Comment by mtmiller** [comment]
Yeah I think this is worth reporting to Octave

    >> format long
    >> x = 1/1000;
    >> a = gammainc (x, 1);
    >> b = quad (@(t) exp(-t), 0, x);
    >> c = double (gammainc (sym(1) / 1000, 1));
    >> a, b, c
    a =    9.995001666249781e-04
    b =    9.995001666250085e-04
    c =    9.995001666250085e-04

**Comment by cbm755** [comment]
I feel like I'd found this before, when I started reviewing the 2017 GSoC specfun project but I forget if I did an upstream bug already.  Will investigate ASAP...

**Comment by mtmiller** [comment]
I'll wait for you to see what you find and report to Octave, but I think this might be a case of `exp (x) - 1` vs `expm1 (x)`, if that rings any bells.

**Comment by cbm755** [comment]
I didn't find anything in particular in my gsoc review notes.  I filed upstream https://savannah.gnu.org/bugs/?53543

**Comment by mtmiller** [comment]
Fixed upstream and `test @sym/gammainc` passes now with Octave stable.

**Comment by cbm755** [comment]
Thanks, see also d489640f160d75341b4b781bdc6252d5991f551c which un-xtests other gammainc tests on 4.3.0+
