### ISSUE TITLE
find fails on sym arrays

### ISSUE THREAD

**Issue by AKonia** [cbm755/octsympy#878]
I suppose it's octsympy problem:
```matlab
rs = solve(L, X); % where L is polynomial, X is symbolic variable 
%rsd = double(rs); % when we casts, find() on the last line works in Octave
rsd  = rs; % this is almost the same, but works in Matlab NOT in Octave. 
% choose roots by condition
lb = -5;
rb = 1;
rs(find(rsd > lb & rsd < rb)) % HERE DOESN'T WORK  if we use this 
```
I suppose it's happening because of different return types of '<' and '>' with symbolic and octave, octsympy returns boolean, but find waits for vector of 0 and 1 
![_2018-03-29_22-47-54](https://user-images.githubusercontent.com/7058335/38110123-42c6124c-33a3-11e8-8478-22e471cef3ad.png)

**Comment by mtmiller** [comment]
So to summarize, in Matlab, `find` can act on an argument of type `@sym` by evaluating the logical value of each array element. In Octave we do have `if` working on `@sym` values, but not `find`.

This could possibly be handled by a `@sym/find` overload, but it might be more efficient if Octave could allow class arguments.

The incompatibility is not in the `<` and `>` operators, because I think Matlab also returns a symbolic value for an expression like `sym(1) > 0`.

**Comment by cbm755** [comment]
A nice workaround is:
```
rs(find(logical(rsd > lb & rsd < rb)))
```
which is probably what core Octave's `find` should be doing: the objects can implement `logical` if they want---as we do.  See #191 and bugs linked within---@mtmiller already fixed `if`, maybe some others.

It is quite hard (but IIRC not impossible) to make a symbolic boolean object in SMT.

**Comment by cbm755** [comment]
> is probably what core ... should be doing

Perhaps this is not true.  Find is supposed to "Return a vector of indices of nonzero elements of a matrix".  But is that exactly what converting to logical is supposed to do in all cases?

It would be great to have the output of the following from Matlab's SMT:
```
help sym/find
syms x real
syms r positive
syms z
find([0 1 2 x r z x^2+1])
```

**Comment by mtmiller** [comment]
Also `which -all find` may show if there is more than one overloaded find function.

**Comment by mtmiller** [comment]
I got someone to run this in Matlab for me

```
>> help sym/find

FIND    Find non-zero elements of symbolic arrays

>> syms x real
>> syms r positive
>> syms z
>> find([0 1 2 x r z x^2+1])
ans =

    2   3   4   5   6   7

>> class(find([0 1 2 x r z x^2+1]))
ans = 'double'
```

**Comment by cbm755** [comment]
Sympy has a nice thing where asking is `x` to nonzero can return `True`, `False` or `None`.  SMT does not generally do this.  In general, I'd like to stay closer to Sympy.

```
octave:12> A = [0 1 2 x r z x^2 + 1]
A = (sym 1×7 matrix)
  ⎡                   2    ⎤
  ⎣0  1  2  x  r  z  x  + 1⎦
octave:13> A == 0
ans = (sym) [True  False  False  x = 0  False  z = 0  False]  (1×7 matrix)
octave:14> A ~= 0
ans = (sym) [False  True  True  x ≠ 0  True  z ≠ 0  True]  (1×7 matrix)
```
`logical` generally converts the indeterminable stuff to true.
```
octave:16> logical(A ~= 0)
ans =
  0  1  1  1  1  1  1
```

Although:
```
octave:17> logical(A)
error: logical: cannot reliably convert sym to bool
error: called from
    logical at line 124 column 5
```
I thought `logical(A([1 2 3 5 7]))` would work without : I think that might be a separate bug: filed #880.

**Comment by cbm755** [comment]
FTR, here's my recipe for creating a symbolic boolean object in SMT---it used to work but I haven't checked recently.
```
>> syms x y       
>> A = [x y] == [x x]    
A =
[ x == x, y == x]
>> B = simplify(A)
B =
[ TRUE, x == y]
>> symboolean = B(1)
symboolean =
TRUE
>> if (symboolean), disp('hello'), end
hello
```
