### ISSUE TITLE
dsolve: SymPy exception when coefficient is sqrt of sym

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#883]
As originallly reported in Octave [#53576](https://savannah.gnu.org/bugs/?53576), dsolve raises an exception when solving a third-order differential equation with a sqrt as one of the coefficients.

Simplest example to reproduce this:

    syms f(x)
    dsolve (sqrt (sym (2)) * diff (f, 3) + diff (f) == 0)

SymPy equivalent code to reproduce this:

    from sympy import Derivative, Function, dsolve, sqrt
    from sympy.abc import x
    f = Function('f')
    dsolve(sqrt(2) * Derivative(f(x), x, x, x) + Derivative(f(x), x))

The exception is

    NotImplementedError: CRootOf is not supported over EX

Replacing the `sqrt(2)` coefficient with anything rational works around this issue. I'm not sure if this is already a known issue in SymPy or not.

**Comment by cbm755** [comment]
This specific case is fixed upstream, so will be in the next sympy 1.4, although there are still other cases that can hit the same error message: https://github.com/sympy/sympy/issues/15520

**Comment by cbm755** [comment]
I think I'll close for now, let the other cases run their course upstream.
