### ISSUE TITLE
Octave GUI shows all nonscalar sym as dimension `1x1`

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#89]

**Comment by latot** [comment]
This is already fixed (status of the bug confirm it)
```
>> A = [x 2*x; 3*x 4*x]
A = (sym 2×2 matrix)

  ⎡ x   2⋅x⎤
  ⎢        ⎥
  ⎣3⋅x  4⋅x⎦

>> size(A)
ans =

   2   2
```
from GUI.

**Comment by mtmiller** [comment]
ack, looks fixed in 4.0.3 and in 4.2.0-rc2

**Comment by cbm755** [comment]
Ok, just to be clear, this bug is not about what `size()` says, it about what appears in the "Workspace" pane of the GUI.  But anyway, it does look fixed.

**Comment by cbm755** [comment]
And thank you both for checking!
