### ISSUE TITLE
coeffs missing

### ISSUE THREAD

**Issue by Erik999erik** [cbm755/octsympy#904]
Hello,
I use the symbolic package 2.7.0 
and in the following code snipping

syms xx m
solve(xx == 2*xx + 6, x)

bb=[-2, -1, 0, 1, 2];
cc=polyout(bb,'m')
cc
[c9, t9] = coeffs(cc)

the function solve works, whereas coeffs throw an error:
error: 'coeffs' undefined near line 1

Thanks in advance Erik

**Comment by cbm755** [comment]
The problem here is that `cc` is just a string (`char`) not a symbolic object.

Try:
```
>> bb = [-2 -1 0 1 2]
bb =

          -2          -1           0           1           2

>> cc = poly2sym(bb, m)    # note this step
cc = (sym)

       4    3        
  - 2⋅m  - m  + m + 2

>> [c9, t9] = coeffs(cc, 'all')
c9 = (sym) [-2  -1  0  1  2]  (1×5 matrix)
t9 = (sym 1×5 matrix)

  ⎡ 4   3   2      ⎤
  ⎣m   m   m   m  1⎦
```
