### ISSUE TITLE
Matlab expat XML_SetHashSalt problem

### ISSUE THREAD

**Issue by ladmanj** [cbm755/octsympy#905]
Hi 
While working fine with octave, on matlab i got errors.
Even i have reinstalled python, updated all packages, reinstalled expat library, i still see this report:

The linked  /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so does contain XML_SetHashSalt symbol

    >> sympref diagnose
    Symbolic package diagnostics
    ============================
    Python and SymPy are needed for most features of the Symbolic package.
    The Python interpreter is currently: "python".
    Computers may have more than one Python interpreter installed.  If you
    need to, you can select a different one using the PYTHON environment
    variable (see "help sympref").  For example, to use Python 3, try
        setenv PYTHON python3
        sympref reset
    Attempting to run python -c "print(\"Python says hello\")"
    
    
    status =
    
         0
    
    
    output =
    
        'Python says hello
     '
    
    Good, Python ran correctly.
    SymPy Python Library
    --------------------
    SymPy is a Python library used by Symbolic for almost all features.
    Attempting to run python -c "import sympy; print(sympy.__version__)"
    
    
    status =
    
         0

    output =
    
        '1.1.1
         '

    SymPy must be at least version 1.0; you have version 1.1.1.
    We cannot automatically compare versions on Matlab: please verify above.
    Good, a working version of SymPy is installed.
    Python XML Parsing and DOM Support
    ----------------------------------
    The XML DOM library is used by Symbolic for passing values to and from Python.
    Some older versions of Python formatted XML output differently.  As long as you
    have any reasonably recent version of Python, this should pass.
    Attempting to run python -c "import xml.dom.minidom as minidom; doc = minidom.parseString(\"        <item>value</item>\"); print(doc.toprettyxml(indent=\"\"))"
    
    
    status =
    
         1
    
    
    output =
    
        'Traceback (most recent call last):
           File "<string>", line 1, in <module>
           File "/usr/lib/python2.7/xml/dom/minidom.py", line 1927, in parseString
             from xml.dom import expatbuilder
           File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 32, in <module>
             from xml.parsers import expat
           File "/usr/lib/python2.7/xml/parsers/expat.py", line 4, in <module>
             from pyexpat import *
         ImportError: /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so: undefined symbol:     XML_SetHashSalt
         '
    
    Unfortunately status was non-zero: perhaps Python cannot import xml.dom?
      * Is there an error message above?
      * Are you using an unusual Python installation?  If not, please try to
        reinstall it and try again.
    >>

**Comment by mtmiller** [comment]
Take a look at [this Matlab forum post](https://www.mathworks.com/matlabcentral/answers/267099-matlab-s-python-engine-crashes-minidom).

It seems that Matlab includes its own libexpat shared library, which is older than the system libexpat that Python intended to link with.

I'm not sure if any of the workarounds in the thread will help, but you might also try `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libexpat.so.1` in the environment before starting Matlab.

**Comment by ladmanj** [comment]
Dne 2.8.2018 v 22:50 Mike Miller napsal(a):
>
> Take a look at this Matlab forum post 
> <https://www.mathworks.com/matlabcentral/answers/267099-matlab-s-python-engine-crashes-minidom>.
>
> It seems that Matlab includes its own libexpat shared library, which 
> is older than the system libexpat that Python intended to link with.
>
> I'm not sure if any of the workarounds in the thread will help, but 
> you might also try 
> |LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libexpat.so.1| in the 
> environment before starting Matlab.
>
Unfortunately i have tried LD_PRELOAD already with no luck.
Maybe i will try also replacing matlab's libexpat.so.1 with symlink to 
the system one.
J.

**Comment by ladmanj** [comment]
Making the library coming with matlab invisible/unloadable solved the 
problem, but maybe i will encounter some side effects ...

$ mv /opt/MATLAB/R2018a/bin/glnxa64/libexpat.so.1 
/opt/MATLAB/R2018a/bin/glnxa64/libexpat.so.1.backup
$ mv /opt/MATLAB/R2018a/bin/glnxa64/libexpat.so.1.5.0 
/opt/MATLAB/R2018a/bin/glnxa64/libexpat.so.1.5.0.backup

J.

Dne 2.8.2018 v 22:50 Mike Miller napsal(a):

**Comment by cbm755** [comment]
Haven't read this whole thread but is this #63?

**Comment by mtmiller** [comment]
@cbm755 yeah, looks the same to me.

**Comment by cbm755** [comment]
Ok thanks.  @ladmanj, see #63 for workarounds, let us know if they work for you.
