### ISSUE TITLE
problem!

### ISSUE THREAD

**Issue by JavierGamonal** [cbm755/octsympy#907]
hi guys, i tried to install the symbolic package in my computer, i downloaded the zip file with the whole bundle, but i got this error when i try to make use of 'syms'

error: 'assumptions' undefined near line 93 column 15
error: called from
    syms at line 93 column 13

what can i do???

thanks

**Comment by cbm755** [comment]
Maybe you or something on your filesystem changed the class files while Octave was running?

Try "clear all; clear classes" and/or restarting Octave

**Comment by JavierGamonal** [comment]
thanks!, but i got the same error

>> clear all
>> clear classes
>> syms x
warning: the 'syms' function belongs to the symbolic package from Octave Forge
which you have installed but not loaded.  To load the package, run 'pkg
load symbolic' from the Octave prompt.

Please read <https://www.octave.org/missing.html> to learn how you can
contribute missing functionality.
error: 'syms' undefined near line 1 column 1
>> pkg load syms
error: package syms is not installed
error: called from
    load_packages at line 41 column 7
    pkg at line 457 column 7
>> pkg load symbolic
>> syms x
error: 'assumptions' undefined near line 93 column 15
error: called from
    syms at line 93 column 13
>> syms X
error: 'assumptions' undefined near line 93 column 15
error: called from
    syms at line 93 column 13

**Comment by cbm755** [comment]
There seems to be a lot of extra stuff in there.

Restart Octave, type "pkg load symbolic".  Type "sympref diagnose".  What happens?

I still guess something is changing the filesystem underneath Octave, like antivirus software.  Or maybe there is something actually broken in your install of Symbolic or Octave.

What version of Octave?  What version of Windows?  Latest version of Symbolic?

**Comment by JavierGamonal** [comment]
Octave 4.4.1
Symbolic 2.7.0
Windows 10
Avast!

> Restart Octave, type "pkg load symbolic". Type "sympref diagnose". What happens?
error: Invalid call to sympref.  Correct usage is:

 -- Function File: R = sympref ()
 -- Function File: R = sympref (CMD)
 -- Function File: sympref CMD
 -- Function File: sympref CMD ARGS

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at https://www.octave.org and via the help@octave.org
mailing list.




> Also might try showing the output of

pkg load symbolic
which syms
which sympref
which assume
which assumptions
All four of these functions should be in the same directory.

which syms
'syms' is a function from the file C:\Octave\OCTAVE~1.1\share\octave\packages\symbolic-2.2.2\syms
.m
>> which sympref
'sympref' is a function from the file C:\Octave\OCTAVE~1.1\share\octave\packages\symbolic-2.2.2\s
ympref.m
>> which assume
>> which assumptions

**Comment by cbm755** [comment]
Looks like you have an older `symbolic-2.2.2` around.  Probably they are conflicting somehow

**Comment by mtmiller** [comment]
> Symbolic 2.7.0
> …
> 'syms' is a function from the file C:\Octave\OCTAVE~1.1\share\octave\packages\symbolic-2.2.2\syms
.m

It looks like you have symbolic version 2.2.2 installed, not 2.7.0. Maybe the install did not complete or work like you think it did.

**Comment by JavierGamonal** [comment]
yess that was the problem, now it's everything okay


thank you guys <3

**Comment by cbm755** [comment]
Our pleasure, please report any issues you find.
