### ISSUE TITLE
problem:(

### ISSUE THREAD

**Issue by JavierGamonal** [cbm755/octsympy#909]
hi guys i just got this problem trying to solve a DE

>> syms y(x)
Symbolic pkg v2.7.0: Python communication link active, SymPy v1.2.
>> syms y(x)
>> ED= diff(y(x))-W(1,i)*y(x)==0
error: 'W' undefined near line 1 column 16
>> dsolve(ED)
error: 'ED' undefined near line 1 column 8
>> syms #
Symbolic variables in current scope:
  x
  y (symfun)
>> syms E
>> ED= diff(y(x))-E*y(x)==0
ED = (sym)

            d
  -E*y(x) + --(y(x)) = 0
            dx

>> dsolve
>> dsolve(ED)
ans = (sym)

             E*x
  y(x) = C1*e

>> dsolve(ED,y(0)=1)
error: Python exception: AttributeError: 'float' object has no attribute 'rhs'
    occurred at line 5 of the Python code block:
    ics2[s.lhs] = s.rhs
error: called from
    python_cmd at line 179 column 7
    dsolve at line 189 column 10

may you help me

**Comment by JavierGamonal** [comment]
> >> syms y(x)
> Symbolic pkg v2.7.0: Python communication link active, SymPy v1.2.
> >> syms y(x)
> >> ED= diff(y(x))-W(1,i)*y(x)==0
> error: 'W' undefined near line 1 column 16
> >> dsolve(ED)
> error: 'ED' undefined near line 1 column 8
> >> syms #
> Symbolic variables in current scope:
>   x
>   y (symfun)
> >> syms E
> >> ED= diff(y(x))-E*y(x)==0
> ED = (sym)
> 
>             d
>   -E*y(x) + --(y(x)) = 0
>             dx
> 
> >> dsolve
> >> dsolve(ED)
> ans = (sym)
> 
>              E*x
>   y(x) = C1*e
> 
> >> dsolve(ED,y(0)=1)
> error: Python exception: AttributeError: 'float' object has no attribute 'rhs'
>     occurred at line 5 of the Python code block:
>     ics2[s.lhs] = s.rhs
> error: called from
>     python_cmd at line 179 column 7
>     dsolve at line 189 column 10

**Comment by JavierGamonal** [comment]
![sin titulo](https://user-images.githubusercontent.com/43260034/45722633-aa798280-bb83-11e8-8fdf-2794cb2dda9c.png)

**Comment by JavierGamonal** [comment]
dont worry it's okay!!

**Comment by cbm755** [comment]
That was easy ;-)
