### ISSUE TITLE
'jordan' function causing crash

### ISSUE THREAD

**Issue by akselsd** [cbm755/octsympy#922]
The following snippet

```
A = sym([1 1 1 0; -2 -1 0 -1; 0 0 -1 -1; 0 0 2 1]);
[V, D] = jordan(A);
```

causes Octave to hang, and after a few minutes outputs the following:

Waiting.........................................
error: Python exception: TypeError: Cannot multiply <class 'sympy.matrices.dense.MutableDenseMatrix'> and <type 'NoneType'>
    occurred at line 7 of the Python code block:
    return A.jordan_form(calctrans)
error: called from
    python_cmd at line 179 column 7
    jordan at line 136 column 10
    problem3 at line 3 column 6

It is working correctly for other matrices. Running Ubuntu 18 LTS, Octave 4.2.2 and Symbolic 2.7.1

**Comment by cbm755** [comment]
Without `D` is does finish but the result is wrong:

```
>> A
A = (sym 4×4 matrix)
  ⎡1   1   1   0 ⎤
  ⎢              ⎥
  ⎢-2  -1  0   -1⎥
  ⎢              ⎥
  ⎢0   0   -1  -1⎥
  ⎢              ⎥
  ⎣0   0   2   1 ⎦

>> eig(A)
ans = (sym 4×1 matrix)
  ⎡ⅈ ⎤
  ⎢  ⎥
  ⎢ⅈ ⎥
  ⎢  ⎥
  ⎢-ⅈ⎥
  ⎢  ⎥
  ⎣-ⅈ⎦

>> jordan(A)
ans = (sym 10×10 matrix)
  ⎡-ⅈ  1   0  0  0  0  0  0  0  0⎤
  ⎢                              ⎥
  ⎢0   -ⅈ  0  0  0  0  0  0  0  0⎥
  ⎢                              ⎥
  ⎢0   0   ⅈ  1  0  0  0  0  0  0⎥
  ⎢                              ⎥
  ⎢0   0   0  ⅈ  1  0  0  0  0  0⎥
  ⎢                              ⎥
  ⎢0   0   0  0  ⅈ  1  0  0  0  0⎥
  ⎢                              ⎥
  ⎢0   0   0  0  0  ⅈ  0  0  0  0⎥
  ⎢                              ⎥
  ⎢0   0   0  0  0  0  ⅈ  1  0  0⎥
  ⎢                              ⎥
  ⎢0   0   0  0  0  0  0  ⅈ  0  0⎥
  ⎢                              ⎥
  ⎢0   0   0  0  0  0  0  0  ⅈ  1⎥
  ⎢                              ⎥
  ⎣0   0   0  0  0  0  0  0  0  ⅈ⎦
```

This will need to be fixed in [upstream SymPy](https://github.com/sympy/sympy/issues).  If you have some time, you could help by checking if there is an upstream issue already.

**Comment by cbm755** [comment]
I bisected this to a regression upstream: https://github.com/sympy/sympy/issues/15858
