### ISSUE TITLE
[maint] migrate CI to docker for OCT=daily, all versions?

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#943]
The current way I'm providing an Octave binary for the Travis native Ubuntu environment isn't working right now, and I need to rework some things to get the daily build working again, including updating to a newer Ubuntu baseline.

I think it would be more robust (isolation from Travis runtime environment) if CI here pulled a docker image that provided the daily build of Octave. Travis provides docker, and wouldn't matter which old Ubuntu baseline it uses. This would also work better with other CI more tightly integrated with docker (e.g. GitLab CI). And I believe Travis caches docker images globally so it should be optimized.

Posting here in case you have any thoughts on how this should work before I start overhauling everything.

I'm envisioning a docker image with `octave` as the default entry point, and from there the user can run interactively or pass a file or a `--eval` option as normal. Different tags would yield different stable versions of Octave, the `devel` tag would give the latest daily build.

For example

    docker pull mtmiller/octave:5.1.0
    docker run mtmiller/octave:5.1.0 octave --eval "r = octsympy_tests; exit(r)"
    docker pull mtmiller/octave:devel
    docker run mtmiller/octave:devel octave --eval "r = octsympy_tests; exit(r)"

If I get this working, including previous stable versions of Octave under different tags (including a `latest` tag for the current stable release), would that solve all of your CI needs for different versions of Octave? Should also allow customization, equivalent of Travis `before_install` and `install`, before running Octave commands.

**Comment by mtmiller** [comment]
@cbm755 Obviously no need to act on this now, just looking for an easy public place to pick your brain as a primary user of my Octave daily builds, which are now stalled.

**Comment by cbm755** [comment]
I don't really know much about docker.  But it definitely sounds good to be able to have specific Octave versions.

I like the idea of Gitlab CI running for Octave-Forge packages, like what Gnome and Fedora are both doing.

What would this do?
```
docker run mtmiller/octave:5.1.0 octave --eval "pkg install -forge optim"
```
Would it put the compiled optim code in `$HOME/octave/...` or within the docker image?

**Comment by mtmiller** [comment]
The docs are really good :wink: 

But I think the biggest advantages are independence from whatever Ubuntu baseline Travis happens to choose, and flexibility to work with other CI and provisioning tools. Also allows easier local testing instead of just throwing syntax at Travis and hoping for the best, which is mostly my Travis experience.

> What would this do?

Every `docker run` command creates a new container that destroys itself as soon as its primary command exits. So

    docker run mtmiller/octave:5.1.0 octave --eval "pkg install -forge optim"

would instantiate a new container, run that octave command, install the optim package in the container's Octave directory as root (`pkg install -global` by default as root), and then shut itself down, all changes discarded.

The normal docker use case is "here's my pristine service or web application image, boot it as a docker service, it runs in the foreground indefinitely, and when it is told to shut down the container cleans up after itself".

That said, there are definitely a few ways to replicate the CI model of pre-install, install, run test script, log results. Just to assure you it's possible, here's a quick real example I did on my command line

    $ docker run --cidfile=/tmp/container --detach --init debian:latest sleep inf
    $ CONTAINER=`cat /tmp/container`
    $ docker exec $CONTAINER bash -c "type octave"
    bash: line 0: type: octave: not found
    $ docker exec $CONTAINER apt-get update
    …
    $ docker exec $CONTAINER apt-get install -y octave
    …
    $ docker exec $CONTAINER octave --version
    GNU Octave, version 4.0.3
    Copyright (C) 2016 John W. Eaton and others.
    $ docker stop $CONTAINER

For the case of this theoretical Octave image, it might be something like

    docker run --cidfile=/tmp/container --detach --init mtmiller/octave:latest sleep inf
    docker exec $(cat /tmp/container) octave --eval "pkg install -forge optim"
    docker exec $(cat /tmp/container) octave --eval "runtests ([OCTAVE_HOME, '/share/octave/packages/optim-x.y.z'])"

or to run the octsympy CI

    docker run --cidfile=/tmp/container --detach --init --volume=$PWD:/octsympy mtmiller/octave:latest sleep inf
    docker exec $(cat /tmp/container) pip install sympy==$SYMPY_VERSION
    docker exec $(cat /tmp/container) octave --path=/octsympy/inst --eval "r = octsympy_tests; exit(r)"

This is probably more than enough detail for now, hopefully just enough to show how I imagine this Octave container approach working and applying to installing system packages, installing Octave packages, and running test scripts.

**Comment by cbm755** [comment]
I think I see.  My understanding from your examples: you can start it with `docker run` and then its persistent (enough) to feed it several commands with `docker exec`.

Sounds great to me.

**Comment by mtmiller** [comment]
`mtmiller/octave` is now active, only 5.1.0 done for now. I will probably incrementally add more tags and versions, including 6.0.0.

```
$ docker run mtmiller/octave octave --eval "ver"
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
----------------------------------------------------------------------
GNU Octave Version: 5.1.0 (hg id: d05d6eebde10)
GNU Octave License: GNU General Public License
Operating System: Linux 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64
----------------------------------------------------------------------
no packages installed.
```

* [mtmiller/octave on Docker Hub](https://hub.docker.com/r/mtmiller/octave)
* built from [mtmiller/docker-octave on GitLab](https://gitlab.com/mtmiller/docker-octave)

**Comment by mtmiller** [comment]
Based on the current CI matrix, the docker replacement should provide at least "stable" and "devel" versions of Octave. Do you agree that's the minimum Octave support to start working on migrating the CI to docker?

https://gitlab.com/mtmiller/docker-octave/issues/2

**Comment by cbm755** [comment]
I think the minimum would be just 5.0.0 and more could be added later...

I think the ppa was/is providing 4.2 (?).  Ideally docker would provide these too.  I'd like to be able to test:
  * minimum version (currently 4.2 for this project)
  * all major versions between min version and stable (i.e., 4.4.2 for this project).
  * stable
  * devel

In a way, devel is *less* important than those historical versions.
