### ISSUE TITLE
rewrite as "sincos"

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#945]
Following up on some comments in https://savannah.gnu.org/bugs/?55968#comment6 which are being conflated with an unrelated issue of normalized versus unnormalized sinc function.

@mtmiller: on Matlab R2015b I had someone run:
```
>> rewrite(tan(x)/x, 'sinco') 
Error using sym/rewrite (line 62)
The value of 'T' is invalid. It must satisfy the function:
@(x)any(strcmp(x,{'sin','cos','tan','sincos','exp','log','heaviside','sqrt'})).
 
>> rewrite(tan(x)/x, 'sinc') 
Error using sym/rewrite (line 62)
The value of 'T' is invalid. It must satisfy the function:
@(x)any(strcmp(x,{'sin','cos','tan','sincos','exp','log','heaviside','sqrt'})).
 
>> rewrite(tan(x)/x, 'sin') 
 
ans =
 
-sin(x)/(x*(2*sin(x/2)^2 - 1))
 
>> rewrite(tan(x)/x, 'sincos')
 
ans =
 
sin(x)/(x*cos(x)) 
```
These are reasonable results.  Note difference b/w `sin` and `sincos`.

Maybe other versions of Matlab's SMT give something different...

We should:

  * support `sin` (we do)
  * ideally for SMT compat, we could support `sincos` (unlikely that we do).
  * `sinco` should be either an error or silently do nothing, same as `zzzzZZzz`

Finally, I think `sinc` should rewrite in terms of sinc function.  It certainly should not be some abbreviation for `sincos`.

**Comment by mtmiller** [comment]
Ok, that's different from what I see on Matlab's "Try this in your browser", which is running R2019a.

```
rewrite(tan(x)/x, 'sinc')
ans =

  sin(x)/(x*cos(x))
```

Anyway, yeah, I also don't like how Matlab tends to accept arbitrary abbreviations in various functions, sometimes.

My version of SymPy does already support `sincos`, so that part is done.

**Comment by mtmiller** [comment]
With Octave 5.1, SymPy 1.3, this is already done?

```
>> syms x
Symbolic pkg v2.7.1: Python communication link active, SymPy v1.3.
>> rewrite (tan(x)/x, 'sincos')
ans = (sym)

   sin(x) 
  ────────
  x⋅cos(x)

```
