### ISSUE TITLE
[maint] python_header.py: license unrecognized by `licensecheck`

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#951]
`# Copyright (C) ...`
`# Free Software without warranty, GPL-3.0+: see python_header.m`

[licensecheck](https://metacpan.org/pod/distribution/App-Licensecheck/bin/licensecheck) doesn't like that. 

I tried:
`# License: GPL-3.0-or-later, see python_header.m`
and various other strings but I haven't found something that works for GPL.

This is ok (except its the wrong license):
`# License: BSD-3-Clause, blah blah blah`

Should probably file upstream bug.

CC @mtmiller FYI

**Comment by mtmiller** [comment]
Yeah, I've only had luck with licensecheck on the full recommended GPL header.

Personally I'd rather see [this upstream bug](https://bugs.debian.org/904518) fixed and use

    SPDX-License-Identifier: GPL-3.0-or-later

**Comment by cbm755** [comment]
In licensecheck's defense here, IIRC FSF does not recommend abbreviating the GPL.  Whereas that is common practice for BSD.

But sometimes there are constraints (in this case, the .py file needs to fit in a buffer in one of our experimental IPC mechanisms).

Anyway, certainly agree about `SPDX-License-Identifier`
