### ISSUE TITLE
docs: functions with arguments that switch order in SymPy 

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#952]
- [x] gammainc
- [x] igamma
- [ ] lambertw
- [ ] others?

**Comment by mtmiller** [comment]
I added `lambertw` to your list (does GitHub notify you if I edit your post?).

`gammainc` and `igamma` are switched order with respect to each other, and that's already documented in `@sym/igamma.m`. `igamma(n, x)` is the same as Python `uppergamma(n, x)`.

**Comment by cbm755** [comment]
Thanks!

> notify you if I edit your post?

apparently not.

**Comment by cbm755** [comment]
igamma and gammainc are not really the issue here: they are backwards in Matlab's SMT too.  I did find and fix other bugs in gammainc in #956.
