### ISSUE TITLE
Last UTF character breaks terminal on Windows

### ISSUE THREAD

**Issue by E3V3A** [cbm755/octsympy#981]
I'm not sure how to report this properly, since I  just tried to install this a few moments ago. 

Trying to follow the examples, it seem to sort-of  work. However, when the last UTF-8 (?) character is printed, it just prints a garbage symbol and then the CLI prompt become useless. I.e. doesn't react to any further commands. 

This is the output I get, using Octave 5.1.0 (for Win64 on Win-8.1).

![octave-gui_2019-05-10_18-43-19](https://user-images.githubusercontent.com/194392/57539896-03786f80-733b-11e9-8cf3-de53d1cca977.png)

BTW. How can I check which Python interpreter is used by the SymPy ?  
(I have 4 installed, with SymPy in all of them, but haven't set any `PYTHON` var.)

**Comment by E3V3A** [comment]
A related issue seem to be:
*  point 5 in: https://github.com/cbm755/octsympy/issues/83#issuecomment-217352182
* #941 
* #912

**Comment by cbm755** [comment]
`sympref diagnose` should tell you some stuff (e.g., python version).

As for the rest, I agree it looks a lot like https://github.com/cbm755/octsympy/issues/83#issuecomment-217352182

I don't know what to do about any of this except wait for some motivated windows developer to fix upstream Octave.  In the meantime, this package just has `unicode=false` on Windows.  Not ideal.

**Comment by E3V3A** [comment]
@cbm755 
Yes, it's really a shame, since it pretty much works and then falls on the finishing line. Unfortunately I am not going to report anything on that shamelessly useless *Savannah* bug tracking system. I'm fed up with these old/email based bug tracking that is so poorly maintained that stuff reported more than 3 years ago, still haven't been properly addressed. If they were to migrate to GitHub I'd reconsider, but any useful contributions get lost in the bureaucratic filing process over there.

**Comment by cbm755** [comment]
I certainly understand your frustration with the upstream tooling, but I think an even more urgent issue is a lack of developers.  Octave is all volunteers, and probably not enough of them run Windows systems themselves.

If you're good with Windows, an important (and faster moving) Octave project that could probably use your help would be https://gitlab.com/mtmiller/octave-pythonic/

**Comment by mtmiller** [comment]
> If you're good with Windows, an important (and faster moving) Octave project that could probably use your help would be https://gitlab.com/mtmiller/octave-pythonic/

Yes please! :pray:

**Comment by E3V3A** [comment]
>  but I think an even more urgent issue is a lack of developers. Octave is all volunteers, and probably not enough of them run Windows systems themselves.

That's why it should be moved to Github. Every project which moves here, get a lot more attention and rapid development.

**Comment by cbm755** [comment]
That would certainly get more attention.  Gitlab.com more likely b/c it runs on Free Software.   Least friction of all might be if FSF hosted a gitlab instance, ideally with easy scripts to migrate issues from Savannah...  These would help but no magic bullet; someone still has to do the work.

Please help if you can.  And consider this: if we each only contributed to projects whose every tooling detail matched our own preferences, than we'd probably contribute nothing. 

All of this is a bit off topic for this little project.

**Comment by mtmiller** [comment]
I'm now mirroring Octave on both [GitHub](https://github.com/mtmiller/octave) and [GitLab](https://gitlab.com/mtmiller/octave), and I will be monitoring PRs in both places, so let's see if that brings any more attention.

**Comment by E3V3A** [comment]
Great! @cbm755  Maybe link to that repo in README, so people can see it.

**Comment by cbm755** [comment]
> Maybe link to that repo in README, so people can see it.

You mean in Octave, yes someday I think.  Here in the Symbolic pkg?  That doesn't feel appropriate.

> you have not enabled the issues!?

We cannot expect @mtmiller to act a human filter between those mirrors and official Octave in all cases.  I think he's trialing this for MR/PR first, while its a solo effort...  OTOH, it wouldn't surprise me if the official project eventually follows, especially if a community starts to grow around the mirrors...

@mtmiller: I suppose it might be technically possible to try to mirror the issues.  But most projects I've seen doing this do a one-way migration (e.g., off of code.google onto github).

**Comment by mtmiller** [comment]
> But, eeeh... you have not enabled the issues!?

Yes, it would be pointless to have two independent bug trackers for Octave. The official bug tracker lives on Savannah (yes, I also dislike Savannah, but it is what we use).

> People generally don't send PR's, especially if they don't know what the issues are!

It's easy to know what the issues are, Savannah is public and searchable and indexed by Google.

If the argument is "using hg and sending patch attachments to Savannah creates a high bar for contribution", then I agree, and I believe I am doing everything I can to help to lower that bar.

If the argument is "users only know how to use GitHub", then it's likely that there is nothing we can do to encourage them to contribute to Octave anyway.

**Comment by E3V3A** [comment]
> Yes, it would be pointless to have two independent bug trackers for Octave. The official bug tracker lives on Savannah (yes, I also dislike Savannah, but it is what we use).

It's a good start! :+1:

**Comment by mtmiller** [comment]
> Savannah lovers

:rofl: I don't think there are any.
