### ISSUE TITLE
default to ipc=native if pythonic is available

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#982]
Now that pythonic is a package, and presumably we think it will eventually be a dependency, maybe we should default to `ipc=native` and fall back to `ipc=popen2`.

Or we can wait until there is at least an (alpha) released version pythonic.

See merged PR #980, where some of the testing logic could be simpler...

**Comment by mtmiller** [comment]
I plan to make and announce a 0.0.1 release very soon. I want to try to fix [octave-pythonic#14](https://gitlab.com/mtmiller/octave-pythonic/issues/14) first. And please report any other things you think should be fixed urgently.

I think this is a fair idea and worth trying to see if it causes any major problems. It would probably be helpful to have `sympref diagnose` report this so you can easily redirect bugs to pythonic.

**Comment by cbm755** [comment]
I'm having second thoughts about doing this yet b/c of https://gitlab.com/mtmiller/octave-pythonic/issues/21

In a long session, I think the user going to run up a very large number of python strings that are never getting deleted...

On the other hand, if user has done `pkg load pythonic`, maybe she can expect some breakage...?

**Comment by mtmiller** [comment]
> On the other hand, if user has done `pkg load pythonic`, maybe she can expect some breakage...?

That's how I look at it. We should make it easy to diagnose if/when things break, direct users to use `sympref ipc popen` or not to load the package, etc.

**Comment by cbm755** [comment]
Thanks!

My PR #991 adds a special `sympref diagnose` when on Pythonic.  I think it says how to go back to `popen2`.  Could probably tweak sympref docs more if needed.  

Anyway, sounds like we agree so I'll merge it soon.
