### ISSUE TITLE
[maint] CI testing should use a release of pythonic?

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#985]
Should we use releases of pythonic for our CI testing?  Then we could move it out of "allowed-to-fail".

OTOH, maybe nice to test against git master pythonic.

[Why don't we have both?](https://knowyourmeme.com/memes/why-not-both-why-dont-we-have-both)

**Comment by mtmiller** [comment]
It would certainly help pythonic if you test against both, if you don't mind the extra turnaround time.
