### ISSUE TITLE
Implement sort

### ISSUE THREAD

**Issue by cbm755** [cbm755/octsympy#99]

**Comment by trueutkarsh** [comment]
I am new to octsympy 
can some more description be provided so that i can work on it ?

**Comment by cbm755** [comment]
Look at `sort` for doubles in Octave `sort([4 5 1 6])` for example.  Its low priority but `sort([sym(1) sym(0)]` should behave similarly.

Getting the two-output form work could be messy, see `inst/@sym/min.m`.

**Comment by trueutkarsh** [comment]
@cbm755  so I need to make a new function(and a coresponding file) for symbols or have to make changes in existing sort.m function .?

**Comment by cbm755** [comment]
yes, you would need to create `inst/@sym/sort.m`.

**Comment by trueutkarsh** [comment]
please see #372 
let me know if I missed something.

**Comment by cbm755** [comment]
@trueutkarsh just FYI: you can put "Fixes #99" in one of your commit message bodies (i.e., line 3 or later) and github will automatically close an issue when the PR is merged.

**Comment by trueutkarsh** [comment]
@cbm755 I'll keep that in mind for future commits.
