### ISSUE TITLE
Should we change `defaultpython` to `python3`?

### ISSUE THREAD

**Issue by mtmiller** [cbm755/octsympy#999]
Now that it's almost 2020, should we update the `defaultpython` helper function to return `python3` by default? Obviously still useful for packagers and vendors to be able to patch this however they want, but should also be useful to the most users out of the box.

**Comment by latot** [comment]
mm, i think we can use the defaultpython from the system, but i think would be good check to be at least python3.

**Comment by cbm755** [comment]
Yes, let's do that.

**Comment by latot** [comment]
mm, thinking a little again....

Yes, there is some systems that have python linked to python2...

But, if python is linked to python v3, and for some reason, python3 is linked to a other version of python3..., what version should we use?

**Comment by cbm755** [comment]
@latot I see your point.  At the distribution level its explicitly not recommended by https://www.python.org/dev/peps/pep-0394/

We set the default: people can always change it.   Probably anyone who is aliasing or symlinking `python` to `foo` can handle `setenv PYTHON foo` as well.
